# Hmmer

## Установка hmmer

In [2]:
%%bash
wget http://eddylab.org/software/hmmer/hmmer-3.3.2.tar.gz
tar xf hmmer-3.3.2.tar.gz
cd hmmer-3.3.2

--2026-06-10 16:48:02--  http://eddylab.org/software/hmmer/hmmer-3.3.2.tar.gz
Resolving eddylab.org (eddylab.org)... 96.126.110.11, 2600:3c03::f03c:91ff:fec8:383c
Connecting to eddylab.org (eddylab.org)|96.126.110.11|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18213049 (17M) [application/x-gzip]
Saving to: ‘hmmer-3.3.2.tar.gz’

     0K .......... .......... .......... .......... ..........  0%  395K 45s
    50K .......... .......... .......... .......... ..........  0%  791K 34s
   100K .......... .......... .......... .......... ..........  0% 62.1M 22s
   150K .......... .......... .......... .......... ..........  1%  145M 17s
   200K .......... .......... .......... .......... ..........  1%  802K 18s
   250K .......... .......... .......... .......... ..........  1%  342M 15s
   300K .......... .......... .......... .......... ..........  1% 44.2M 13s
   350K .......... .......... .......... .......... ..........  2%  232M 11s
   400K .......... .......... .......... .......... ..........  2%  814K 12s
   450K .......... .......... .......... .......... ..........  2%  421M 11s
   500K .......... .......... .......... .......... ..........  3%  185M 10s
   550K .......... .......... .......... .......... ..........  3%  273M 9s
   600K .......... .......... .......... .......... ..........  3% 37.9M 8s
   650K .......... .......... .......... .......... ..........  3%  183M 8s
   700K .......... .......... .......... .......... ..........  4%  393M 7s
   750K .......... .......... .......... .......... ..........  4% 48.6M 7s
   800K .......... .......... .......... .......... ..........  4% 82.5M 6s
   850K .......... .......... .......... .......... ..........  5%  842K 7s
   900K .......... .......... .......... .......... ..........  5%  348M 7s
   950K .......... .......... .......... .......... ..........  5%  402M 6s
  1000K .......... .......... .......... .......... ..........  5%  357M 6s
  1050K .......... .......... .......... .......... ..........  6%  315M 6s
  1100K .......... .......... .......... .......... ..........  6%  302M 5s
  1150K .......... .......... .......... .......... ..........  6%  514M 5s
  1200K .......... .......... .......... .......... ..........  7%  676M 5s
  1250K .......... .......... .......... .......... ..........  7% 34.5M 5s
  1300K .......... .......... .......... .......... ..........  7%  345M 5s
  1350K .......... .......... .......... .......... ..........  7%  298M 4s
  1400K .......... .......... .......... .......... ..........  8%  327M 4s
  1450K .......... .......... .......... .......... ..........  8%  448M 4s
  1500K .......... .......... .......... .......... ..........  8%  681M 4s
  1550K .......... .......... .......... .......... ..........  8%  233M 4s
  1600K .......... .......... .......... .......... ..........  9%  138M 4s
  1650K .......... .......... .......... .......... ..........  9%  287M 4s
  1700K .......... .......... .......... .......... ..........  9%  250M 4s
  1750K .......... .......... .......... .......... .......... 10%  842K 4s
  1800K .......... .......... .......... .......... .......... 10%  333M 4s
  1850K .......... .......... .......... .......... .......... 10% 86.2M 4s
  1900K .......... .......... .......... .......... .......... 10%  535M 4s
  1950K .......... .......... .......... .......... .......... 11%  223M 4s
  2000K .......... .......... .......... .......... .......... 11%  388M 3s
  2050K .......... .......... .......... .......... .......... 11%  409M 3s
  2100K .......... .......... .......... .......... .......... 12%  669M 3s
  2150K .......... .......... .......... .......... .......... 12%  629M 3s
  2200K .......... .......... .......... .......... .......... 12% 84.4M 3s
  2250K .......... .......... .......... .......... .......... 12%  213M 3s
  2300K .......... .......... .......... .......... .......... 13%  381M 3s
  2350K .......... .......... .......... .......... .......... 13%  345M 3s
  2400K .......... .......... .......... .......... .......... 13%  383M 3s
  2450K .......... .......... .......... .......... .......... 14%  369M 3s
  2500K .......... .......... .......... .......... .......... 14%  351M 3s
  2550K .......... .......... .......... .......... .......... 14%  336M 3s
  2600K .......... .......... .......... .......... .......... 14%  250M 3s
  2650K .......... .......... .......... .......... .......... 15%  247M 2s
  2700K .......... .......... .......... .......... .......... 15%  298M 2s
  2750K .......... .......... .......... .......... .......... 15%  264M 2s
  2800K .......... .......... .......... .......... .......... 16%  272M 2s
  2850K .......... .......... .......... .......... .......... 16%  272M 2s
  2900K .......... .......... .......... .......... .......... 16%  361M 2s
  2950K .......... .......... .......... .......... .......... 16%  487M 2s
  3000K .......... .......... .......... .......... .......... 17%  594M 2s
  3050K .......... .......... .......... .......... .......... 17%  507M 2s
  3100K .......... .......... .......... .......... .......... 17%  581M 2s
  3150K .......... .......... .......... .......... .......... 17%  509M 2s
  3200K .......... .......... .......... .......... .......... 18%  637M 2s
  3250K .......... .......... .......... .......... .......... 18%  651M 2s
  3300K .......... .......... .......... .......... .......... 18%  575M 2s
  3350K .......... .......... .......... .......... .......... 19%  566M 2s
  3400K .......... .......... .......... .......... .......... 19%  539M 2s
  3450K .......... .......... .......... .......... .......... 19%  626M 2s
  3500K .......... .......... .......... .......... .......... 19%  560M 2s
  3550K .......... .......... .......... .......... .......... 20%  539M 2s
  3600K .......... .......... .......... .......... .......... 20%  863K 2s
  3650K .......... .......... .......... .......... .......... 20%  447M 2s
  3700K .......... .......... .......... .......... .......... 21%  522M 2s
  3750K .......... .......... .......... .......... .......... 21%  123M 2s
  3800K .......... .......... .......... .......... .......... 21%  342M 2s
  3850K .......... .......... .......... .......... .......... 21%  310M 2s
  3900K .......... .......... .......... .......... .......... 22%  330M 2s
  3950K .......... .......... .......... .......... .......... 22%  408M 2s
  4000K .......... .......... .......... .......... .......... 22%  281M 2s
  4050K .......... .......... .......... .......... .......... 23%  348M 2s
  4100K .......... .......... .......... .......... .......... 23%  330M 2s
  4150K .......... .......... .......... .......... .......... 23%  344M 2s
  4200K .......... .......... .......... .......... .......... 23%  286M 2s
  4250K .......... .......... .......... .......... .......... 24%  337M 2s
  4300K .......... .......... .......... .......... .......... 24%  299M 2s
  4350K .......... .......... .......... .......... .......... 24%  333M 2s
  4400K .......... .......... .......... .......... .......... 25%  375M 2s
  4450K .......... .......... .......... .......... .......... 25%  369M 2s
  4500K .......... .......... .......... .......... .......... 25%  283M 1s
  4550K .......... .......... .......... .......... .......... 25%  305M 1s
  4600K .......... .......... .......... .......... .......... 26%  363M 1s
  4650K .......... .......... .......... .......... .......... 26%  347M 1s
  4700K .......... .......... .......... .......... .......... 26%  251M 1s
  4750K .......... .......... .......... .......... .......... 26%  348M 1s
  4800K .......... .......... .......... .......... .......... 27%  360M 1s
  4850K .......... .......... .......... .......... .......... 27%  380M 1s
  4900K .......... .......... .......... .......... .......... 27%  266M 1s
  4950K .......... .......... .......... .......... .......... 28%  425M 1s
  5000K .......... .......... .......... .......... .......... 28%  458M 1s
  5050K .......... .......... .......... .......... .......... 28%  422M 1s
  5100K .......... .......... .......... .......... .......... 28%  338M 1s
  5150K .......... .......... .......... .......... .......... 29%  408M 1s
  5200K .......... .......... .......... .......... .......... 29%  463M 1s
  5250K .......... .......... .......... .......... .......... 29%  447M 1s
  5300K .......... .......... .......... .......... .......... 30%  337M 1s
  5350K .......... .......... .......... .......... .......... 30%  446M 1s
  5400K .......... .......... .......... .......... .......... 30%  456M 1s
  5450K .......... .......... .......... .......... .......... 30%  451M 1s
  5500K .......... .......... .......... .......... .......... 31%  373M 1s
  5550K .......... .......... .......... .......... .......... 31%  455M 1s
  5600K .......... .......... .......... .......... .......... 31%  806K 1s
  5650K .......... .......... .......... .......... .......... 32% 25.2M 1s
  5700K .......... .......... .......... .......... .......... 32%  375M 1s
  5750K .......... .......... .......... .......... .......... 32%  364M 1s
  5800K .......... .......... .......... .......... .......... 32%  316M 1s
  5850K .......... .......... .......... .......... .......... 33%  414M 1s
  5900K .......... .......... .......... .......... .......... 33%  434M 1s
  5950K .......... .......... .......... .......... .......... 33%  371M 1s
  6000K .......... .......... .......... .......... .......... 34%  399M 1s
  6050K .......... .......... .......... .......... .......... 34%  458M 1s
  6100K .......... .......... .......... .......... .......... 34%  420M 1s
  6150K .......... .......... .......... .......... .......... 34%  357M 1s
  6200K .......... .......... .......... .......... .......... 35%  561M 1s
  6250K .......... .......... .......... .......... .......... 35%  594M 1s
  6300K .......... .......... .......... .......... .......... 35%  665M 1s
  6350K .......... .......... .......... .......... .......... 35%  561M 1s
  6400K .......... .......... .......... .......... .......... 36%  458M 1s
  6450K .......... .......... .......... .......... .......... 36%  661M 1s
  6500K .......... .......... .......... .......... .......... 36%  583M 1s
  6550K .......... .......... .......... .......... .......... 37%  601M 1s
  6600K .......... .......... .......... .......... .......... 37%  688M 1s
  6650K .......... .......... .......... .......... .......... 37%  544M 1s
  6700K .......... .......... .......... .......... .......... 37%  459M 1s
  6750K .......... .......... .......... .......... .......... 38%  360M 1s
  6800K .......... .......... .......... .......... .......... 38%  899K 1s
  6850K .......... .......... .......... .......... .......... 38%  405M 1s
  6900K .......... .......... .......... .......... .......... 39%  445M 1s
  6950K .......... .......... .......... .......... .......... 39%  357M 1s
  7000K .......... .......... .......... .......... .......... 39%  241M 1s
  7050K .......... .......... .......... .......... .......... 39%  424M 1s
  7100K .......... .......... .......... .......... .......... 40%  524M 1s
  7150K .......... .......... .......... .......... .......... 40%  432M 1s
  7200K .......... .......... .......... .......... .......... 40%  542M 1s
  7250K .......... .......... .......... .......... .......... 41%  659M 1s
  7300K .......... .......... .......... .......... .......... 41%  609M 1s
  7350K .......... .......... .......... .......... .......... 41%  618M 1s
  7400K .......... .......... .......... .......... .......... 41%  548M 1s
  7450K .......... .......... .......... .......... .......... 42%  541M 1s
  7500K .......... .......... .......... .......... .......... 42%  627M 1s
  7550K .......... .......... .......... .......... .......... 42%  632M 1s
  7600K .......... .......... .......... .......... .......... 43%  530M 1s
  7650K .......... .......... .......... .......... .......... 43%  626M 1s
  7700K .......... .......... .......... .......... .......... 43%  634M 1s
  7750K .......... .......... .......... .......... .......... 43%  595M 1s
  7800K .......... .......... .......... .......... .......... 44%  542M 1s
  7850K .......... .......... .......... .......... .......... 44%  632M 1s
  7900K .......... .......... .......... .......... .......... 44%  562M 1s
  7950K .......... .......... .......... .......... .......... 44%  659M 1s
  8000K .......... .......... .......... .......... .......... 45%  574M 1s
  8050K .......... .......... .......... .......... .......... 45%  585M 1s
  8100K .......... .......... .......... .......... .......... 45%  661M 1s
  8150K .......... .......... .......... .......... .......... 46%  335M 1s
  8200K .......... .......... .......... .......... .......... 46%  275M 1s
  8250K .......... .......... .......... .......... .......... 46%  344M 1s
  8300K .......... .......... .......... .......... .......... 46%  509M 1s
  8350K .......... .......... .......... .......... .......... 47%  461M 1s
  8400K .......... .......... .......... .......... .......... 47%  299M 1s
  8450K .......... .......... .......... .......... .......... 47%  306M 1s
  8500K .......... .......... .......... .......... .......... 48%  413M 1s
  8550K .......... .......... .......... .......... .......... 48%  645M 1s
  8600K .......... .......... .......... .......... .......... 48%  572M 1s
  8650K .......... .......... .......... .......... .......... 48%  656M 1s
  8700K .......... .......... .......... .......... .......... 49%  637M 1s
  8750K .......... .......... .......... .......... .......... 49%  620M 1s
  8800K .......... .......... .......... .......... .......... 49%  581M 1s
  8850K .......... .......... .......... .......... .......... 50% 59.1M 1s
  8900K .......... .......... .......... .......... .......... 50%  178M 1s
  8950K .......... .......... .......... .......... .......... 50%  303M 1s
  9000K .......... .......... .......... .......... .......... 50%  340M 1s
  9050K .......... .......... .......... .......... .......... 51%  333M 1s
  9100K .......... .......... .......... .......... .......... 51%  297M 1s
  9150K .......... .......... .......... .......... .......... 51%  321M 1s
  9200K .......... .......... .......... .......... .......... 52%  554M 1s
  9250K .......... .......... .......... .......... .......... 52%  681M 1s
  9300K .......... .......... .......... .......... .......... 52%  303M 1s
  9350K .......... .......... .......... .......... .......... 52%  235M 1s
  9400K .......... .......... .......... .......... .......... 53%  443M 1s
  9450K .......... .......... .......... .......... .......... 53%  668M 1s
  9500K .......... .......... .......... .......... .......... 53%  883K 1s
  9550K .......... .......... .......... .......... .......... 53%  405M 1s
  9600K .......... .......... .......... .......... .......... 54%  308M 1s
  9650K .......... .......... .......... .......... .......... 54%  378M 1s
  9700K .......... .......... .......... .......... .......... 54%  385M 1s
  9750K .......... .......... .......... .......... .......... 55%  388M 1s
  9800K .......... .......... .......... .......... .......... 55%  322M 1s
  9850K .......... .......... .......... .......... .......... 55%  394M 1s
  9900K .......... .......... .......... .......... .......... 55%  395M 1s
  9950K .......... .......... .......... .......... .......... 56%  319M 1s
 10000K .......... .......... .......... .......... .......... 56%  333M 1s
 10050K .......... .......... .......... .......... .......... 56%  382M 1s
 10100K .......... .......... .......... .......... .......... 57%  397M 1s
 10150K .......... .......... .......... .......... .......... 57%  373M 1s
 10200K .......... .......... .......... .......... .......... 57%  300M 1s
 10250K .......... .......... .......... .......... .......... 57%  366M 1s
 10300K .......... .......... .......... .......... .......... 58%  286M 1s
 10350K .......... .......... .......... .......... .......... 58%  360M 0s
 10400K .......... .......... .......... .......... .......... 58%  306M 0s
 10450K .......... .......... .......... .......... .......... 59%  344M 0s
 10500K .......... .......... .......... .......... .......... 59%  395M 0s
 10550K .......... .......... .......... .......... .......... 59%  370M 0s
 10600K .......... .......... .......... .......... .......... 59%  310M 0s
 10650K .......... .......... .......... .......... .......... 60%  291M 0s
 10700K .......... .......... .......... .......... .......... 60%  393M 0s
 10750K .......... .......... .......... .......... .......... 60%  345M 0s
 10800K .......... .......... .......... .......... .......... 61%  318M 0s
 10850K .......... .......... .......... .......... .......... 61%  349M 0s
 10900K .......... .......... .......... .......... .......... 61%  369M 0s
 10950K .......... .......... .......... .......... .......... 61%  662M 0s
 11000K .......... .......... .......... .......... .......... 62%  596M 0s
 11050K .......... .......... .......... .......... .......... 62%  455M 0s
 11100K .......... .......... .......... .......... .......... 62%  340M 0s
 11150K .......... .......... .......... .......... .......... 62%  347M 0s
 11200K .......... .......... .......... .......... .......... 63%  568M 0s
 11250K .......... .......... .......... .......... .......... 63%  656M 0s
 11300K .......... .......... .......... .......... .......... 63%  692M 0s
 11350K .......... .......... .......... .......... .......... 64%  684M 0s
 11400K .......... .......... .......... .......... .......... 64%  539M 0s
 11450K .......... .......... .......... .......... .......... 64%  685M 0s
 11500K .......... .......... .......... .......... .......... 64%  681M 0s
 11550K .......... .......... .......... .......... .......... 65%  690M 0s
 11600K .......... .......... .......... .......... .......... 65% 36.3M 0s
 11650K .......... .......... .......... .......... .......... 65%  555M 0s
 11700K .......... .......... .......... .......... .......... 66% 47.5M 0s
 11750K .......... .......... .......... .......... .......... 66%  324M 0s
 11800K .......... .......... .......... .......... .......... 66%  272M 0s
 11850K .......... .......... .......... .......... .......... 66%  294M 0s
 11900K .......... .......... .......... .......... .......... 67%  235M 0s
 11950K .......... .......... .......... .......... .......... 67%  308M 0s
 12000K .......... .......... .......... .......... .......... 67%  297M 0s
 12050K .......... .......... .......... .......... .......... 68%  315M 0s
 12100K .......... .......... .......... .......... .......... 68%  207M 0s
 12150K .......... .......... .......... .......... .......... 68%  278M 0s
 12200K .......... .......... .......... .......... .......... 68%  409M 0s
 12250K .......... .......... .......... .......... .......... 69%  421M 0s
 12300K .......... .......... .......... .......... .......... 69%  478M 0s
 12350K .......... .......... .......... .......... .......... 69%  612M 0s
 12400K .......... .......... .......... .......... .......... 69%  433M 0s
 12450K .......... .......... .......... .......... .......... 70%  618M 0s
 12500K .......... .......... .......... .......... .......... 70%  546M 0s
 12550K .......... .......... .......... .......... .......... 70%  614M 0s
 12600K .......... .......... .......... .......... .......... 71%  787K 0s
 12650K .......... .......... .......... .......... .......... 71%  332M 0s
 12700K .......... .......... .......... .......... .......... 71%  597M 0s
 12750K .......... .......... .......... .......... .......... 71%  600M 0s
 12800K .......... .......... .......... .......... .......... 72%  934K 0s
 12850K .......... .......... .......... .......... .......... 72%  444M 0s

In [3]:
%%bash
cd hmmer-3.3.2
./configure
make
make install

configure: Configuring HMMER3 for your system.
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking whether to compile using MPI... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO Standard C... (cached) none needed
checking how to run the C preprocessor... gcc -E
checking for a BSD-compatible install... /usr/bin/install -c
checking for strip... strip
checking for ranlib... ranlib
checking for ar... /usr/bin/ar
checking whether ln -s works... yes
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking whether gcc is Clang... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking whether gcc can compile our Altivec/VMX code... no
checking whether gcc can compile our SSE code... yes
configure: Activating Intel/AMD SSE vector DP implementation
checking whether _MM_SET_FLUSH_ZERO_MODE is supported... yes
checking compiler support --start-group... yes
checking for gzip... /usr/bin/gzip
checking for python3... yes
checking for library containing clock_gettime... none required
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking endian.h usability... yes
checking endian.h presence... yes
checking for endian.h... yes
checking for inttypes.h... (cached) yes
checking for stdint.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/types.h... (cached) yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking for sys/sysctl.h... no
checking for uint8_t... yes
checking for uint16_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for off_t... yes
checking whether byte ordering is bigendian... no
checking for __attribute__((noreturn))... yes
checking for __attribute__((format))... yes
checking for mkstemp... yes
checking for popen... yes
checking for putenv... yes
checking for strcasecmp... yes
checking for strsep... yes
checking for times... yes
checking for getpid... yes
checking for sysctl... no
checking for sysconf... yes
checking for getcwd... yes
checking for chmod... yes
checking for stat... yes
checking for fstat... yes
checking for erfc... no
checking for library containing ntohs... none required
checking for library containing ntohl... none required
checking for library containing htons... none required
checking for library containing htonl... none required
checking for library containing socket... none required
checking for library containing inet_pton... none required
checking for _LARGEFILE_SOURCE value needed for large files... no
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating testsuite/Makefile
config.status: creating profmark/Makefile
config.status: creating src/impl_sse/Makefile
config.status: creating documentation/Makefile
config.status: creating documentation/man/Makefile
config.status: creating documentation/userguide/Makefile
config.status: creating documentation/userguide/inclusions/Makefile
config.status: creating libdivsufsort/Makefile
config.status: creating easel/Makefile
config.status: creating easel/miniapps/Makefile
config.status: creating easel/testsuite/Makefile
config.status: creating easel/documentation/Makefile
config.status: creating documentation/userguide/titlepage.tex
config.status: creating documentation/userguide/titlepage_daemon.tex
config.status: creating documentation/userguide/copyright.tex
config.status: creating documentation/man/alimask.man
config.status: creating documentation/man/hmmalign.man
config.status: creating documentation/man/hmmbuild.man
config.status: creating documentation/man/hmmc2.man
config.status: creating documentation/man/hmmconvert.man
config.status: creating documentation/man/hmmemit.man
config.status: creating documentation/man/hmmer.man
config.status: creating documentation/man/hmmfetch.man
config.status: creating documentation/man/hmmlogo.man
config.status: creating documentation/man/hmmpgmd.man
config.status: creating documentation/man/hmmpgmd_shard.man
config.status: creating documentation/man/hmmpress.man
config.status: creating documentation/man/hmmscan.man
config.status: creating documentation/man/hmmsearch.man
config.status: creating documentation/man/hmmsim.man
config.status: creating documentation/man/hmmstat.man
config.status: creating documentation/man/jackhmmer.man
config.status: creating documentation/man/makehmmerdb.man
config.status: creating documentation/man/nhmmer.man
config.status: creating documentation/man/nhmmscan.man
config.status: creating documentation/man/phmmer.man
config.status: creating easel/miniapps/esl-afetch.man
config.status: creating easel/miniapps/esl-alimanip.man
config.status: creating easel/miniapps/esl-alimap.man
config.status: creating easel/miniapps/esl-alimask.man
config.status: creating easel/miniapps/esl-alimerge.man
config.status: creating easel/miniapps/esl-alipid.man
config.status: creating easel/miniapps/esl-alirev.man
config.status: creating easel/miniapps/esl-alistat.man
config.status: creating easel/miniapps/esl-compalign.man
config.status: creating easel/miniapps/esl-compstruct.man
config.status: creating easel/miniapps/esl-construct.man
config.status: creating easel/miniapps/esl-histplot.man
config.status: creating easel/miniapps/esl-mask.man
config.status: creating easel/miniapps/esl-mixdchlet.man
config.status: creating easel/miniapps/esl-reformat.man
config.status: creating easel/miniapps/esl-selectn.man
config.status: creating easel/miniapps/esl-seqrange.man
config.status: creating easel/miniapps/esl-seqstat.man
config.status: creating easel/miniapps/esl-sfetch.man
config.status: creating easel/miniapps/esl-shuffle.man
config.status: creating easel/miniapps/esl-ssdraw.man
config.status: creating easel/miniapps/esl-translate.man
config.status: creating easel/miniapps/esl-weight.man
config.status: creating easel/decoy_config.h
config.status: creating src/p7_config.h
config.status: creating easel/esl_config.h
config.status: creating libdivsufsort/divsufsort.h
config.status: linking src/impl_sse to src/impl


HMMER configuration:
   compiler:             gcc -O3   -pthread
   host:                 x86_64-pc-linux-gnu
   linker:
   libraries:
   DP implementation:    sse

Now do 'make'  to build HMMER, and optionally:
       'make check'  to run self tests,
       'make install'  to install programs and man pages,
       '(cd easel; make install)'  to install Easel tools.

     SUBDIR easel
     CC easel.o
     CC esl_alloc.o
     CC esl_alphabet.o
     CC esl_arr2.o
     CC esl_arr3.o
     CC esl_bitfield.o
     CC esl_buffer.o
     CC esl_cluster.o
     CC esl_composition.o
     CC esl_cpu.o
     CC esl_dirichlet.o
     CC esl_distance.o
     CC esl_dmatrix.o
     CC esl_dsqdata.o
     CC esl_exponential.o
     CC esl_fileparser.o
     CC esl_gamma.o
     CC esl_gencode.o
     CC esl_getopts.o
     CC esl_gev.o
     CC esl_graph.o
     CC esl_gumbel.o
     CC esl_heap.o
     CC esl_histogram.o
     CC esl_hmm.o
     CC esl_huffman.o
     CC esl_hyperexp.o
     CC esl_json.o
     CC esl_keyhash.o
     CC esl_matrixops.o
     CC esl_mem.o
     CC esl_minimizer.o
     CC esl_mixdchlet.o
     CC esl_mixgev.o
     CC esl_mpi.o
     CC esl_msa.o
     CC esl_msacluster.o
     CC esl_msafile.o
     CC esl_msafile2.o
     CC esl_msafile_a2m.o
     CC esl_msafile_afa.o
     CC esl_msafile_clustal.o
     CC esl_msafile_phylip.o
     CC esl_msafile_psiblast.o
     CC esl_msafile_selex.o
     CC esl_msafile_stockholm.o
     CC esl_msashuffle.o
     CC esl_msaweight.o
     CC esl_normal.o
     CC esl_paml.o
     CC esl_quicksort.o
     CC esl_random.o
     CC esl_rand64.o
     CC esl_randomseq.o
     CC esl_ratematrix.o
     CC esl_recorder.o
     CC esl_red_black.o
     CC esl_regexp.o
     CC esl_rootfinder.o
     CC esl_scorematrix.o
     CC esl_sq.o
     CC esl_sqio.o
     CC esl_sqio_ascii.o
     CC esl_sqio_ncbi.o
     CC esl_ssi.o
     CC esl_stack.o
     CC esl_stats.o
     CC esl_stopwatch.o
     CC esl_stretchexp.o
     CC esl_subcmd.o
     CC esl_threads.o
     CC esl_tree.o
     CC esl_varint.o
     CC esl_vectorops.o
     CC esl_weibull.o
     CC esl_workqueue.o
     CC esl_wuss.o
     CC esl_sse.o
     CC esl_avx.o
     CC esl_avx512.o
     CC esl_neon.o
     CC esl_vmx.o
     AR libeasel.a
     SUBDIR miniapps
     GEN esl-afetch
     GEN esl-alimanip
     GEN esl-alimap
     GEN esl-alimask
     GEN esl-alimerge
     GEN esl-alipid
     GEN esl-alirev
     GEN esl-alistat
     GEN esl-compalign
     GEN esl-compstruct
     GEN esl-construct
     GEN esl-histplot
     GEN esl-mask
     GEN esl-mixdchlet
     GEN esl-reformat
     GEN esl-selectn
     GEN esl-seqrange
     GEN esl-seqstat
     GEN esl-sfetch
     GEN esl-shuffle
     GEN esl-ssdraw
     GEN esl-translate
     GEN esl-weight
     CC cmd_alistat.o
     CC cmd_downsample.o
     CC cmd_filter.o
     CC cmd_index.o
     GEN easel
     SUBDIR libdivsufsort
     CC divsufsort.o
     AR libdivsufsort.a
     SUBDIR src
     CC alimask.o
     CC build.o
     CC cachedb.o
     CC cachedb_shard.o
     CC emit.o
     CC errors.o
     CC evalues.o
     CC eweight.o
     CC generic_decoding.o
     CC generic_fwdback.o
     CC generic_fwdback_chk.o
     CC generic_fwdback_banded.o
     CC generic_null2.o
     CC generic_msv.o
     CC generic_optacc.o
     CC generic_stotrace.o
     CC generic_viterbi.o
     CC generic_vtrace.o
     CC h2_io.o
     CC heatmap.o
     CC hmmlogo.o
     CC hmmdmstr.o
     CC hmmdmstr_shard.o
     CC hmmd_search_status.o
     CC hmmdwrkr.o
     CC hmmdwrkr_shard.o
     CC hmmdutils.o
     CC hmmer.o
     CC logsum.o
     CC modelconfig.o
     CC modelstats.o
     CC mpisupport.o
     CC seqmodel.o
     CC tracealign.o
     CC p7_alidisplay.o
     CC p7_bg.o
     CC p7_builder.o
     CC p7_domain.o
     CC p7_domaindef.o
     CC p7_gbands.o
     CC p7_gmx.o
     CC p7_gmxb.o
     CC p7_gmxchk.o
     CC p7_hit.o
     CC p7_hmm.o
     CC p7_hmmcache.o
     CC p7_hmmd_search_stats.o
     CC p7_hmmfile.o
     CC p7_hmmwindow.o
     CC p7_pipeline.o
     CC p7_prior.o
     CC p7_profile.o
     CC p7_spensemble.o
     CC p7_tophits.o
     CC p7_trace.o
     CC p7_scoredata.o
     CC hmmpgmd2msa.o
     CC fm_alphabet.o
     CC fm_general.o
     CC fm_sse.o
     CC fm_ssv.o
     AR libhmmer-src.stamp
     SUBDIR impl_sse
     CC decoding.o
     CC fwdback.o
     CC io.o
     CC ssvfilter.o
     CC msvfilter.o
     CC null2.o
     CC optacc.o
     CC stotrace.o
     CC vitfilter.o
     CC p7_omx.o
     CC p7_oprofile.o
     CC mpi.o
     AR libhmmer-impl.stamp
     GEN alimask
     CC hmmalign.o
     GEN hmmalign
     CC hmmbuild.o
     GEN hmmbuild
     CC hmmconvert.o
     GEN hmmconvert
     CC hmmemit.o
     GEN hmmemit
     CC hmmfetch.o
     GEN hmmfetch
     GEN hmmlogo
     CC hmmpgmd.o
     GEN hmmpgmd
     CC hmmpgmd_shard.o
     GEN hmmpgmd_shard
     CC hmmpress.o
     GEN hmmpress
     CC hmmscan.o
     GEN hmmscan
     CC hmmsearch.o
     GEN hmmsearch
     CC hmmsim.o
     GEN hmmsim
     CC hmmstat.o
     GEN hmmstat
     CC jackhmmer.o
     GEN jackhmmer
     CC phmmer.o
     GEN phmmer
     CC nhmmer.o
     GEN nhmmer
     CC nhmmscan.o
     GEN nhmmscan
     CC makehmmerdb.o
     GEN makehmmerdb
     CC hmmc2.o
     GEN hmmc2
     CC hmmerfm-exactmatch.o
     GEN hmmerfm-exactmatch
     SUBDIR profmark
     CC create-profmark.o
     GEN create-profmark
     CC rocplot.o
     GEN rocplot
     SUBDIR easel
     SUBDIR miniapps
     SUBDIR libdivsufsort
     SUBDIR src
     SUBDIR impl_sse
     SUBDIR profmark
/usr/bin/install -c -d /usr/local/bin
/usr/bin/install -c -d /usr/local/share/man/man1
make -C src install
make[1]: Entering directory '/content/hmmer-3.3.2/src'
for file in alimask hmmalign hmmbuild hmmconvert hmmemit hmmfetch hmmlogo hmmpgmd hmmpgmd_shard hmmpress hmmscan hmmsearch hmmsim hmmstat jackhmmer phmmer nhmmer nhmmscan makehmmerdb; do \
   /usr/bin/install -c -m 0755 $file /usr/local/bin/ ;\
done
make[1]: Leaving directory '/content/hmmer-3.3.2/src'
make -C documentation install
make[1]: Entering directory '/content/hmmer-3.3.2/documentation'
make -C man install
make[2]: Entering directory '/content/hmmer-3.3.2/documentation/man'
for file in hmmer hmmalign hmmbuild hmmc2 hmmconvert hmmemit hmmfetch hmmlogo hmmpgmd hmmpgmd_shard hmmpress hmmscan hmmsearch hmmsim hmmstat jackhmmer makehmmerdb phmmer nhmmer nhmmscan alimask; do \
   /usr/bin/install -c -m 0664 $file.man /usr/local/share/man/man1/${file}.1 ;\
done
make[2]: Leaving directory '/content/hmmer-3.3.2/documentation/man'
make[1]: Leaving directory '/content/hmmer-3.3.2/documentation'

In file included from hmmbuild.c:13:
In function ‘usual_master’,
    inlined from ‘main’ at hmmbuild.c:463:7:
../easel/easel.h:164:17: warning: argument 1 range [18446744022169944064, 18446744073709551592] exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
  164 |     if ( ((p) = malloc(size)) == NULL)  { \
      |                 ^~~~~~~~~~~~
hmmbuild.c:561:3: note: in expansion of macro ‘ESL_ALLOC’
  561 |   ESL_ALLOC(info, sizeof(*info) * infocnt);
      |   ^~~~~~~~~
In file included from hmmbuild.c:6:
hmmbuild.c: In function ‘main’:
/usr/include/stdlib.h:540:14: note: in a call to allocation function ‘malloc’ declared here
  540 | extern void *malloc (size_t __size) __THROW __attribute_malloc__
      |              ^~~~~~
In file included from hmmscan.c:14:
In function ‘serial_master’,
    inlined from ‘main’ at hmmscan.c:302:16:
../easel/easel.h:164:17: warning: argument 1 range [18446743987810205696, 18446744073709551576] exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
  164 |     if ( ((p) = malloc(size)) == NULL)  { \
      |                 ^~~~~~~~~~~~
hmmscan.c:402:3: note: in expansion of macro ‘ESL_ALLOC’
  402 |   ESL_ALLOC(info, sizeof(*info) * infocnt);
      |   ^~~~~~~~~
In file included from hmmscan.c:11:
hmmscan.c: In function ‘main’:
/usr/include/stdlib.h:540:14: note: in a call to allocation function ‘malloc’ declared here
  540 | extern void *malloc (size_t __size) __THROW __attribute_malloc__
      |              ^~~~~~

In [4]:
!wget http://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam35.0/Pfam-A.hmm.gz # Скачивание Pfam

--2026-06-10 16:49:03--  http://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam35.0/Pfam-A.hmm.gz
Resolving ftp.ebi.ac.uk (ftp.ebi.ac.uk)... 193.62.193.165
Connecting to ftp.ebi.ac.uk (ftp.ebi.ac.uk)|193.62.193.165|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 293000230 (279M) [application/x-gzip]
Saving to: ‘Pfam-A.hmm.gz’

Pfam-A.hmm.gz       100%[===================>] 279.43M  1.81MB/s    in 3m 46s

2026-06-10 16:52:49 (1.24 MB/s) - ‘Pfam-A.hmm.gz’ saved [293000230/293000230]

In [5]:
!gunzip Pfam-A.hmm.gz # Извлечение из архива

In [6]:
!hmmpress Pfam-A.hmm # Индексация

Working...    done.
Pressed and indexed 19632 HMMs (19632 names and 19632 accessions).
Models pressed into binary file:   Pfam-A.hmm.h3m
SSI index for binary model file:   Pfam-A.hmm.h3i
Profiles (MSV part) pressed into:  Pfam-A.hmm.h3f
Profiles (remainder) pressed into: Pfam-A.hmm.h3p

## Загрузка файлов с диска

In [7]:
!gdown "https://drive.google.com/uc?id=1rUtdUO7r4gIvlZno1oYLMTrnMkng5S7G"
!gdown "https://drive.google.com/uc?id=1-INJ8Q7wN_pGAXiVlhUUxMWq5bRotXds"
!gdown "https://drive.google.com/uc?id=1JaNkBcGJH6YqXha81HUgb3I1J7tuZcwY"

Downloading...
From: https://drive.google.com/uc?id=1rUtdUO7r4gIvlZno1oYLMTrnMkng5S7G
To: /content/protein.faa
100% 17.3M/17.3M [00:00<00:00, 106MB/s]
Downloading...
From (original): https://drive.google.com/uc?id=1-INJ8Q7wN_pGAXiVlhUUxMWq5bRotXds
From (redirected): https://drive.google.com/uc?id=1-INJ8Q7wN_pGAXiVlhUUxMWq5bRotXds&confirm=t&uuid=da970c7a-942b-444b-ac40-a857380b2302
To: /content/genomic.gff
100% 117M/117M [00:00<00:00, 170MB/s]
Downloading...
From: https://drive.google.com/uc?id=1JaNkBcGJH6YqXha81HUgb3I1J7tuZcwY
To: /content/For project - selected.csv
100% 172k/172k [00:00<00:00, 125MB/s]

## Извлечение Pfam ID из таблицы

In [ ]:
import csv
import re

# Список для хранения выбранных семейств
families = []

epigenetics = ["Chromatin remodeling cofactor", "Chromatin remodeling", "Histone modification read",
"Histone modification write cofactor", "Histone modification read", "Histone modification", "Histone chaperone"]

with open('For project - selected.csv', 'r', encoding='utf-8') as f:
    reader = csv.DictReader(f)  # читаем как словарь

    for row in reader:
        if row['Modification'] == '#' or row['Function'] not in epigenetics:
            continue

        symbol = row['HGNC approved symbol']  # Берём название семейства
        if symbol == 'AEBP2': # неспецифичен, даёт 1900+ хитов
                      continue
        pfam_str = row['Pfam domains'] # Берём строку с Pfam доменами
        pfam_ids = re.findall(r'PF\d{5}', pfam_str) # Ищем все PFxxxxx

        # Если нашлись Pfam домены, добавляем семейство в список
        if pfam_ids:
            families.append({
                'family': symbol,
                'pfam_domains': ', '.join(pfam_ids),
                'function': row['Function'],
                'modification': row['Modification']
            })

        # выход, если набрали 10 семейств
        if len(families) == 10:
            break

print("10 семейств: ")
for i, f in enumerate(families, 1):
    print(f"{i}. {f['family']}")
    print(f"   Pfam: {f['pfam_domains']}")
    print(f"   Function: {f['function']}")
    print(f"   Modification: {f['modification']}")
    print()

# все Pfam ID из всех семейств в один список
all_pfam_ids = []
for f in families:    all_pfam_ids.extend(f['pfam_domains'].split(', '))

# удаление дубликатов
unique_pfam_ids = list(dict.fromkeys(all_pfam_ids))

print(f"Уникальных Pfam доменов для поиска: {len(unique_pfam_ids)}")
print(unique_pfam_ids)

10 семейств:
1. ARID4A
   Pfam: PF01388, PF08169, PF11717
   Function: Histone modification write cofactor
   Modification: Histone acetylation

2. ARID4B
   Pfam: PF01388, PF08169, PF11717
   Function: Histone modification write cofactor
   Modification: Histone acetylation

3. ASH2L
   Pfam: PF00622
   Function: Histone modification write cofactor
   Modification: Histone methylation

4. ATXN7
   Pfam: PF08313
   Function: Histone modification write cofactor
   Modification: Histone acetylation

5. BRE
   Pfam: PF06113
   Function: Histone modification write cofactor
   Modification: Histone ubiquitination

6. BRPF3
   Pfam: PF00439, PF10513, PF13831, PF00855, PF13832
   Function: Histone modification write cofactor
   Modification: Histone acetylation

7. C11orf30
   Pfam: PF03735
   Function: Histone modification write cofactor
   Modification: Histone methylation

8. CDC73
   Pfam: PF05179
   Function: Histone modification write cofactor
   Modification: Histone methylation

9. CLNS1A
   Pfam: PF03517
   Function: Histone modification write cofactor
   Modification: Histone methylation

10. CTBP2
   Pfam: PF00389, PF02826
   Function: Histone modification write cofactor
   Modification: Histone methylation

Уникальных Pfam доменов для поиска: 16
['PF01388', 'PF08169', 'PF11717', 'PF00622', 'PF08313', 'PF06113', 'PF00439', 'PF10513', 'PF13831', 'PF00855', 'PF13832', 'PF03735', 'PF05179', 'PF03517', 'PF00389', 'PF02826']

## Hmmer

In [8]:
!pip install pyhmmer pandas

Collecting pyhmmer
  Downloading pyhmmer-0.12.1-cp312-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (14 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: psutil<8.0,>=5.0 in /usr/local/lib/python3.12/dist-packages (from pyhmmer) (5.9.5)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pyhmmer-0.12.1-cp312-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (4.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 61.5 MB/s eta 0:00:00
Installing collected packages: pyhmmer
Successfully installed pyhmmer-0.12.1

In [ ]:
from pyhmmer import hmmscan, easel, plan7
import pandas as pd

pfam_list = unique_pfam_ids

# загрузка базы Pfam
with plan7.HMMFile("Pfam-A.hmm") as hmm_file:
    all_hmm = list(hmm_file)

hmm_needed = []
for hmm in all_hmm:
    acc = hmm.accession
    acc_clean = acc.split('.')[0]  # PF10417.12 в PF10417
    if acc_clean in pfam_list:
        hmm_needed.append(hmm)

print(f"Найдено {len(hmm_needed)} HMM из {len(pfam_list)}")

# загрузка протеома осьминога
with easel.SequenceFile("protein.faa", digital=True) as sf:
    sequences = list(sf)

print(f"Загружено {len(sequences)} белков")

results = hmmscan(sequences, hmm_needed, cpus=2)
hits = []
for top_hits in results:
    protein = top_hits.query.name
    for hit in top_hits:
        for domain in hit.domains:
            # Берём Accession и отрезаем версию
            acc_full = domain.alignment.hmm_accession
            if isinstance(acc_full, bytes):
                acc_full = acc_full.decode()
            pfam_id = acc_full.split('.')[0]   # PFxxxxx
            hits.append({
                'pfam_domain': pfam_id,
                'protein_id': protein,
                'score': round(domain.score, 2),
                'evalue': f'{domain.c_evalue:.2e}'
            })

df = pd.DataFrame(hits).drop_duplicates()
df = df[(df['evalue'].astype(float) < 1e-10) & (df['score'] > 25)]
df.to_csv('results.csv', index=False)

print(f"Найдено {len(df)} совпадений")
print(df.head())

Найдено 16 HMM из 16
Загружено 30134 белков
Найдено 243 совпадений
   pfam_domain    protein_id   score    evalue
1      PF01388  CAI9714888.1   53.16  2.13e-18
3      PF01388  CAI9714889.1   53.47  1.69e-18
16     PF13832  CAI9715056.1  126.62  1.19e-40
17     PF10513  CAI9715056.1   95.61  1.26e-30
21     PF00439  CAI9715056.1   85.24  6.58e-28

In [ ]:
print(families)

[{'family': 'ARID4A', 'pfam_domains': 'PF01388, PF08169, PF11717', 'function': 'Histone modification write cofactor', 'modification': 'Histone acetylation'}, {'family': 'ARID4B', 'pfam_domains': 'PF01388, PF08169, PF11717', 'function': 'Histone modification write cofactor', 'modification': 'Histone acetylation'}, {'family': 'ASH2L', 'pfam_domains': 'PF00622', 'function': 'Histone modification write cofactor', 'modification': 'Histone methylation'}, {'family': 'ATXN7', 'pfam_domains': 'PF08313', 'function': 'Histone modification write cofactor', 'modification': 'Histone acetylation'}, {'family': 'BRE', 'pfam_domains': 'PF06113', 'function': 'Histone modification write cofactor', 'modification': 'Histone ubiquitination'}, {'family': 'BRPF3', 'pfam_domains': 'PF00439, PF10513, PF13831, PF00855, PF13832', 'function': 'Histone modification write cofactor', 'modification': 'Histone acetylation'}, {'family': 'C11orf30', 'pfam_domains': 'PF03735', 'function': 'Histone modification write cofactor', 'modification': 'Histone methylation'}, {'family': 'CDC73', 'pfam_domains': 'PF05179', 'function': 'Histone modification write cofactor', 'modification': 'Histone methylation'}, {'family': 'CLNS1A', 'pfam_domains': 'PF03517', 'function': 'Histone modification write cofactor', 'modification': 'Histone methylation'}, {'family': 'CTBP2', 'pfam_domains': 'PF00389, PF02826', 'function': 'Histone modification write cofactor', 'modification': 'Histone methylation'}]

In [ ]:
results = []
for f in families:
    family_name = f['family']
    required_domains = set(f['pfam_domains'].split(', '))

    family_proteins = df[df['pfam_domain'].isin(required_domains)]['protein_id'].unique()

    for protein in family_proteins:
        results.append({
            'Семейство': family_name,
            'Ген': protein
        })

result_df = pd.DataFrame(results).drop_duplicates()

In [ ]:
result_df

    Семейство           Ген
0      ARID4A  CAI9714888.1
1      ARID4A  CAI9714889.1
2      ARID4A  CAI9718675.1
3      ARID4A  CAI9718676.1
4      ARID4A  CAI9719588.1
..        ...           ...
196     CTBP2  CAI9737388.1
197     CTBP2  CAI9737389.1
198     CTBP2  CAI9737674.1
199     CTBP2  CAI9737675.1
200     CTBP2  CAI9737676.1

[201 rows x 2 columns]

In [ ]:
result_df.to_csv('epigenetics_results.csv', index=False, encoding='utf-8')

# ZDNABERT

Был посчитан здесь: https://bioinformatics.ibp.cz/#/analyse/zdna

In [ ]:
import pandas as pd
import os

In [ ]:
# Соответствие номера хромосомы и GenBank
chrom_to_seqid = {
    '1': 'OX597814.1',
    '2': 'OX597815.1',
    '3': 'OX597816.1',
    '4': 'OX597817.1',
    '5': 'OX597818.1',
    '6': 'OX597819.1',
    '7': 'OX597820.1',
    '8': 'OX597821.1',
    '9': 'OX597822.1',
    '10': 'OX597823.1',
    '11': 'OX597824.1',
    '12': 'OX597825.1',
    '13': 'OX597826.1',
    '14': 'OX597827.1',
    '15': 'OX597828.1',
    '16': 'OX597829.1',
    '17': 'OX597830.1',
    '18': 'OX597831.1',
    '19': 'OX597832.1',
    '20': 'OX597833.1',
    '21': 'OX597834.1',
    '22': 'OX597835.1',
    '23': 'OX597836.1',
    '24': 'OX597837.1',
    '25': 'OX597838.1',
    '26': 'OX597839.1',
    '27': 'OX597840.1',
    '28': 'OX597841.1',
    '29': 'OX597842.1',
    '30': 'OX597843.1',
    'MT': 'OY720585.1'
}

In [ ]:
import os
import pandas as pd

files = [f for f in os.listdir('.') if f.startswith('chr') or f == 'MT.csv']

zdnabert_list = []
for f in files:
    # Извлекаем номер хромосомы из имени файла
    chrom_num = f.replace('chr', '').replace('.csv', '')
    seqid = chrom_to_seqid.get(chrom_num)
    if seqid is None:
        print(f"Предупреждение: нет соответствия для {chrom_num}, пропускаем {f}")
        continue

    df = pd.read_csv(f, sep='\t')
    df['seqid'] = seqid          # добавляем колонку с именем хромосомы
    zdnabert_list.append(df)

zdnabert = pd.concat(zdnabert_list, ignore_index=True)
zdnabert.to_csv('zdnabert_all.csv', index=False)
print(f"ZHUNT загружен: {len(zdnabert)}")

/tmp/ipykernel_8392/3877955805.py:19: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  zdnabert = pd.concat(zdnabert_list, ignore_index=True)

ZHUNT загружен: 212403

In [ ]:
zdnabert.head()

,ID,POSITION,LENGTH,SEQUENCE,ZDNAGCRICHNESS,ZDNAGTRICHNESS,CONFIDENCESCORE,PREDICTIONVARIANT,seqid
0,1,62812,20,CCCGGTGCGCGCAATCGCGC,52.631579,10.526316,0.862461,normal,OX597834.1
1,2,63031,17,GCGCGGATGCGCGCACT,56.250000,6.250000,0.894387,normal,OX597834.1
2,3,352387,16,ACATGCACACACACAC,6.666667,6.666667,0.555502,normal,OX597834.1
3,4,370449,27,TGCATGTGCGTGCGCGCGCGCGCGTGT,57.692308,34.615385,0.700848,normal,OX597834.1
4,5,481790,10,GTGTGTGTGT,0.000000,100.000000,0.608522,normal,OX597834.1

# Zhunt

Был посчитан здесь: https://bioinformatics.ibp.cz/#/analyse/zdna

Удалила старые файлы, загружаю новые и собираю в один

In [ ]:
files = [f for f in os.listdir('.') if f.startswith('chr') or f == 'MT.csv']

zhunt_list = []
for f in files:
    # Извлекаем номер хромосомы из имени файла
    chrom_num = f.replace('chr', '').replace('.csv', '')
    seqid = chrom_to_seqid.get(chrom_num)
    if seqid is None:
        print(f"Предупреждение: нет соответствия для {chrom_num}, пропускаем {f}")
        continue

    df = pd.read_csv(f, sep='\t')
    df['seqid'] = seqid          # добавляем колонку с именем хромосомы
    zhunt_list.append(df)

zhunt = pd.concat(zhunt_list, ignore_index=True)
print(f"ZHUNT загружен: {len(zhunt)}")

ZHUNT загружен: 1950858

/tmp/ipykernel_8392/4226961780.py:16: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  zhunt = pd.concat(zhunt_list, ignore_index=True)

In [ ]:
zhunt.head()

,ID,POSITION,LENGTH,SEQUENCE,ZDNAGCRICHNESS,ZDNAGTRICHNESS,SCORE,SCOREPERC,seqid
0,1,7778,13,ACACACACACACA,0.000000,0.000000,18.0,12.000000,OX597834.1
1,2,8957,21,ACACACACACACACACACACA,0.000000,0.000000,30.0,12.000000,OX597834.1
2,3,17337,14,TGCACACACACGCA,23.076923,7.692308,52.5,32.307693,OX597834.1
3,4,22928,15,ACACACACACACACA,0.000000,0.000000,21.0,12.000000,OX597834.1
4,5,22945,51,TGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTG...,0.000000,100.000000,75.0,12.000000,OX597834.1

In [ ]:
# фильтрация по z-score
zhunt = zhunt[zhunt["SCORE"] > 400 ]

In [ ]:
zhunt.head()

,ID,POSITION,LENGTH,SEQUENCE,ZDNAGCRICHNESS,ZDNAGTRICHNESS,SCORE,SCOREPERC,seqid
347,348,546710,115,ACGCACGCACGCACGCACGCACGCACGCACGCACGCACGCACGCAC...,29.824561,0.000000,545.0,38.245617,OX597834.1
364,365,562544,211,CACACACACACACACACGCACACACACACACACACACACACACACA...,7.619048,0.000000,491.0,18.704762,OX597834.1
397,398,574059,150,TGTGTGTGTGTGTGTGTGCGCGCGCGCGCGCGCGTGTGTGTGCGTG...,13.422819,86.577181,443.5,23.812080,OX597834.1
1229,1230,1575297,162,ACGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGCGTGTGCGTGTGT...,10.559006,88.819876,428.5,21.291925,OX597834.1
2552,2553,2731753,371,CACACACACACACACACACACACACACACACACACACACACACACA...,1.081081,0.000000,599.0,12.951352,OX597834.1

In [ ]:
zhunt.to_csv('zhunt_all.csv', index=False)

# Поиск квадруплексов

In [ ]:
# файл с геномом
!gdown 1z2AoDSU8bjCoxy1efD8qScGzXwk4xmy7

Downloading...
From (original): https://drive.google.com/uc?id=1z2AoDSU8bjCoxy1efD8qScGzXwk4xmy7
From (redirected): https://drive.google.com/uc?id=1z2AoDSU8bjCoxy1efD8qScGzXwk4xmy7&confirm=t&uuid=1f5ad9bd-7c57-4bff-9056-888b0b639ea3
To: /content/GCA_951406725.2_xcOctVulg1.2_genomic.fna
100% 2.84G/2.84G [00:55<00:00, 50.8MB/s]

In [ ]:
!pip install biopython

Collecting biopython
  Downloading biopython-1.87-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from biopython) (2.0.2)
Downloading biopython-1.87-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 102.9 MB/s eta 0:00:00
Installing collected packages: biopython
Successfully installed biopython-1.87

In [ ]:
import re
from Bio import SeqIO
import pandas as pd

# Файлы
input_fasta = "/content/GCA_951406725.2_xcOctVulg1.2_genomic.fna"
output_csv = "g4_quadruplexes.csv"

# Паттерн для G4
pattern = re.compile(r"(G{3,5}[ATGC]{1,7}){3,}G{3,5}", re.IGNORECASE)

# Функция реверс-комплемента
def revcomp(seq):
    return seq[::-1].translate(str.maketrans("ATGC", "TACG"))

hits = []

for record in SeqIO.parse(input_fasta, "fasta"):
    chrom = record.id
    seq = str(record.seq).upper()
    rev = revcomp(seq)
    print(f"Ищу в {chrom}...")

    # + стренд
    for m in pattern.finditer(seq):
        hits.append([chrom, m.start(), m.end(), '+', m.group()])

    # - стренд
    for m in pattern.finditer(rev):
        start = len(seq) - m.end()
        end = len(seq) - m.start()
        hits.append([chrom, start, end, '-', m.group()])

df = pd.DataFrame(hits, columns=['chrom', 'start', 'end', 'strand', 'seq'])
df.to_csv(output_csv, index=False)

print(f"Найдено {len(df)} G4. Результат в {output_csv}")

Ищу в OX597814.1...
Ищу в OX597815.1...
Ищу в OX597816.1...
Ищу в OX597817.1...
Ищу в OX597818.1...
Ищу в OX597819.1...
Ищу в OX597820.1...
Ищу в OX597821.1...
Ищу в OX597822.1...
Ищу в OX597823.1...
Ищу в OX597824.1...
Ищу в OX597825.1...
Ищу в OX597826.1...
Ищу в OX597827.1...
Ищу в OX597828.1...
Ищу в OX597829.1...
Ищу в OX597830.1...
Ищу в OX597831.1...
Ищу в OX597832.1...
Ищу в OX597833.1...
Ищу в OX597834.1...
Ищу в OX597835.1...
Ищу в OX597836.1...
Ищу в OX597837.1...
Ищу в OX597838.1...
Ищу в OX597839.1...
Ищу в OX597840.1...
Ищу в OX597841.1...
Ищу в OX597842.1...
Ищу в OX597843.1...
Ищу в CATOCA020000001.1...
Ищу в CATOCA020000002.1...
Ищу в CATOCA020000003.1...
Ищу в CATOCA020000004.1...
Ищу в CATOCA020000005.1...
Ищу в CATOCA020000006.1...
Ищу в CATOCA020000007.1...
Ищу в CATOCA020000008.1...
Ищу в CATOCA020000009.1...
Ищу в CATOCA020000010.1...
Ищу в CATOCA020000011.1...
Ищу в CATOCA020000012.1...
Ищу в CATOCA020000013.1...
Ищу в CATOCA020000014.1...
Ищу в CATOCA020000015.1...
Ищу в CATOCA020000016.1...
Ищу в CATOCA020000017.1...
Ищу в CATOCA020000018.1...
Ищу в CATOCA020000019.1...
Ищу в CATOCA020000020.1...
Ищу в CATOCA020000021.1...
Ищу в CATOCA020000022.1...
Ищу в CATOCA020000023.1...
Ищу в CATOCA020000024.1...
Ищу в CATOCA020000025.1...
Ищу в CATOCA020000026.1...
Ищу в CATOCA020000027.1...
Ищу в CATOCA020000028.1...
Ищу в CATOCA020000029.1...
Ищу в CATOCA020000030.1...
Ищу в CATOCA020000031.1...
Ищу в CATOCA020000032.1...
Ищу в CATOCA020000033.1...
Ищу в CATOCA020000034.1...
Ищу в CATOCA020000035.1...
Ищу в CATOCA020000036.1...
Ищу в CATOCA020000037.1...
Ищу в CATOCA020000038.1...
Ищу в CATOCA020000039.1...
Ищу в CATOCA020000040.1...
Ищу в CATOCA020000041.1...
Ищу в CATOCA020000042.1...
Ищу в CATOCA020000043.1...
Ищу в CATOCA020000044.1...
Ищу в CATOCA020000045.1...
Ищу в CATOCA020000046.1...
Ищу в CATOCA020000047.1...
Ищу в CATOCA020000048.1...
Ищу в CATOCA020000049.1...
Ищу в CATOCA020000050.1...
Ищу в CATOCA020000051.1...
Ищу в CATOCA020000052.1...
Ищу в CATOCA020000053.1...
Ищу в CATOCA020000054.1...
Ищу в CATOCA020000055.1...
Ищу в CATOCA020000056.1...
Ищу в CATOCA020000057.1...
Ищу в CATOCA020000058.1...
Ищу в CATOCA020000059.1...
Ищу в CATOCA020000060.1...
Ищу в CATOCA020000061.1...
Ищу в CATOCA020000062.1...
Ищу в CATOCA020000063.1...
Ищу в CATOCA020000064.1...
Ищу в CATOCA020000065.1...
Ищу в CATOCA020000066.1...
Ищу в CATOCA020000067.1...
Ищу в CATOCA020000068.1...
Ищу в CATOCA020000069.1...
Ищу в CATOCA020000070.1...
Ищу в CATOCA020000071.1...
Ищу в CATOCA020000072.1...
Ищу в CATOCA020000073.1...
Ищу в CATOCA020000074.1...
Ищу в CATOCA020000075.1...
Ищу в CATOCA020000076.1...
Ищу в CATOCA020000077.1...
Ищу в CATOCA020000078.1...
Ищу в CATOCA020000079.1...
Ищу в CATOCA020000080.1...
Ищу в CATOCA020000081.1...
Ищу в CATOCA020000082.1...
Ищу в CATOCA020000083.1...
Ищу в CATOCA020000084.1...
Ищу в CATOCA020000085.1...
Ищу в CATOCA020000086.1...
Ищу в CATOCA020000087.1...
Ищу в CATOCA020000088.1...
Ищу в CATOCA020000089.1...
Ищу в CATOCA020000090.1...
Ищу в CATOCA020000091.1...
Ищу в CATOCA020000092.1...
Ищу в CATOCA020000093.1...
Ищу в CATOCA020000094.1...
Ищу в CATOCA020000095.1...
Ищу в CATOCA020000096.1...
Ищу в CATOCA020000097.1...
Ищу в CATOCA020000098.1...
Ищу в CATOCA020000099.1...
Ищу в CATOCA020000100.1...
Ищу в CATOCA020000101.1...
Ищу в CATOCA020000102.1...
Ищу в CATOCA020000103.1...
Ищу в CATOCA020000104.1...
Ищу в CATOCA020000105.1...
Ищу в CATOCA020000106.1...
Ищу в CATOCA020000107.1...
Ищу в CATOCA020000108.1...
Ищу в CATOCA020000109.1...
Ищу в CATOCA020000110.1...
Ищу в CATOCA020000111.1...
Ищу в CATOCA020000112.1...
Ищу в CATOCA020000113.1...
Ищу в CATOCA020000114.1...
Ищу в CATOCA020000115.1...
Ищу в CATOCA020000116.1...
Ищу в CATOCA020000117.1...
Ищу в CATOCA020000118.1...
Ищу в CATOCA020000119.1...
Ищу в CATOCA020000120.1...
Ищу в CATOCA020000121.1...
Ищу в CATOCA020000122.1...
Ищу в CATOCA020000123.1...
Ищу в CATOCA020000124.1...
Ищу в CATOCA020000125.1...
Ищу в CATOCA020000126.1...
Ищу в CATOCA020000127.1...
Ищу в CATOCA020000128.1...
Ищу в CATOCA020000129.1...
Ищу в CATOCA020000130.1...
Ищу в CATOCA020000131.1...
Ищу в CATOCA020000132.1...
Ищу в CATOCA020000133.1...
Ищу в CATOCA020000134.1...
Ищу в CATOCA020000135.1...
Ищу в CATOCA020000136.1...
Ищу в CATOCA020000137.1...
Ищу в CATOCA020000138.1...
Ищу в CATOCA020000139.1...
Ищу в CATOCA020000140.1...
Ищу в CATOCA020000141.1...
Ищу в CATOCA020000142.1...
Ищу в CATOCA020000143.1...
Ищу в CATOCA020000144.1...
Ищу в CATOCA020000145.1...
Ищу в CATOCA020000146.1...
Ищу в CATOCA020000147.1...
Ищу в CATOCA020000148.1...
Ищу в CATOCA020000149.1...
Ищу в CATOCA020000150.1...
Ищу в CATOCA020000151.1...
Ищу в CATOCA020000152.1...
Ищу в CATOCA020000153.1...
Ищу в CATOCA020000154.1...
Ищу в CATOCA020000155.1...
Ищу в CATOCA020000156.1...
Ищу в CATOCA020000157.1...
Ищу в CATOCA020000158.1...
Ищу в CATOCA020000159.1...
Ищу в CATOCA020000160.1...
Ищу в CATOCA020000161.1...
Ищу в CATOCA020000162.1...
Ищу в CATOCA020000163.1...
Ищу в CATOCA020000164.1...
Ищу в CATOCA020000165.1...
Ищу в CATOCA020000166.1...
Ищу в CATOCA020000167.1...
Ищу в CATOCA020000168.1...
Ищу в CATOCA020000169.1...
Ищу в CATOCA020000170.1...
Ищу в CATOCA020000171.1...
Ищу в CATOCA020000172.1...
Ищу в CATOCA020000173.1...
Ищу в CATOCA020000174.1...
Ищу в CATOCA020000175.1...
Ищу в CATOCA020000176.1...
Ищу в CATOCA020000177.1...
Ищу в CATOCA020000178.1...
Ищу в CATOCA020000179.1...
Ищу в CATOCA020000180.1...
Ищу в CATOCA020000181.1...
Ищу в CATOCA020000182.1...
Ищу в CATOCA020000183.1...
Ищу в CATOCA020000184.1...
Ищу в CATOCA020000185.1...
Ищу в CATOCA020000186.1...
Ищу в CATOCA020000187.1...
Ищу в CATOCA020000188.1...
Ищу в CATOCA020000189.1...
Ищу в CATOCA020000190.1...
Ищу в CATOCA020000191.1...
Ищу в CATOCA020000192.1...
Ищу в CATOCA020000193.1...
Ищу в CATOCA020000194.1...
Ищу в CATOCA020000195.1...
Ищу в CATOCA020000196.1...
Ищу в OY720585.1...
Найдено 83930 G4. Результат в g4_quadruplexes.csv

# Таблицы с результатами

In [25]:
import pandas as pd

g4 = pd.read_csv("/content/g4_quadruplexes.csv")
zdnabert = pd.read_csv("/content/zdnabert_all.csv")
zhunt = pd.read_csv("/content/zhunt_all.csv")

In [26]:
# аннотация генома
! gdown 1-INJ8Q7wN_pGAXiVlhUUxMWq5bRotXds

Downloading...
From (original): https://drive.google.com/uc?id=1-INJ8Q7wN_pGAXiVlhUUxMWq5bRotXds
From (redirected): https://drive.google.com/uc?id=1-INJ8Q7wN_pGAXiVlhUUxMWq5bRotXds&confirm=t&uuid=4ea6c040-df4d-4856-931b-6c515cdd1ccf
To: /content/genomic.gff
100% 117M/117M [00:00<00:00, 200MB/s]

In [27]:
column_names = [
    'seqid',
    'source',
    'type',
    'start',
    'end',
    'score',
    'strand',
    'phase',
    'attributes'
]

annotations_df = pd.read_csv(
    "/content/genomic.gff",
    sep='\t',
    comment='#',
    header=None,
    names=column_names,
    low_memory=False
)

print(annotations_df.head())

        seqid source    type   start        end score strand phase  \
0  OX597814.1   EMBL  region       1  225692979     .      +     .
1  OX597814.1   EMBL    gene  166925     259180     .      -     .
2  OX597814.1   EMBL     CDS  259167     259180     .      -     0
3  OX597814.1   EMBL     CDS  252344     252397     .      -     1
4  OX597814.1   EMBL     CDS  240692     240778     .      -     1

                                          attributes
0  ID=OX597814.1:1..225692979;Dbxref=taxon:6645;N...
1  ID=gene-OCTVUL_1B012403;Name=OCTVUL_1B012403;g...
2  ID=cds-CAI9714688.1;Parent=gene-OCTVUL_1B01240...
3  ID=cds-CAI9714688.1;Parent=gene-OCTVUL_1B01240...
4  ID=cds-CAI9714688.1;Parent=gene-OCTVUL_1B01240...

In [28]:
annotations_df.head()

,seqid,source,type,start,end,score,strand,phase,attributes
0,OX597814.1,EMBL,region,1,225692979,.,+,.,ID=OX597814.1:1..225692979;Dbxref=taxon:6645;N...
1,OX597814.1,EMBL,gene,166925,259180,.,-,.,ID=gene-OCTVUL_1B012403;Name=OCTVUL_1B012403;g...
2,OX597814.1,EMBL,CDS,259167,259180,.,-,0,ID=cds-CAI9714688.1;Parent=gene-OCTVUL_1B01240...
3,OX597814.1,EMBL,CDS,252344,252397,.,-,1,ID=cds-CAI9714688.1;Parent=gene-OCTVUL_1B01240...
4,OX597814.1,EMBL,CDS,240692,240778,.,-,1,ID=cds-CAI9714688.1;Parent=gene-OCTVUL_1B01240...

In [29]:
annotations_df['type'].unique()

array(['region', 'gene', 'CDS', 'mRNA', 'exon', 'lnc_RNA'], dtype=object)

In [30]:
!pip install intervaltree

Collecting intervaltree
  Downloading intervaltree-3.2.1-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.12/dist-packages (from intervaltree) (2.4.0)
Downloading intervaltree-3.2.1-py2.py3-none-any.whl (25 kB)
Installing collected packages: intervaltree
Successfully installed intervaltree-3.2.1

In [31]:
import pandas as pd
import numpy as np
from intervaltree import IntervalTree
from collections import defaultdict

In [32]:
# Для g4 (квадруплексы) – start и end уже есть, сделаем end полуоткрытым
g4['start_half'] = g4['start']
g4['end_half'] = g4['end'] + 1

# Для zdnabert – добавим start и end (включительные)
zdnabert['start_half'] = zdnabert['POSITION']
zdnabert['end_half'] = zdnabert['POSITION'] + zdnabert['LENGTH'] + 1

# Для zhunt – аналогично
zhunt['start_half'] = zhunt['POSITION']
zhunt['end_half'] = zhunt['POSITION'] + zhunt['LENGTH'] + 1

# Для аннотации – start и end уже есть, переведём в полуоткрытые
annotations_df['start_half'] = annotations_df['start']
annotations_df['end_half'] = annotations_df['end'] + 1

In [33]:
# Возвращает долю пересечения feature с region: (0,1)
def overlap_ratio(region_start, region_end, feat_start, feat_end):
    inter_start = max(region_start, feat_start)
    inter_end = min(region_end, feat_end)
    if inter_start >= inter_end:
        return 0.0
    inter_len = inter_end - inter_start
    feat_len = feat_end - feat_start
    return inter_len / feat_len

In [34]:
# Построение интервальных деревьев
# Принимает DataFrame с предсказаниями. Возвращает словарь: {seqid: IntervalTree}, где каждый интервал хранит индекс строки
def build_interval_trees(df, seqid_col='seqid', start_col='start_half', end_col='end_half'):
    trees = defaultdict(IntervalTree)
    for idx, row in df.iterrows():
        seqid = row[seqid_col]
        # Используем полуоткрытые интервалы [start, end)
        trees[seqid].addi(row[start_col], row[end_col], idx)
    return trees

# Построим деревья для всех трёх наборов
g4_trees = build_interval_trees(g4, seqid_col='chrom')
zhun_trees = build_interval_trees(zhunt, seqid_col='seqid')
zdnabert_trees = build_interval_trees(zdnabert, seqid_col='seqid')

In [35]:
# Создание датафрейма с регионами
regions_list = []

# Вспомогательная функция для обрезки отрицательных координат
def clip_negative(start, end):
    return max(start, 0), end

# Экзоны
exons = annotations_df[annotations_df['type'] == 'exon'][['seqid', 'start_half', 'end_half']].copy()
for _, row in exons.iterrows():
    regions_list.append([row['seqid'], row['start_half'], row['end_half'], 'Exons'])

# Гены (нужны для промоторов, downstream, интронов)
genes = annotations_df[annotations_df['type'] == 'gene'][['seqid', 'start_half', 'end_half', 'strand']].copy()

# Промоторы (1000 bp вверх от TSS)
for _, row in genes.iterrows():
    if row['strand'] == '+':
        start = row['start_half'] - 1000
        end = row['start_half']
        start, end = clip_negative(start, end)
    else:  # strand == '-'
        start = row['end_half']
        end = row['end_half'] + 1000
    regions_list.append([row['seqid'], start, end, 'Promoters'])

# Downstream (200 bp после гена)
for _, row in genes.iterrows():
    if row['strand'] == '+':
        start = row['end_half']
        end = row['end_half'] + 200
    else:
        start = row['start_half'] - 200
        end = row['start_half']
        start, end = clip_negative(start, end)
    regions_list.append([row['seqid'], start, end, 'Downstream'])

# Интроны
for _, gene in genes.iterrows():

    exon_mask = (exons['seqid'] == gene['seqid']) & \
                (exons['start_half'] >= gene['start_half']) & \
                (exons['end_half'] <= gene['end_half'])
    gene_exons = exons[exon_mask].sort_values('start_half')
    if len(gene_exons) < 2:
        continue
    for i in range(len(gene_exons) - 1):
        intron_start = gene_exons.iloc[i]['end_half']
        intron_end = gene_exons.iloc[i+1]['start_half']
        if intron_start < intron_end:
            regions_list.append([gene['seqid'], intron_start, intron_end, 'Introns'])

# Межгенные области
for seqid in genes['seqid'].unique():
    genes_on_chr = genes[genes['seqid'] == seqid].sort_values('start_half')
    if len(genes_on_chr) < 2:
        continue
    for i in range(len(genes_on_chr) - 1):
        gap_start = genes_on_chr.iloc[i]['end_half']
        gap_end = genes_on_chr.iloc[i+1]['start_half']
        if gap_start < gap_end:
            regions_list.append([seqid, gap_start, gap_end, 'Intergenic'])

# Создаём единый DataFrame
regions_df = pd.DataFrame(regions_list, columns=['seqid', 'start_half', 'end_half', 'region_type'])

In [36]:
print(f"Всего регионов: {len(regions_df)}")
regions_df.head()

Всего регионов: 416115

        seqid  start_half  end_half region_type
0  OX597814.1      166925    259181       Exons
1  OX597814.1      167290    259181       Exons
2  OX597814.1      166925    166943       Exons
3  OX597814.1      167290    167848       Exons
4  OX597814.1      167590    167848       Exons

In [37]:
# интервальные деревья для каждого типа региона

region_trees = {}
for region_type in regions_df['region_type'].unique():
    subset = regions_df[regions_df['region_type'] == region_type]
    trees = defaultdict(IntervalTree)
    for _, row in subset.iterrows():
        trees[row['seqid']].addi(row['start_half'], row['end_half'], None)
    region_trees[region_type] = trees

In [38]:
# Подсчёт уникальных структур, попавших в регионы

def count_structures_in_regions(struct_trees, region_trees, overlap_threshold=0.9):
    results = {}
    for region_type, r_trees in region_trees.items():
        structure_ids = set()
        for seqid, rtree in r_trees.items():
            if seqid not in struct_trees:
                continue
            stree = struct_trees[seqid]
            for s_interval in stree:
                s_start, s_end, s_id = s_interval.begin, s_interval.end, s_interval.data
                overlapping = rtree.overlap(s_start, s_end)
                for r_interval in overlapping:
                    if overlap_ratio(r_interval.begin, r_interval.end, s_start, s_end) >= overlap_threshold:
                        structure_ids.add(s_id)
                        break
        results[region_type] = len(structure_ids)
    return results

In [39]:
# Подсчёт регионов, содержащих хотя бы одну структуру

def count_regions_with_structures(region_trees, struct_trees, overlap_threshold=0.9):
    results = {}
    for region_type, r_trees in region_trees.items():
        region_counter = 0
        for seqid, rtree in r_trees.items():
            if seqid not in struct_trees:
                continue
            stree = struct_trees[seqid]
            for r_interval in rtree:
                r_start, r_end = r_interval.begin, r_interval.end
                overlapping = stree.overlap(r_start, r_end)
                for s_interval in overlapping:
                    if overlap_ratio(r_start, r_end, s_interval.begin, s_interval.end) >= overlap_threshold:
                        region_counter += 1
                        break
        results[region_type] = region_counter
    return results

In [40]:
# Вычисление результатов

# Общее количество структур каждого типа
total_g4 = len(g4)
total_zhun = len(zhunt)
total_zdnabert = len(zdnabert)

# Первая таблица: число структур в регионах
g4_counts = count_structures_in_regions(g4_trees, region_trees)
zhun_counts = count_structures_in_regions(zhun_trees, region_trees)
zdnabert_counts = count_structures_in_regions(zdnabert_trees, region_trees)

# Вторая таблица: число регионов со структурами
regions_with_g4 = count_regions_with_structures(region_trees, g4_trees)
regions_with_zhun = count_regions_with_structures(region_trees, zhun_trees)
regions_with_zdnabert = count_regions_with_structures(region_trees, zdnabert_trees)

# Общее количество регионов каждого типа (из regions_df)
total_regions = regions_df.groupby('region_type').size().to_dict()

for rt in region_trees.keys():
    if rt not in total_regions:
        total_regions[rt] = 0

In [ ]:
# Таблица 1
table1_data = []
for region_type in sorted(region_trees.keys()):
    table1_data.append([
        region_type,
        g4_counts[region_type],
        f"{g4_counts[region_type]/total_g4:.2%}" if total_g4 else "0%",
        zhun_counts[region_type],
        f"{zhun_counts[region_type]/total_zhun:.2%}" if total_zhun else "0%",
        zdnabert_counts[region_type],
        f"{zdnabert_counts[region_type]/total_zdnabert:.2%}" if total_zdnabert else "0%"
    ])
table1 = pd.DataFrame(table1_data, columns=[
    'Участок', 'Число квадруплексов', 'Доля квадруплексов',
    'Число предсказаний Zhun', 'Доля предсказаний Zhun',
    'Число предсказаний ZDNABERT', 'Доля предсказаний ZDNABERT'
])
print("Таблица 1:")
print(table1.to_string(index=False))

# Таблица 2
table2_data = []
for region_type in sorted(region_trees.keys()):
    total = total_regions.get(region_type, 0)
    table2_data.append([
        region_type,
        regions_with_g4[region_type],
        f"{regions_with_g4[region_type]/total:.2%}" if total else "0%",
        regions_with_zhun[region_type],
        f"{regions_with_zhun[region_type]/total:.2%}" if total else "0%",
        regions_with_zdnabert[region_type],
        f"{regions_with_zdnabert[region_type]/total:.2%}" if total else "0%"
    ])
table2 = pd.DataFrame(table2_data, columns=[
    'Участок', 'Число участков с квадруплексом', 'Доля участков с квадруплексом',
    'Число участков с предсказанием Zhun', 'Доля участков с предсказанием Zhun',
    'Число участков с предсказанием ZDNABERT', 'Доля участков с предсказанием ZDNABERT'
])
print("\nТаблица 2:")
print(table2.to_string(index=False))

Таблица 1:
   Участок  Число квадруплексов Доля квадруплексов  Число предсказаний Zhun Доля предсказаний Zhun  Число предсказаний ZDNABERT Доля предсказаний ZDNABERT
Downstream                  120              0.14%                        0                  0.00%                          168                      0.08%
     Exons                32554             38.79%                      233                 28.77%                        59103                     27.83%
Intergenic                51144             60.94%                      577                 71.23%                       152930                     72.00%
   Introns                31186             37.16%                      225                 27.78%                        56000                     26.36%
 Promoters                 1309              1.56%                        5                  0.62%                         2526                      1.19%

Таблица 2:
   Участок  Число участков с квадруплексом Доля участков с квадруплексом  Число участков с предсказанием Zhun Доля участков с предсказанием Zhun  Число участков с предсказанием ZDNABERT Доля участков с предсказанием ZDNABERT
Downstream                             114                         0.45%                                    0                              0.00%                                      156                                  0.62%
     Exons                           13708                         6.76%                                  255                              0.13%                                    14493                                  7.15%
Intergenic                           11174                        46.09%                                  448                              1.85%                                    11667                                 48.13%
   Introns                           16623                        11.96%                                  204                              0.15%                                    18486                                 13.31%
 Promoters                            1155                         4.60%                                    5                              0.02%                                     1872                                  7.45%

In [ ]:
table1

,Участок,Число квадруплексов,Доля квадруплексов,Число предсказаний Zhun,Доля предсказаний Zhun,Число предсказаний ZDNABERT,Доля предсказаний ZDNABERT
0,Downstream,120,0.14%,0,0.00%,168,0.08%
1,Exons,32554,38.79%,233,28.77%,59103,27.83%
2,Intergenic,51144,60.94%,577,71.23%,152930,72.00%
3,Introns,31186,37.16%,225,27.78%,56000,26.36%
4,Promoters,1309,1.56%,5,0.62%,2526,1.19%

In [ ]:
table2

,Участок,Число участков с квадруплексом,Доля участков с квадруплексом,Число участков с предсказанием Zhun,Доля участков с предсказанием Zhun,Число участков с предсказанием ZDNABERT,Доля участков с предсказанием ZDNABERT
0,Downstream,114,0.45%,0,0.00%,156,0.62%
1,Exons,13708,6.76%,255,0.13%,14493,7.15%
2,Intergenic,11174,46.09%,448,1.85%,11667,48.13%
3,Introns,16623,11.96%,204,0.15%,18486,13.31%
4,Promoters,1155,4.60%,5,0.02%,1872,7.45%

# Для групповой части

## Проверка наличия CTCF и когезина

In [13]:
!ls -lh /content/Pfam-A.hmm

-rw-r--r-- 1 root root 1.5G Nov 15  2021 /content/Pfam-A.hmm

In [14]:
# Поищем PF00096 в базе
!grep "PF00096" /content/Pfam-A.hmm | head -5

# Поищем PF01132
!grep "PF01132" /content/Pfam-A.hmm | head -5

# Поищем PF02463
!grep "PF02463" /content/Pfam-A.hmm | head -5

# Поищем PF04824
!grep "PF04824" /content/Pfam-A.hmm | head -5

ACC   PF00096.29
ACC   PF01132.23
ACC   PF02463.22
ACC   PF04824.19

In [15]:
!hmmfetch /content/Pfam-A.hmm PF00096.29 > /content/zf-C2H2.hmm
!hmmfetch /content/Pfam-A.hmm PF01132.23 > /content/CTCF_Nterm.hmm
!hmmfetch /content/Pfam-A.hmm PF02463.22 > /content/smc.hmm
!hmmfetch /content/Pfam-A.hmm PF04824.19 > /content/rad21.hmm

In [16]:
!hmmsearch --tblout smc_results.txt -E 1e-5 /content/smc.hmm /content/protein.faa
!hmmsearch --tblout rad21_results.txt -E 1e-5 /content/rad21.hmm /content/protein.faa
!hmmsearch --tblout c2h2_results.txt -E 1e-5 /content/zf-C2H2.hmm /content/protein.faa
!hmmsearch --tblout ctcf_results.txt -E 1e-5 /content/CTCF_Nterm.hmm /content/protein.faa

Выходные данные были обрезаны до нескольких последних строк (5000).
   4 !   16.8   0.3   0.00078     0.011       2      23 .]     147     169 ..     146     169 .. 0.95
   5 ?   12.2   3.3     0.022      0.32       1      23 []     347     371 ..     347     371 .. 0.91
   6 ?   10.0   0.5      0.11       1.6       1      22 [.     391     412 ..     391     415 .. 0.88
   7 ?    8.1   0.1      0.48       6.8       1      23 []     489     513 ..     489     513 .. 0.93
   8 ?   10.7   0.3     0.072         1       2      21 ..     725     744 ..     724     745 .. 0.92
   9 ?    7.7   0.1      0.63         9       2      23 .]     862     884 ..     861     884 .. 0.93
  10 ?   10.3   6.4     0.094       1.3       1      22 [.    1412    1433 ..    1412    1437 .. 0.94
  11 ?    8.1   0.8      0.46       6.5       1      23 []    1619    1641 ..    1619    1641 .. 0.97
  12 ?   10.0   0.4      0.12       1.7       2      23 .]    1777    1799 ..    1776    1799 .. 0.96
  13 ?    5.2   2.8       3.9        55       2      23 .]    2106    2129 ..    2106    2129 .. 0.89

  Alignments for each domain:
  == domain 1  score: 12.2 bits;  conditional E-value: 0.024
                  EEETTTTEEESSHHHHHHHHH CS
       zf-C2H2  1 ykCpdCgksFkrksnLkrHir 21
                  ++C  C+++F++ ++L +H++
  CAI9735131.1 41 FRCQTCTQTFTNIDSLYTHQN 61
                  89*****************97 PP

  == domain 2  score: 6.2 bits;  conditional E-value: 1.9
                   ET..TTTEEESSHHHHHHHHHC.C CS
       zf-C2H2   3 Cp..dCgksFkrksnLkrHirt.H 23
                   C   +C++ Fk+ ++L++H r  H
  CAI9735131.1  79 CWkkGCNQYFKTGHSLQVHFREiH 102
                   77779***************9988 PP

  == domain 3  score: 9.0 bits;  conditional E-value: 0.25
                   EEETTTTEEESSHHHHHHHHHCC CS
       zf-C2H2   1 ykCpdCgksFkrksnLkrHirtH 23
                   y+C+ C+  Fk+ + L++H   H
  CAI9735131.1 118 YRCNQCSLAFKTIDKLQQHSHYH 140
                   9******************7766 PP

  == domain 4  score: 16.8 bits;  conditional E-value: 0.00078
                   EETTTTEEESSHHHHHHHHHC.C CS
       zf-C2H2   2 kCpdCgksFkrksnLkrHirt.H 23
                   +C++Cg+sF++   Lk+Hi   H
  CAI9735131.1 147 RCSICGRSFRSTLALKKHIELaH 169
                   7******************9888 PP

  == domain 5  score: 12.2 bits;  conditional E-value: 0.022
                   EEETTTTEEESSHHHHHHHHHC..C CS
       zf-C2H2   1 ykCpdCgksFkrksnLkrHirt..H 23
                   +kC+ C+  F+ +s L++H +t  H
  CAI9735131.1 347 FKCHRCKVAFTKQSYLTAHNKTlqH 371
                   8******************887555 PP

  == domain 6  score: 10.0 bits;  conditional E-value: 0.11
                   EEETTTTEEESSHHHHHHHHHC CS
       zf-C2H2   1 ykCpdCgksFkrksnLkrHirt 22
                   ykC++C++sF++k  L +H+++
  CAI9735131.1 391 YKCDVCKESFTQKNILLVHYNS 412
                   9************999999876 PP

  == domain 7  score: 8.1 bits;  conditional E-value: 0.48
                   EEETTTTEEESSHHHHHHHHHC..C CS
       zf-C2H2   1 ykCpdCgksFkrksnLkrHirt..H 23
                   y+C+ C+  +++ s L  Hir+  H
  CAI9735131.1 489 YRCNLCKVAYNQGSTLDIHIRSvlH 513
                   9********************8666 PP

  == domain 8  score: 10.7 bits;  conditional E-value: 0.072
                   EETTTTEEESSHHHHHHHHH CS
       zf-C2H2   2 kCpdCgksFkrksnLkrHir 21
                    C  C+ +F++++ L +H++
  CAI9735131.1 725 ACQNCNSVFSNQETLIQHQQ 744
                   6*****************97 PP

  == domain 9  score: 7.7 bits;  conditional E-value: 0.63
                   EETTTTEEESSHHHHHHHHHC.C CS
       zf-C2H2   2 kCpdCgksFkrksnLkrHirt.H 23
                   +C+ C+k F++   Lk+H+   H
  CAI9735131.1 862 VCTRCNKEFSSVWVLKAHQEEiH 884
                   7*****************98877 PP

  == domain 10  score: 10.3 bits;  conditional E-value: 0.094
                    EEETTTTEEESSHHHHHHHHHC CS
       zf-C2H2    1 ykCpdCgksFkrksnLkrHirt 22
                    y+C++C+  F+r ++L++H+++
  CAI9735131.1 1412 YQCKKCHSIFPRYYDLMKHQKR 1433
                    9*******************97 PP

  == domain 11  score: 8.1 bits;  conditional E-value: 0.46
                    EEETTTTEEESSHHHHHHHHHCC CS
       zf-C2H2    1 ykCpdCgksFkrksnLkrHirtH 23
                    ++C++C+  F+  ++ + H+++H
  CAI9735131.1 1619 HRCDKCNLFFPKIEQWQEHLNVH 1641
                    79*******************99 PP

  == domain 12  score: 10.0 bits;  conditional E-value: 0.12
                    EETTTTEEESSHHHHHHHHHC.C CS
       zf-C2H2    2 kCpdCgksFkrksnLkrHirt.H 23
                    +Cp C   F+ ks L++H+ t H
  CAI9735131.1 1777 RCPFCRALFRAKSALESHLATkH 1799
                    7*******************999 PP

  == domain 13  score: 5.2 bits;  conditional E-value: 3.9
                    EETTTTEEESSHHHHHHHHHC..C CS
       zf-C2H2    2 kCpdCgksFkrksnLkrHirt..H 23
                    +C+ C+ ++++k+  + Hi t  H
  CAI9735131.1 2106 ECTLCNFKYSHKYTVQDHIFTkkH 2129
                    5*****************987555 PP

>> CAI9741638.1  finger and BTB domain-containing 49-like [Octopus vulgaris]
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   16.9   1.9   0.00073      0.01       2      23 .]      88     110 ..      87     110 .. 0.95
   2 ?   10.0   0.2      0.12       1.6       6      23 .]     120     138 ..     120     138 .. 0.96
   3 !   19.2   2.0   0.00014    0.0019       3      23 .]     144     164 ..     142     164 .. 0.97
   4 !   18.1   2.4   0.00032    0.0045       1      23 []     170     192 ..     170     192 .. 0.96
   5 ?    8.1   2.0      0.46       6.6       1      19 [.     351     369 ..     351     372 .. 0.94

  Alignments for each domain:
  == domain 1  score: 16.9 bits;  conditional E-value: 0.00073
                   EETTTTEEESSHHHHHHHHHC.C CS
       zf-C2H2   2 kCpdCgksFkrksnLkrHirt.H 23
                    Cp C+++  rk nLkrHi t H
  CAI9741638.1  88 LCPQCHYVTDRKNNLKRHIITmH 110
                   5*******************999 PP

  == domain 2  score: 10.0 bits;  conditional E-value: 0.12
                   TTEEESSHHHHHHHHHC.C CS
       zf-C2H2   6 CgksFkrksnLkrHirt.H 23
                   Cg +F++k +L+ H +  H
  CAI9741638.1 120 CGFVFRSKASLREHVSLfH 138
                   **************99888 PP

  == domain 3  score: 19.2 bits;  conditional E-value: 0.00014
                   ETTTTEEESSHHHHHHHHHCC CS
       zf-C2H2   3 CpdCgksFkrksnLkrHirtH 23
                   C +Cg+ F+rk +L+rH+++H
  CAI9741638.1 144 CRICGRNFCRKALLRRHLSVH 164
                   *******************99 PP

  == domain 4  score: 18.1 bits;  conditional E-value: 0.00032
                   EEETTTTEEESSHHHHHHHHHCC CS
       zf-C2H2   1 ykCpdCgksFkrksnLkrHirtH 23
                   y Cp C++  ++ksnL+rH+++H
  CAI9741638.1 170 YLCPFCSYATSHKSNLERHQKVH 192
                   66*******************99 PP

  == domain 5  score: 8.1 bits;  conditional E-value: 0.46
                   EEETTTTEEESSHHHHHHH CS
       zf-C2H2   1 ykCpdCgksFkrksnLkrH 19
                   ykC dC   F+++s+L++H
  CAI9741638.1 351 YKCIDCRNIFSHQSLLNSH 369
                   8999*************** PP

>> CAI9742639.1  protein krueppel-like isoform X2 [Octopus vulgaris]
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   29.9   3.4   5.7e-08   8.1e-07       1      23 []      29      51 ..      29      51 .. 0.98
   2 !   31.0   1.3   2.5e-08   3.5e-07       1      23 []      57      79 ..      57      79 .. 0.98

  Alignments for each domain:
  == domain 1  score: 29.9 bits;  conditional E-value: 5.7e-08
                  EEETTTTEEESSHHHHHHHHHCC CS
       zf-C2H2  1 ykCpdCgksFkrksnLkrHirtH 23
                  y C++CgksF+++++L++H r+H
  CAI9742639.1 29 YHCNICGKSFSQSYDLTKHKRVH 51
                  89********************9 PP

  == domain 2  score: 31.0 bits;  conditional E-value: 2.5e-08
                  EEETTTTEEESSHHHHHHHHHCC CS
       zf-C2H2  1 ykCpdCgksFkrksnLkrHirtH 23
                  ++C++CgksF+r++ L++H r+H
  CAI9742639.1 57 FRCDICGKSFSRNDTLTSHKRIH 79
                  89*******************99 PP

>> CAI9743706.1  zinc finger 271-like [Octopus vulgaris]
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   24.5   1.3     3e-06   4.3e-05       1      23 []      21      43 ..      21      43 .. 0.98
   2 !   22.0   2.3   1.9e-05   0.00026       1      23 []      49      71 ..      49      71 .. 0.98
   3 !   14.4   0.3    0.0046     0.065       1      15 [.      77      91 ..      77      91 .. 0.91

  Alignments for each domain:
  == domain 1  score: 24.5 bits;  conditional E-value: 3e-06
                  EEETTTTEEESSHHHHHHHHHCC CS
       zf-C2H2  1 ykCpdCgksFkrksnLkrHirtH 23
                  y C+ Cgk F+rk nL +H+r+H
  CAI9743706.1 21 YDCDTCGKLFSRKTNLLTHRRIH 43
                  89********************9 PP

  == domain 2  score: 22.0 bits;  conditional E-value: 1.9e-05
                  EEETTTTEEESSHHHHHHHHHCC CS
       zf-C2H2  1 ykCpdCgksFkrksnLkrHirtH 23
                  y C+ Cg+sF+ +  L rH+r+H
  CAI9743706.1 49 YHCDTCGRSFSENQGLSRHRRVH 71
                  89********************9 PP

  == domain 3  score: 14.4 bits;  conditional E-value: 0.0046
                  EEETTTTEEESSHHH CS
       zf-C2H2  1 ykCpdCgksFkrksn 15
                  y C++CgksF +k n
  CAI9743706.1 77 YHCDICGKSFAQKGN 91
                  89********99875 PP

>> CAI9739615.1  finger and BTB domain-containing 14-like [Octopus vulgaris]
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   24.2   5.9   3.6e-06   5.1e-05       2      23 .]       3      24 ..       2      24 .. 0.96
   2 !   20.9   2.3     4e-05   0.00057       1      23 []      30      52 ..      30      52 .. 0.97
   3 !   14.6   8.2     0.004     0.057       1      23 []      58      80 ..      58      80 .. 0.98
   4 ?    9.6   1.1      0.16       2.3       1      15 [.      86     100 ..      86     107 .. 0.81

  Alignments for each domain:
  == domain 1  score: 24.2 bits;  conditional E-value: 3.6e-06
                  EETTTTEEESSHHHHHHHHHCC CS
       zf-C2H2  2 kCpdCgksFkrksnLkrHirtH 23
                  +C+ C+k+F++ks+L++H+r+H
  CAI9739615.1  3 TCSLCSKTFTSKSSLTTHMRSH 24
                  8********************9 PP

  == domain 2  score: 20.9 bits;  conditional E-value: 4e-05
                  EEETTTTEEESSHHHHHHHHHCC CS
       zf-C2H2  1 ykCpdCgksFkrksnLkrHirtH 23
                  y+C++C+k+F+r+ +L+ H  +H
  CAI9739615.1 30 YQCDICKKRFTRNTSLNYHKLVH 52
                  9******************9998 PP

  == domain 3  score: 14.6 bits;  conditional E-value: 0.004
                  EEETTTTEEESSHHHHHHHHHCC CS
       zf-C2H2  1 ykCpdCgksFkrksnLkrHirtH 23
                  ++C+ C+k F+++ +++ H  +H
  CAI9739615.1 58 FTCKLCDKHFRHRGHFNDHVLKH 80
                  89******************999 PP

  == domain 4  score: 9.6 bits;  conditional E-value: 0.16
                   EEETTTTEEESSHHH CS
       zf-C2H2   1 ykCpdCgksFkrksn 15
                   ++C+ C+k+F+++
  CAI9739615.1  86 FECGRCHKTFPSRQK 100
                   89********99865 PP

>> CAI9743565.1  zinc finger 91-like [Octopus vulgaris]
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   24.5   1.3   2.8e-06     4e-05       1      23 []      18      40 ..      18      40 .. 0.98
   2 !   22.0   2.3   1.8e-05   0.00025       1      23 []      46      68 ..      46      68 .. 0.98
   3 !   14.5   0.3    0.0043     0.062       1      15 [.      74      88 ..      74      88 .. 0.91

  Alignments for each domain:
  == domain 1  score: 24.5 bits;  conditional E-value: 2.8e-06
                  EEETTTTEEESSHHHHHHHHHCC CS
       zf-C2H2  1 ykCpdCgksFkrksnLkrHirtH 23
                  y C+ Cgk F+rk nL +H+r+H
  CAI9743565.1 18 YDCDTCGKLFSRKTNLLTHRRIH 40
                  89********************9 PP

  == domain 2  score: 22.0 bits;  conditional E-value: 1.8e-05
                  EEETTTTEEESSHHHHHHHHHCC CS
       zf-C2H2  1 ykCpdCgksFkrksnLkrHirtH 23
                  y C+ Cg+sF+ +  L rH+r+H
  CAI9743565.1 46 YHCDTCGRSFSENQGLSRHRRVH 68
                  89********************9 PP

  == domain 3  score: 14.5 bits;  conditional E-value: 0.0043
                  EEETTTTEEESSHHH CS
       zf-C2H2  1 ykCpdCgksFkrksn 15
                  y C++CgksF +k n
  CAI9743565.1 74 YHCDICGKSFAQKGN 88
                  89********99875 PP

>> CAI9743654.1  ---NA--- [Octopus vulgaris]
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   15.7   0.1    0.0018     0.025       3      17 ..       9      25 ..       8      25 .. 0.94
   2 !   25.6   0.1   1.3e-06   1.8e-05       2      23 .]      25      46 ..      24      46 .. 0.96
   3 !   14.5   0.3    0.0045     0.064       1      13 [.      52      64 ..      52      66 .] 0.92

  Alignments for each domain:
  == domain 1  score: 15.7 bits;  conditional E-value: 0.0018
                  ET..TTTEEESSHHHHH CS
       zf-C2H2  3 Cp..dCgksFkrksnLk 17
                  C+  +CgksF+r+ nL+
  CAI9743654.1  9 CHgyICGKSFSRRPNLT 25
                  9999*********9996 PP

  == domain 2  score: 25.6 bits;  conditional E-value: 1.3e-06
                  EETTTTEEESSHHHHHHHHHCC CS
       zf-C2H2  2 kCpdCgksFkrksnLkrHirtH 23
                  +C++CgksF++ s L +H ++H
  CAI9743654.1 25 TCGICGKSFSQISTLISHKSIH 46
                  8******************999 PP

  == domain 3  score: 14.5 bits;  conditional E-value: 0.0045
                  EEETTTTEEESSH CS
       zf-C2H2  1 ykCpdCgksFkrk 13
                  y+C++Cg+ F++k
  CAI9743654.1 52 YQCNICGMAFSHK 64
                  9**********97 PP

>> CAI9738574.1  transcription factor Sp5-like [Octopus vulgaris]
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   17.7   2.1   0.00041    0.0059       1      23 []     335     359 ..     335     359 .. 0.95
   2 !   28.2   0.8     2e-07   2.8e-06       1      23 []     365     389 ..     365     389 .. 0.98
   3 !   21.0   2.8   3.7e-05   0.00053       1      23 []     395     417 ..     395     417 .. 0.97

  Alignments for each domain:
  == domain 1  score: 17.7 bits;  conditional E-value: 0.00041
                   EEET..TTTEEESSHHHHHHHHHCC CS
       zf-C2H2   1 ykCp..dCgksFkrksnLkrHirtH 23
                   + C+  +Cgk++   s+Lk+H+r H
  CAI9738574.1 335 HICHipGCGKVYGKTSHLKAHLRWH 359
                   579********************99 PP

  == domain 2  score: 28.2 bits;  conditional E-value: 2e-07
                   EEET..TTTEEESSHHHHHHHHHCC CS
       zf-C2H2   1 ykCp..dCgksFkrksnLkrHirtH 23
                   ++C+   CgksF+r+++L+rH+rtH
  CAI9738574.1 365 FVCNwlFCGKSFTRSDELQRHLRTH 389
                   89**********************9 PP

  == domain 3  score: 21.0 bits;  conditional E-value: 3.7e-05
                   EEETTTTEEESSHHHHHHHHHCC CS
       zf-C2H2   1 ykCpdCgksFkrksnLkrHirtH 23
                   + C++Cgk+F r+++L +H +tH
  CAI9738574.1 395 FACSECGKRFMRSDHLSKHVKTH 417
                   78********************9 PP

>> CAI9743762.1  finger 92-like [Octopus vulgaris]
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   25.9   1.2     1e-06   1.4e-05       1      23 []      17      39 ..      17      39 .. 0.97
   2 !   20.6   6.2     5e-05   0.00071       1      23 []      45      67 ..      45      67 .. 0.97
   3 !   15.0   0.4     0.003     0.042       1      18 [.      73      90 ..      73      90 .. 0.94
   4 ?    4.3   0.3       7.5   1.1e+02       1       8 [.     101     108 ..     101     112 .. 0.88

  Alignments for each domain:
  == domain 1  score: 25.9 bits;  conditional E-value: 1e-06
                  EEETTTTEEESSHHHHHHHHHCC CS
       zf-C2H2  1 ykCpdCgksFkrksnLkrHirtH 23
                  y C++Cg sF+ +s+L++H+r+H
  CAI9743762.1 17 YFCDICGTSFNYNSQLTSHRRIH 39
                  88********************9 PP

  == domain 2  score: 20.6 bits;  conditional E-value: 5e-05
                  EEETTTTEEESSHHHHHHHHHCC CS
       zf-C2H2  1 ykCpdCgksFkrksnLkrHirtH 23
                  y C++C+ksF+++s L++H  tH
  CAI9743762.1 45 YHCDICDKSFSSNSTLTHHKYTH 67
                  89*****************9999 PP

  == domain 3  score: 15.0 bits;  conditional E-value: 0.003
                  EEETTTTEEESSHHHHHH CS
       zf-C2H2  1 ykCpdCgksFkrksnLkr 18
                  y C++C+ksF+ +s+L++
  CAI9743762.1 73 YHCDICSKSFPGSSDLTK 90
                  89**************86 PP

  == domain 4  score: 4.3 bits;  conditional E-value: 7.5
                   EEETTTTE CS
       zf-C2H2   1 ykCpdCgk 8
                   y+C++Cg
  CAI9743762.1 101 YQCDICGI 108
                   9*****95 PP

>> CAI9732798.1  ---NA--- [Octopus vulgaris]
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 ?    7.6   0.2      0.69       9.8       3      12 ..      13      22 ..      11      25 .. 0.85
   2 !   29.9   0.7   5.7e-08   8.1e-07       1      23 []      40      62 ..      40      62 .. 0.98
   3 !   14.3   1.9     0.005     0.072       3      23 .]      70      90 ..      69      90 .. 0.97
   4 !   13.8   2.9    0.0074       0.1       1      23 []      97     119 ..      97     119 .. 0.97
   5 ?    4.9   0.6         5        71       2      10 ..     124     132 ..     123     133 .] 0.93

  Alignments for each domain:
  == domain 1  score: 7.6 bits;  conditional E-value: 0.69
                  ETTTTEEESS CS
       zf-C2H2  3 CpdCgksFkr 12
                  C +CgksF +
  CAI9732798.1 13 CLVCGKSFVH 22
                  99******87 PP

  == domain 2  score: 29.9 bits;  conditional E-value: 5.7e-08
                  EEETTTTEEESSHHHHHHHHHCC CS
       zf-C2H2  1 ykCpdCgksFkrksnLkrHirtH 23
                  ++C++CgksF++  +L++H+++H
  CAI9732798.1 40 HTCEVCGKSFSQAGLLTSHMKVH 62
                  79********************9 PP

  == domain 3  score: 14.3 bits;  conditional E-value: 0.005
                  ETTTTEEESSHHHHHHHHHCC CS
       zf-C2H2  3 CpdCgksFkrksnLkrHirtH 23
                  C++CgksF + + + +HirtH
  CAI9732798.1 70 CKVCGKSFLQHEPFSQHIRTH 90
                  ********************9 PP

  == domain 4  score: 13.8 bits;  conditional E-value: 0.0074
                   EEETTTTEEESSHHHHHHHHHCC CS
       zf-C2H2   1 ykCpdCgksFkrksnLkrHirtH 23
                   + Cp+C +sF   s L++H++tH
  CAI9732798.1  97 HSCPICEQSFHEESILRTHMKTH 119
                   68********************9 PP

  == domain 5  score: 4.9 bits;  conditional E-value: 5
                   EETTTTEEE CS
       zf-C2H2   2 kCpdCgksF 10
                   +C +C ksF
  CAI9732798.1 124 QCQVCRKSF 132
                   7*******9 PP

>> CAI9743772.1  finger 92-like [Octopus vulgaris]
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   25.8   1.0   1.1e-06   1.6e-05       1      23 []      17      39 ..      17      39 .. 0.97
   2 !   21.5   6.2   2.6e-05   0.00037       1      23 []      45      67 ..      45      67 .. 0.97

In [19]:
def show_hits(filename, name):
    print(f"\n===== {name} =====")
    try:
        with open(filename, 'r') as f:
            lines = [l for l in f if not l.startswith('#') and l.strip()]
        if not lines:
            print("Нет попаданий (файл пуст)")
            return
        data = []
        for line in lines:
            cols = line.split()
            if len(cols) >= 6 and float(cols[4]) < 1e-5:
                data.append([cols[0], cols[4], cols[5]])
        if data:
            df = pd.DataFrame(data, columns=['Protein_ID', 'E-value', 'Score'])
            print(df.to_string(index=False))
        else:
            print("Нет белков с E-value < 1e-5")
    except FileNotFoundError:
        print("Файл не найден")

show_hits('smc_results.txt', 'SMC (когезин)')
show_hits('rad21_results.txt', 'RAD21 (когезин)')
show_hits('c2h2_results.txt', 'CTCF (цинковые пальцы PF00096)')
show_hits('ctcf_results.txt', 'CTCF (N-term PF01132)')

===== SMC (когезин) =====
  Protein_ID E-value Score
CAI9732558.1 3.7e-58 197.3
CAI9728869.1 3.9e-54 184.1
CAI9721520.1   2e-48 165.5
CAI9722573.1 4.8e-37 128.3
CAI9722575.1 2.7e-35 122.6
CAI9728495.1 1.3e-18  68.0
CAI9715598.1 9.1e-14  52.2
CAI9729080.1 3.4e-13  50.3
CAI9715599.1 5.6e-13  49.6
CAI9716157.1 1.3e-11  45.1
CAI9737156.1 1.6e-11  44.8
CAI9714744.1 1.6e-11  44.8
CAI9738873.1 3.2e-11  43.8
CAI9716156.1 6.2e-11  42.9
CAI9737729.1 2.9e-10  40.7
CAI9738035.1 1.4e-09  38.5
CAI9738036.1 1.4e-09  38.5
CAI9724597.1 1.5e-09  38.4
CAI9727682.1 3.2e-09  37.3
CAI9727681.1 3.6e-09  37.1
CAI9738034.1 5.5e-09  36.5
CAI9734867.1 2.1e-08  34.6
CAI9715527.1 3.3e-08  34.0
CAI9737224.1 3.7e-08  33.8
CAI9725993.1 1.3e-07  32.0
CAI9738334.1 3.8e-07  30.5
CAI9738032.1 7.3e-07  29.6
CAI9728469.1 8.4e-07  29.4
CAI9738031.1 9.7e-07  29.2
CAI9737201.1 1.1e-06  29.1
CAI9728910.1 1.3e-06  28.7
CAI9715464.1   3e-06  27.6
CAI9733037.1 5.1e-06  26.8

===== RAD21 (когезин) =====
  Protein_ID E-value Score
CAI9721988.1 6.2e-17  61.4
CAI9721989.1 6.2e-17  61.3
CAI9733164.1 6.8e-07  29.2

===== CTCF (цинковые пальцы PF00096) =====
  Protein_ID  E-value  Score
CAI9726407.1        0 3216.1
CAJ1099264.1        0 2001.2
CAJ1099297.1        0 1860.0
CAI9742053.1   2e-234  746.7
CAI9742630.1   7e-213  678.9
CAI9743549.1 1.6e-184  589.6
CAI9743094.1 7.3e-177  565.5
CAI9740262.1 3.3e-161  516.1
CAI9740263.1 4.9e-161  515.6
CAI9738307.1 2.2e-160  513.5
CAI9743748.1 5.7e-160  512.2
CAI9742618.1 1.5e-154  495.2
CAI9742142.1 3.6e-153  490.8
CAI9742089.1 4.6e-152  487.3
CAI9743778.1 6.2e-152  486.9
CAI9724627.1 1.1e-148  476.8
CAI9743872.1 1.2e-148  476.6
CAI9742637.1 5.2e-147  471.4
CAI9742418.1 5.5e-147  471.3
CAI9742683.1 6.6e-144  461.6
CAI9743878.1 3.3e-140  450.0
CAI9716979.1 2.5e-139  447.2
CAI9742678.1 1.6e-137  441.6
CAI9739841.1 3.3e-137  440.6
CAI9740259.1 3.2e-136  437.4
CAI9742517.1 4.3e-135  433.9
CAI9742381.1 9.8e-135  432.8
CAI9744221.1 2.7e-134  431.4
CAI9743102.1 4.1e-134  430.8
CAI9742893.1 1.2e-133  429.4
CAI9742078.1 6.8e-133  427.0
CAI9742088.1 1.5e-131  422.8
CAI9742104.1 2.4e-131  422.1
CAI9739839.1 3.1e-131  421.7
CAI9742380.1 6.5e-131  420.7
CAI9742092.1 6.8e-131  420.7
CAI9740260.1   8e-131  420.4
CAI9743107.1   9e-130  417.1
CAI9743902.1 1.9e-129  416.1
CAI9723330.1   2e-129  416.0
CAI9738308.1 2.1e-129  416.0
CAI9739838.1 2.4e-129  415.8
CAI9742447.1 1.3e-128  413.5
CAI9743555.1   3e-127  409.2
CAI9738298.1 5.3e-127  408.4
CAI9716982.1 1.5e-126  407.0
CAI9742082.1 1.9e-126  406.6
CAI9743119.1 2.4e-126  406.4
CAI9742649.1 4.1e-126  405.6
CAI9742607.1 7.1e-126  404.9
CAI9742706.1   5e-125  402.2
CAI9742080.1 5.8e-125  402.0
CAI9744232.1 9.5e-125  401.3
CAI9743817.1 1.7e-124  400.5
CAI9743678.1 7.1e-124  398.5
CAI9742091.1 5.1e-122  392.7
CAI9743818.1 3.8e-121  389.9
CAI9744467.1 5.3e-121  389.5
CAI9738310.1 9.4e-121  388.7
CAI9742038.1 1.1e-120  388.5
CAI9743999.1 1.2e-120  388.3
CAI9743710.1 2.6e-120  387.3
CAI9743695.1 3.7e-120  386.9
CAI9742643.1 5.1e-120  386.4
CAI9742084.1 2.5e-119  384.2
CAI9742534.1 3.3e-119  383.8
CAI9724106.1 6.4e-119  383.0
CAI9742112.1 7.7e-117  376.4
CAI9743993.1 8.6e-117  376.2
CAI9738296.1 1.5e-116  375.5
CAI9717521.1 1.5e-116  375.5
CAI9716893.1   6e-116  373.6
CAI9743111.1 1.4e-115  372.5
CAI9743122.1 1.7e-115  372.2
CAI9743113.1 4.6e-115  370.8
CAI9721449.1 6.6e-115  370.3
CAI9743790.1 1.2e-114  369.5
CAI9737164.1 9.7e-114  366.6
CAI9743116.1 5.5e-113  364.3
CAI9721258.1   2e-112  362.5
CAI9744028.1 2.6e-112  362.1
CAI9742420.1 2.6e-112  362.1
CAI9721259.1 5.3e-112  361.1
CAI9718798.1 1.5e-111  359.7
CAI9742432.1 2.1e-111  359.3
CAI9743786.1 3.5e-111  358.6
CAI9742370.1 4.4e-111  358.3
CAI9743121.1 1.2e-110  356.9
CAI9742443.1 1.2e-110  356.9
CAI9743139.1   2e-110  356.2
CAI9743834.1 3.8e-110  355.3
CAI9742629.1 6.4e-110  354.6
CAI9743112.1 9.4e-110  354.1
CAI9742640.1 1.4e-109  353.5
CAI9743780.1 2.1e-109  352.9
CAI9743114.1 2.6e-109  352.7
CAI9742459.1 2.9e-109  352.5
CAI9744125.1 3.1e-109  352.5
CAI9743687.1 8.9e-109  351.0
CAI9717063.1 1.1e-108  350.7
CAI9743771.1 1.2e-108  350.6
CAI9742880.1   2e-108  349.9
CAI9728224.1   2e-108  349.9
CAI9742122.1 2.4e-108  349.7
CAI9742725.1 5.1e-108  348.6
CAI9732586.1 5.7e-108  348.5
CAI9722144.1 5.8e-108  348.4
CAI9741943.1 7.3e-108  348.1
CAI9727930.1   1e-107  347.6
CAI9742579.1 1.4e-107  347.2
CAI9743135.1 1.4e-106  344.1
CAI9742909.1 4.2e-106  342.6
CAI9742083.1 7.1e-106  341.9
CAI9738360.1 1.1e-105  341.3
CAI9727229.1 1.7e-105  340.7
CAI9725528.1 1.8e-105  340.6
CAI9737562.1 1.8e-105  340.6
CAI9739818.1 2.7e-105  340.1
CAI9743091.1   1e-104  338.2
CAI9738208.1   1e-104  338.2
CAI9742627.1 1.3e-104  337.9
CAI9716892.1 2.3e-104  337.1
CAI9726803.1 2.6e-104  336.9
CAI9742035.1 3.1e-104  336.7
CAI9742121.1 3.4e-104  336.6
CAI9742518.1 4.5e-104  336.2
CAI9743890.1 4.8e-104  336.1
CAI9743096.1 6.1e-104  335.8
CAI9733389.1 7.5e-104  335.5
CAI9742431.1 1.3e-103  334.7
CAI9743408.1 2.8e-103  333.7
CAI9743899.1 3.4e-103  333.4
CAI9724116.1 3.4e-103  333.4
CAI9716986.1 5.2e-103  332.8
CAI9716987.1 5.2e-103  332.8
CAI9743816.1 1.3e-102  331.6
CAI9744230.1 2.4e-102  330.7
CAI9741987.1 2.5e-102  330.7
CAI9743634.1 3.3e-102  330.3
CAI9742101.1 5.2e-102  329.7
CAI9742575.1 6.2e-102  329.5
CAI9743852.1 7.2e-102  329.2
CAI9743175.1 7.9e-102  329.1
CAI9740258.1   1e-101  328.8
CAI9742634.1 1.1e-101  328.6
CAI9742069.1 2.8e-101  327.4
CAI9743848.1 3.7e-101  327.0
CAI9716980.1 4.4e-101  326.8
CAI9716985.1   5e-101  326.6
CAI9731714.1 5.7e-101  326.4
CAI9742730.1 5.8e-101  326.4
CAI9743088.1 6.8e-101  326.2
CAI9743914.1 6.9e-101  326.2
CAI9742106.1 1.3e-100  325.3
CAI9716956.1 1.9e-100  324.8
CAI9743097.1 2.5e-100  324.4
CAI9726802.1 2.6e-100  324.3
CAI9743688.1 2.6e-100  324.3
CAI9743128.1 2.7e-100  324.3
CAI9738309.1 2.7e-100  324.3
CAI9742414.1 3.1e-100  324.1
CAI9744466.1 3.2e-100  324.0
CAI9743501.1 3.9e-100  323.8
CAI9743123.1 4.1e-100  323.7
CAI9743141.1 5.2e-100  323.4
CAI9743853.1 5.8e-100  323.2
CAI9739822.1 9.1e-100  322.6
CAI9742449.1  1.3e-99  322.2
CAI9742052.1  1.5e-99  321.9
CAI9743889.1  2.1e-99  321.5
CAI9742544.1  2.3e-99  321.4
CAI9744027.1  2.6e-99  321.2
CAI9742633.1  3.3e-99  320.9
CAI9725401.1  3.8e-99  320.7
CAI9742644.1  4.4e-99  320.5
CAI9737170.1  4.4e-99  320.5
CAI9743607.1  6.6e-99  319.9
CAI9742375.1  6.8e-99  319.9
CAI9723012.1  8.9e-99  319.5
CAI9743815.1  1.1e-98  319.3
CAI9744229.1  2.1e-98  318.3
CAI9742179.1  2.6e-98  318.0
CAI9742628.1  3.8e-98  317.5
CAI9742037.1  4.1e-98  317.4
CAI9742704.1  4.3e-98  317.4
CAI9742538.1    7e-98  316.7
CAI9724115.1  7.9e-98  316.5
CAI9738649.1    1e-97  316.2
CAI9742440.1  1.1e-97  316.1
CAI9743611.1  2.9e-97  314.7
CAI9725160.1  3.7e-97  314.4
CAI9743868.1  9.5e-97  313.1
CAI9743854.1  9.9e-97  313.1
CAI9722140.1  1.1e-96  313.0
CAI9742450.1  1.5e-96  312.5
CAI9742412.1  2.1e-96  312.0
CAI9724874.1  2.6e-96  311.7
CAI9743901.1    3e-96  311.6
CAI9743124.1  3.2e-96  311.5
CAI9727227.1  1.2e-95  309.7
CAI9742139.1  1.2e-95  309.6
CAI9742050.1  1.3e-95  309.5
CAI9731715.1  1.6e-95  309.3
CAI9743768.1  2.4e-95  308.7
CAI9742635.1  6.7e-95  307.3
CAI9738358.1  9.9e-95  306.8
CAI9742542.1  1.2e-94  306.5
CAI9743614.1  1.4e-94  306.3
CAI9728229.1  1.4e-94  306.3
CAI9742513.1  1.4e-94  306.3
CAI9743926.1  5.3e-94  304.5
CAI9743144.1  5.8e-94  304.3
CAI9722143.1  7.6e-94  304.0
CAI9744228.1  1.8e-93  302.8
CAI9742718.1  2.2e-93  302.5
CAI9744222.1    3e-93  302.1
CAI9742490.1  3.2e-93  302.0
CAI9743884.1  3.3e-93  302.0
CAI9742448.1  4.6e-93  301.5
CAI9725757.1    6e-93  301.1
CAI9744324.1  6.6e-93  301.0
CAI9742520.1  9.5e-93  300.5
CAI9742471.1    1e-92  300.4
CAI9726415.1  1.1e-92  300.3
CAI9728231.1  1.2e-92  300.2
CAI9727231.1  1.2e-92  300.2
CAI9742894.1  1.6e-92  299.8
CAI9743927.1  2.1e-92  299.4
CAI9743690.1  2.2e-92  299.4
CAI9742117.1  3.2e-92  298.9
CAI9743100.1  3.7e-92  298.7
CAI9742641.1  4.1e-92  298.5
CAI9738624.1  6.9e-92  297.8
CAI9739820.1  6.9e-92  297.8
CAI9744029.1  9.3e-92  297.4
CAI9743913.1  1.1e-91  297.2
CAI9722142.1  1.1e-91  297.2
CAI9721804.1  1.1e-91  297.2
CAI9743118.1  1.5e-91  296.7
CAI9743117.1  2.1e-91  296.3
CAI9731712.1  2.7e-91  296.0
CAI9743669.1  3.7e-91  295.5
CAI9738328.1  5.2e-91  295.0
CAI9742063.1  6.4e-91  294.8
CAI9743924.1  7.8e-91  294.5
CAI9743920.1  8.2e-91  294.4
CAI9743985.1  8.5e-91  294.4
CAI9725539.1    2e-90  293.2
CAI9725801.1    2e-90  293.2
CAI9738295.1  2.1e-90  293.1
CAI9737508.1  2.3e-90  293.0
CAI9741954.1  2.4e-90  293.0
CAI9742551.1  3.6e-90  292.4
CAI9743779.1  4.5e-90  292.1
CAI9743930.1  5.3e-90  291.9
CAI9743149.1  5.3e-90  291.9
CAI9743759.1  7.5e-90  291.4
CAI9743133.1  1.2e-89  290.7
CAI9742679.1  1.4e-89  290.6
CAI9714758.1  2.2e-89  289.9
CAI9742391.1  2.3e-89  289.9
CAI9742590.1  2.4e-89  289.8
CAI9742070.1  2.4e-89  289.8
CAI9743805.1    3e-89  289.5
CAI9717984.1    3e-89  289.5
CAI9742469.1  3.6e-89  289.2
CAI9725729.1  5.9e-89  288.6
CAI9743752.1  6.8e-89  288.4
CAI9727665.1    9e-89  288.0
CAI9742664.1  1.9e-88  287.0
CAI9743793.1  2.3e-88  286.7
CAI9723801.1  2.8e-88  286.5
CAI9742181.1  3.2e-88  286.3
CAI9743958.1  4.1e-88  285.9
CAI9743741.1  4.3e-88  285.8
CAI9743799.1  4.7e-88  285.7
CAI9725410.1  5.6e-88  285.5
CAI9727936.1  5.9e-88  285.4
CAI9742619.1    6e-88  285.4
CAI9740257.1    1e-87  284.7
CAI9724123.1  1.1e-87  284.6
CAI9743115.1  1.2e-87  284.5
CAI9743000.1  1.6e-87  284.1
CAI9742524.1  1.9e-87  283.8
CAI9743733.1  2.7e-87  283.4
CAI9727225.1  3.2e-87  283.1
CAI9738319.1  3.2e-87  283.1
CAI9742109.1  3.6e-87  283.0
CAI9743693.1  5.3e-87  282.4
CAI9717983.1    7e-87  282.0
CAI9726817.1  7.1e-87  282.0
CAI9743877.1  8.7e-87  281.7
CAI9742698.1    9e-87  281.7
CAI9742437.1  1.3e-86  281.2
CAI9733345.1  1.5e-86  281.0
CAI9740264.1  1.8e-86  280.7
CAI9742646.1  1.9e-86  280.7
CAI9726140.1  1.9e-86  280.7
CAI9742458.1  2.4e-86  280.3
CAI9741923.1  2.6e-86  280.3
CAI9741925.1  2.6e-86  280.3
CAI9738115.1  2.6e-86  280.3
CAI9742377.1  3.8e-86  279.7
CAI9724107.1    4e-86  279.6
CAI9722148.1  4.8e-86  279.4
CAI9742017.1  5.8e-86  279.2
CAI9743649.1    6e-86  279.1
CAI9743942.1  7.4e-86  278.8
CAI9742681.1  1.2e-85  278.1
CAI9743420.1  1.3e-85  278.0
CAI9743717.1  2.2e-85  277.3
CAI9742076.1  2.7e-85  277.0
CAI9742881.1  2.9e-85  276.9
CAI9738625.1  3.4e-85  276.7
CAI9743723.1  3.7e-85  276.6
CAI9732315.1  3.9e-85  276.5
CAI9743142.1    4e-85  276.5
CAI9737495.1  4.3e-85  276.4
CAI9726022.1  4.7e-85  276.3
CAI9743419.1  4.9e-85  276.2
CAI9741935.1    5e-85  276.2
CAI9742369.1  1.1e-84  275.1
CAI9742470.1  1.5e-84  274.7
CAI9733353.1  1.6e-84  274.6
CAI9733352.1  1.6e-84  274.6
CAI9741765.1  1.8e-84  274.5
CAI9721803.1  2.4e-84  274.0
CAI9727226.1  3.6e-84  273.5
CAI9743864.1  3.7e-84  273.5
CAI9732777.1  3.9e-84  273.4
CAI9743586.1  5.2e-84  273.0
CAI9725505.1    6e-84  272.8
CAI9725090.1  6.5e-84  272.7
CAI9720565.1  7.4e-84  272.5
CAI9731716.1  1.1e-83  272.0
CAI9743871.1  1.2e-83  271.9
CAI9743566.1  1.4e-83  271.6
CAI9742466.1  1.7e-83  271.4
CAI9741955.1  1.9e-83  271.2
CAI9743802.1  1.9e-83  271.2
CAI9742707.1    2e-83  271.2
CAI9722136.1  2.1e-83  271.1
CAI9738239.1  2.4e-83  270.9
CAI9743888.1  2.5e-83  270.8
CAI9742467.1  2.8e-83  270.7
CAI9737528.1  5.2e-83  269.8
CAI9743841.1  5.7e-83  269.7
CAI9738122.1  7.7e-83  269.3
CAI9742077.1  8.1e-83  269.2
CAI9743656.1  8.7e-83  269.1
CAI9743824.1  8.8e-83  269.1
CAI9742722.1    1e-82  268.9
CAI9728658.1    1e-82  268.9
CAI9742474.1  1.1e-82  268.9
CAI9732313.1  1.1e-82  268.8
CAI9742453.1  1.2e-82  268.7
CAI9742378.1  1.4e-82  268.5
CAI9743932.1  1.4e-82  268.5
CAI9742107.1  1.7e-82  268.3
CAI9738326.1  1.7e-82  268.2
CAI9743887.1  1.7e-82  268.2
CAI9741952.1    2e-82  268.0
CAI9728227.1  3.7e-82  267.2
CAI9722446.1  4.5e-82  266.9
CAI9742731.1  7.2e-82  266.3
CAI9739835.1  7.4e-82  266.2
CAI9743707.1  9.5e-82  265.9
CAI9725409.1    1e-81  265.8
CAI9742712.1    1e-81  265.8
CAI9743990.1  1.1e-81  265.7
CAI9742386.1  1.3e-81  265.4
CAI9743994.1  1.3e-81  265.4
CAI9741960.1  1.4e-81  265.3
CAI9743923.1  1.4e-81  265.3
CAI9742576.1  1.6e-81  265.2
CAI9715971.1  1.8e-81  265.0
CAI9743676.1  1.8e-81  265.0
CAI9742873.1    2e-81  264.8
CAI9727934.1  2.2e-81  264.7
CAI9743546.1  2.9e-81  264.4
CAI9743803.1  4.5e-81  263.8
CAI9743718.1  4.9e-81  263.6
CAI9739836.1    5e-81  263.6
CAI9743151.1    6e-81  263.3
CAI9743798.1  6.4e-81  263.3
CAI9715663.1    7e-81  263.1
CAI9742624.1  7.6e-81  263.0
CAI9742519.1  8.8e-81  262.8
CAI9742577.1  9.9e-81  262.7
CAI9742075.1  1.1e-80  262.6
CAI9743138.1  1.2e-80  262.4
CAI9728219.1  1.4e-80  262.2
CAI9743769.1  1.5e-80  262.1
CAI9741768.1  1.6e-80  262.0
CAI9726412.1  1.7e-80  261.9
CAI9742486.1  1.7e-80  261.9
CAI9732790.1  1.9e-80  261.8
CAI9743421.1  2.3e-80  261.5
CAI9743691.1  2.7e-80  261.3
CAI9743839.1  3.1e-80  261.1
CAI9738207.1  3.8e-80  260.8
CAI9724388.1  4.1e-80  260.7
CAI9738355.1  4.1e-80  260.7
CAI9742282.1  4.4e-80  260.6
CAI9742079.1    7e-80  260.0
CAI9743806.1  7.1e-80  260.0
CAI9744225.1  7.9e-80  259.8
CAI9743955.1  8.2e-80  259.8
CAI9742539.1  9.6e-80  259.6
CAI9742429.1  1.2e-79  259.3
CAI9732911.1  1.4e-79  259.1
CAI9732191.1  1.4e-79  259.0
CAI9742512.1  1.4e-79  259.0
CAI9743934.1  1.7e-79  258.8
CAI9742686.1  1.7e-79  258.8
CAI9733382.1    2e-79  258.5
CAI9742379.1  2.5e-79  258.2
CAI9742479.1  2.8e-79  258.1
CAI9742682.1  3.2e-79  257.9
CAI9742157.1  3.3e-79  257.9
CAI9743086.1  3.5e-79  257.8
CAI9739821.1    4e-79  257.6
CAI9729200.1    4e-79  257.6
CAI9733286.1  4.1e-79  257.6
CAI9743129.1  4.1e-79  257.6
CAI9732308.1  4.2e-79  257.5
CAI9743090.1  4.7e-79  257.4
CAI9742438.1  5.7e-79  257.1
CAI9742071.1    6e-79  257.1
CAI9742465.1  6.4e-79  257.0
CAI9738120.1  7.5e-79  256.7
CAI9743739.1  8.7e-79  256.5
CAI9743095.1  8.8e-79  256.5
CAI9744220.1    1e-78  256.3
CAI9743692.1  1.2e-78  256.2
CAI9743595.1  1.2e-78  256.1
CAI9744083.1  1.2e-78  256.1
CAI9743625.1  1.3e-78  256.0
CAI9733521.1  1.5e-78  255.8
CAI9725758.1  1.6e-78  255.7
CAI9743645.1    2e-78  255.4
CAI9738292.1    2e-78  255.4
CAI9742680.1  2.1e-78  255.4
CAI9743849.1  2.6e-78  255.1
CAI9726042.1  2.7e-78  255.0
CAI9740265.1  3.3e-78  254.7
CAI9715972.1  4.4e-78  254.3
CAI9743705.1  5.3e-78  254.1
CAI9743950.1  6.6e-78  253.8
CAI9743788.1    7e-78  253.7
CAI9743578.1  7.6e-78  253.6
CAI9743738.1  9.2e-78  253.3
CAI9743659.1  9.3e-78  253.3
CAI9732764.1    1e-77  253.2
CAI9744209.1  1.2e-77  253.0
CAI9742506.1  1.4e-77  252.7
CAI9741927.1  1.6e-77  252.6
CAI9742373.1  1.7e-77  252.5
CAI9742427.1  1.7e-77  252.5
CAI9742392.1  2.1e-77  252.2
CAI9742516.1  2.2e-77  252.1
CAI9727228.1  2.4e-77  252.0
CAI9742158.1  2.9e-77  251.8
CAI9740254.1  3.2e-77  251.6
CAI9740253.1  3.3e-77  251.6
CAI9732945.1  3.4e-77  251.5
CAI9733365.1  3.5e-77  251.5
CAI9732522.1  4.5e-77  251.1
CAI9722149.1  4.8e-77  251.1
CAI9726023.1    5e-77  251.0
CAI9715067.1  5.4e-77  250.9
CAI9732726.1  5.4e-77  250.9
CAI9743961.1  8.2e-77  250.3
CAI9742674.1  8.3e-77  250.3
CAI9733254.1  8.5e-77  250.3
CAI9743892.1  9.1e-77  250.2
CAI9743130.1  1.1e-76  249.9
CAI9725806.1  1.1e-76  249.9
CAI9733338.1  1.2e-76  249.8
CAI9724112.1  1.6e-76  249.4
CAI9715068.1  1.7e-76  249.3
CAI9731722.1  1.9e-76  249.2
CAI9742382.1  2.2e-76  249.0
CAI9743851.1  2.4e-76  248.9
CAI9742613.1  2.5e-76  248.8
CAI9726024.1  2.5e-76  248.8
CAI9741984.1  2.8e-76  248.6
CAI9728651.1  2.9e-76  248.6
CAI9742705.1  3.3e-76  248.4
CAI9742733.1  3.6e-76  248.3
CAI9742452.1  4.2e-76  248.1
CAI9742428.1  5.8e-76  247.7
CAI9724640.1  7.1e-76  247.4
CAI9742478.1  7.8e-76  247.3
CAI9726564.1  8.4e-76  247.1
CAI9725803.1  9.1e-76  247.0
CAI9742729.1  1.2e-75  246.7
CAI9743660.1  1.4e-75  246.5
CAI9742451.1  1.4e-75  246.4
CAI9741705.1  1.6e-75  246.3
CAI9742114.1  1.7e-75  246.2
CAI9743726.1  1.8e-75  246.1
CAI9732217.1    2e-75  246.0
CAI9735697.1    2e-75  246.0
CAI9742284.1    2e-75  246.0
CAI9742676.1    2e-75  246.0
CAI9725545.1  2.3e-75  245.8
CAI9743685.1  2.4e-75  245.7
CAI9743886.1    3e-75  245.4
CAI9728649.1  3.3e-75  245.3
CAI9742480.1  3.3e-75  245.3
CAI9742530.1  3.3e-75  245.3
CAI9742368.1  3.5e-75  245.2
CAI9725342.1  3.6e-75  245.2
CAI9743632.1  3.7e-75  245.1
CAI9725802.1  3.8e-75  245.1
CAI9742645.1  4.2e-75  245.0
CAI9722139.1  4.4e-75  244.9
CAI9742156.1  4.4e-75  244.9
CAI9743905.1  4.7e-75  244.8
CAI9728650.1  5.3e-75  244.6
CAI9738323.1  6.2e-75  244.4
CAI9743569.1  6.3e-75  244.4
CAI9741990.1  6.4e-75  244.4
CAI9743734.1  6.5e-75  244.3
CAI9741855.1  7.3e-75  244.2
CAI9743936.1  8.2e-75  244.0
CAI9724869.1  1.1e-74  243.7
CAI9726816.1  1.1e-74  243.6
CAI9725502.1  1.2e-74  243.5
CAI9743185.1  1.4e-74  243.3
CAI9721806.1  1.5e-74  243.2
CAI9726214.1  1.8e-74  242.9
CAI9733378.1    2e-74  242.8
CAI9743859.1  2.3e-74  242.6
CAI9742118.1  2.3e-74  242.6
CAI9739844.1  2.9e-74  242.3
CAI9742372.1  3.2e-74  242.2
CAI9738356.1  3.2e-74  242.2
CAI9725553.1  3.3e-74  242.1
CAI9738352.1  3.4e-74  242.1
CAI9743869.1  3.8e-74  241.9
CAI9742515.1  4.4e-74  241.7
CAI9733341.1  4.9e-74  241.6
CAI9742689.1    5e-74  241.6
CAI9743906.1  6.6e-74  241.2
CAI9732320.1  6.7e-74  241.2
CAI9732322.1  6.7e-74  241.2
CAI9738297.1    9e-74  240.7
CAI9733354.1  9.7e-74  240.7
CAI9732324.1  1.2e-73  240.3
CAI9742608.1  1.3e-73  240.3
CAI9727938.1  1.3e-73  240.2
CAI9743639.1  1.6e-73  239.9
CAI9738012.1  1.6e-73  239.9
CAI9742488.1  1.7e-73  239.9
CAI9743650.1  1.8e-73  239.8
CAI9725549.1    2e-73  239.7
CAI9744278.1  2.1e-73  239.6
CAI9742102.1  2.4e-73  239.4
CAI9742285.1  2.5e-73  239.4
CAI9743544.1  2.6e-73  239.3
CAI9726664.1  2.8e-73  239.2
CAI9742171.1  3.2e-73  239.0
CAI9741778.1  3.3e-73  239.0
CAI9738126.1  3.5e-73  238.9
CAI9742068.1  3.5e-73  238.9
CAI9739840.1  3.6e-73  238.9
CAI9732307.1  3.8e-73  238.8
CAI9742402.1    4e-73  238.7
CAI9742426.1  4.2e-73  238.6
CAI9742409.1  4.3e-73  238.6
CAI9742514.1    5e-73  238.4
CAI9742172.1  5.1e-73  238.4
CAI9743907.1  5.4e-73  238.3
CAI9743689.1  5.7e-73  238.2
CAI9740255.1  6.8e-73  238.0
CAI9742487.1  6.9e-73  238.0
CAI9742616.1  7.9e-73  237.8
CAI9743856.1  8.1e-73  237.7
CAI9742103.1  8.2e-73  237.7
CAI9742347.1  9.9e-73  237.5
CAI9742405.1  1.2e-72  237.2
CAI9742684.1  1.6e-72  236.8
CAI9732995.1  1.7e-72  236.7
CAI9743773.1  1.7e-72  236.7
CAI9742152.1    2e-72  236.5
CAI9742504.1  3.1e-72  235.9
CAI9739842.1  3.3e-72  235.8
CAI9717265.1  3.6e-72  235.7
CAI9733406.1  3.7e-72  235.7
CAI9743951.1  3.8e-72  235.6
CAI9732224.1  5.9e-72  235.0
CAI9742417.1  6.4e-72  234.9
CAI9743735.1  7.2e-72  234.8
CAI9724871.1    1e-71  234.3
CAI9743860.1  1.2e-71  234.1
CAI9743577.1  1.3e-71  234.0
CAI9742170.1  1.3e-71  234.0
CAI9743529.1  1.3e-71  233.9
CAI9742085.1  1.3e-71  233.9
CAI9714938.1  1.4e-71  233.9
CAI9725520.1  1.6e-71  233.7
CAI9738330.1  1.7e-71  233.6
CAI9727023.1  2.3e-71  233.2
CAI9742934.1  3.6e-71  232.5
CAI9742155.1  3.7e-71  232.5
CAI9742699.1  3.7e-71  232.5
CAI9743944.1  3.8e-71  232.5
CAI9733379.1  3.8e-71  232.5
CAI9743694.1  4.2e-71  232.4
CAI9734061.1  5.3e-71  232.0
CAI9732349.1  5.5e-71  232.0
CAI9726021.1  5.6e-71  232.0
CAI9714757.1  5.9e-71  231.9
CAI9742367.1  6.4e-71  231.8
CAI9742421.1  7.5e-71  231.6
CAI9743867.1    8e-71  231.5
CAI9726410.1    8e-71  231.5
CAI9743908.1  8.3e-71  231.4
CAI9714759.1  8.7e-71  231.3
CAI9743709.1  1.2e-70  230.9
CAI9742441.1  1.3e-70  230.8
CAI9738324.1  1.3e-70  230.8
CAI9722141.1  1.5e-70  230.6
CAI9743099.1  1.5e-70  230.6
CAI9742567.1  1.7e-70  230.4
CAI9744323.1    2e-70  230.2
CAI9742039.1  2.1e-70  230.1
CAI9738311.1  2.2e-70  230.1
CAI9742067.1  2.3e-70  230.0
CAI9742353.1  2.4e-70  230.0
CAI9742425.1  2.6e-70  229.9
CAI9742654.1  2.7e-70  229.8
CAI9742010.1    3e-70  229.7
CAI9742001.1  3.3e-70  229.5
CAI9743668.1    4e-70  229.3
CAI9738327.1  5.8e-70  228.7
CAI9743972.1  6.7e-70  228.6
CAI9743646.1  6.8e-70  228.5
CAI9743637.1  7.3e-70  228.4
CAI9743978.1  7.9e-70  228.3
CAI9739824.1  8.1e-70  228.3
CAI9744208.1  8.6e-70  228.2
CAI9743140.1  1.2e-69  227.7
CAI9743749.1  1.6e-69  227.4
CAI9744127.1  1.7e-69  227.3
CAI9741994.1  1.8e-69  227.2
CAI9742159.1  1.9e-69  227.1

In [21]:
with open('smc_results.txt', 'r') as f:
    lines = f.readlines()
    line_count = len(lines)
    print(f"Number of lines: {line_count}")

Number of lines: 46

## Поиск нужных генов для деревьев

Были выбраны: DNMT1, TET3, EZH2, KMT2A(MILL1), BRD3, ADAR1, UHRF1, CHD1

In [ ]:
!head -20 /content/protein.faa

>CAI9714688.1 Hypothetical predicted protein [Octopus vulgaris]
MSYFGGSNNRLAESSVARNNANRLFDSQNNEKGGYNSRRLYYYTGSKLMIEWTNQHSCQHPNNNCELVLQYMCHDLIRDG
TSVKTIPTNTRKCKGGDCDRDFQYGMHENYTYYQTCAQRERNKGLFFADQKLKKDTAIYTRQNPDGTRRGYECPEERDYY
PYWHPSPWIDIAVMTNNVSRCSYYTQNSQNVKSKWSCNVTQPKNIVIPNNKEECETNGKIGVWTEYPAHAVAAPICREAQ
FSWDNYLGNGLNGKSNVFNWTIPETPGEHCVLRIRYNISTTDYDWWADHTLNPDKKGEPSKVNLSKEYPLNGKAKEQGYV
FKQNPVVKIFEDVDFDLRLAINTAQFGRIFQDRSHTFSIKKRPQDLKDAVIHNLNVRGKRGNIVQVYPAVEYDFVPNLLN
IATGDYIHFQWNGSNTNNKNFEGNGIAGTDRNNVVMLAESDFSEKSKNVPYKLLSFGHYGTNYPTKITNSSFLELSKDDI
TKLAHLGNTKGNDPLLNKADTYFDLGPRKITKQGKYHFMCTRNNDFSNRDQKGKIVVRDFPIVYKMIGLQGGTIAIQSKA
ALYIPPNTLDKLLSLQMASWRSDEGNDWLKEKRKRLPIVEGFASDFILLLPVENFAAESPVRLSINLTDTDSDIISVYRT
GDKEYGVWQRIVTEIENGVAHSDIKQGGVYIAVKEKSLDMITNQEVIS
>CAI9714689.1 Hypothetical predicted protein [Octopus vulgaris]
MSYFGGSNNRLAESSVARNNANRLFDSQNNEKGGYNSRRLYYYTGSKLMIEWTNQHSCQHPNNNCELVLQYMCHDLIRDG
TSVKTIPTNTRKCKGGDCDRDFQYGMHENYTYYQTCAQRERNKGLFFADQKLKKDTAIYTRQNPDGTRRGYECPEERDYY
PYWHPSPWIDIAVMTNNVSRCSYYTQNSQNVKSKWSCNVTQPKNIVIPNNKEECETNGKIGVWTEYPAHAVAAPICREAQ
FSWDNYLGNGLNGKSNVFNWTIPETPGEHCVLRIRYNISTTDYDWWADHTLNPDKKGEPSKVNLSKEYPLNGKAKEQGYV
FKQNPVVKIFEDVDFDLRLAINTAQFGRIFQDRSHTFSIKKRPQDLKDAVIHNLNVRGKRGNIVQVYPAVEYDFVPNLLN
IATGDYIHFQWNGSNTNNKNFEGNGIAGTDRNNVVMLAESDFSEKSKNVPYKLLSFGHYGTNYPTKITNSSFLELSKDDI
TKLAHLGNTKGNDPLLNKADTYFDLGPRKITKQGKYHFMCTRNNDFSNRDQKGKIVVRDFPIVYKMIGLQGGTIAIQSKA
ALYIPPNTLDKLLSLQMASWRSDEGNDWLKEKRKRLPIVEGFASDFILLLPVENFAAESPVRLSINLTDTDSDIISVYRT
GDKEYGVWQRIVTEIENGVAHSDIKQGGVYIAVKEKSLDMITNVIIIVIMFTIGLIAVLVYFYYKKSHPWLYAKNA

In [ ]:
target_genes = ['DNMT1', 'TET3', 'EZH2', 'KMT2A', 'BRD3', 'ADAR1', 'UHRF1', 'CHD1']

```
DNMT1 - DNA (cytosine-5)-methyltransferase 1-like - CAI9739711.1

TET3 - Methylcytosine dioxygenase TET1 - CAI9725251.1

EZH2 - histone-lysine N-methyltransferase EZH2-like - CAI9716361.1

KMT2A - histone-lysine N-methyltransferase 2A isoform X2 - CAI9737782.1

BRD3 - bromodomain-containing protein 3 isoform X4 - CAI9717820.1

ADAR1 - double-stranded RNA-specific adenosine deaminase-like... - CAI9722839.1

UHRF1 - E3 ubiquitin-protein ligase UHRF1-like - CAI9723816.1

CHD1 - не найден в аннотации
```

In [ ]:
ids = [ 'CAI9739711.1', 'CAI9725251.1' , 'CAI9716361.1', 'CAI9737782.1', 'CAI9717820.1', 'CAI9722839.1', 'CAI9723816.1']

In [ ]:
!pip install biopython

Collecting biopython
  Downloading biopython-1.87-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from biopython) (2.0.2)
Downloading biopython-1.87-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 89.4 MB/s eta 0:00:00
Installing collected packages: biopython
Successfully installed biopython-1.87

In [ ]:
from Bio import SeqIO

ids_to_extract = ['CAI9739711.1', 'CAI9725251.1', 'CAI9716361.1',
                  'CAI9737782.1', 'CAI9717820.1', 'CAI9722839.1', 'CAI9723816.1']


input_file = "/content/protein.faa"
output_file = "octopus_vulgaris_8genes.faa"

# Извлекаем последовательности
extracted_records = []
with open(input_file, "r") as handle:
    for record in SeqIO.parse(handle, "fasta"):
        if record.id in ids_to_extract:
            extracted_records.append(record)
            print(f"Найден: {record.id}")

# Сохраняем в файл
SeqIO.write(extracted_records, output_file, "fasta")

print(f"\nИзвлечено {len(extracted_records)} из {len(ids_to_extract)} последовательностей")
print(f"Сохранено в {output_file}")

Найден: CAI9716361.1
Найден: CAI9717820.1
Найден: CAI9722839.1
Найден: CAI9723816.1
Найден: CAI9725251.1
Найден: CAI9737782.1
Найден: CAI9739711.1

Извлечено 7 из 7 последовательностей
Сохранено в octopus_vulgaris_8genes.faa

## Поиск генов, в промоторах которых есть zdna

In [42]:
# Берём гены из аннотации
genes = annotations_df[annotations_df['type'] == 'gene'].copy()

def get_gene_name(attrs):
    for part in attrs.split(';'):
        if part.startswith('Name='):
            return part.split('=')[1]
    return None

genes['gene_name'] = genes['attributes'].apply(get_gene_name)
genes['gene_id'] = genes['attributes'].str.extract(r'ID=([^;]+)')[0]

# Строим промоторы (1000 bp выше TSS)
promoters_list = []
for _, gene in genes.iterrows():
    if gene['strand'] == '+':
        start = max(0, gene['start_half'] - 1000)
        end = gene['start_half']
    else:
        start = gene['end_half']
        end = gene['end_half'] + 1000
    promoters_list.append({
        'seqid': gene['seqid'],
        'start': start,
        'end': end,
        'gene_id': gene['gene_id'],
        'gene_name': gene['gene_name']
    })
promoters_df = pd.DataFrame(promoters_list)

In [43]:
from collections import defaultdict

genes_with_zdna = set()

for _, prom in promoters_df.iterrows():
    seqid = prom['seqid']
    if seqid not in zdnabert_trees:
        continue
    overlaps = zdnabert_trees[seqid].overlap(prom['start'], prom['end'])
    if overlaps:
        genes_with_zdna.add((prom['gene_id'], prom['gene_name']))

print(f"Найдено {len(genes_with_zdna)} генов с Z‑ДНК в промоторах")

Найдено 1937 генов с Z‑ДНК в промоторах

In [44]:
output_file = 'genes_with_zdna_in_promoters_vulgaris.txt'
with open(output_file, 'w') as f:
    f.write("gene_id\tgene_name\n")
    for gid, gname in sorted(genes_with_zdna):
        f.write(f"{gid}\t{gname if gname else 'NA'}\n")

print(f"Список сохранён в {output_file}")

Список сохранён в genes_with_zdna_in_promoters_vulgaris.txt

### Выравнивание, чтобы получить id

In [45]:
# Скачиваем протеом
!wget -O bimac_protein.faa.gz https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/001/194/135/GCF_001194135.2_ASM119413v2/GCF_001194135.2_ASM119413v2_protein.faa.gz
!gunzip -f bimac_protein.faa.gz

# Скачиваем GFF
!wget -O bimac_genomic.gff.gz https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/001/194/135/GCF_001194135.2_ASM119413v2/GCF_001194135.2_ASM119413v2_genomic.gff.gz
!gunzip -f bimac_genomic.gff.gz

# Создаём BLAST-базу
!makeblastdb -in bimac_protein.faa -dbtype prot -out bimac_db

--2026-06-10 18:13:15--  https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/001/194/135/GCF_001194135.2_ASM119413v2/GCF_001194135.2_ASM119413v2_protein.faa.gz
Resolving ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)... 130.14.250.31, 130.14.250.7, 2607:f220:41e:250::12, ...
Connecting to ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)|130.14.250.31|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6741705 (6.4M) [application/x-gzip]
Saving to: ‘bimac_protein.faa.gz’

bimac_protein.faa.g 100%[===================>]   6.43M  12.5MB/s    in 0.5s

2026-06-10 18:13:16 (12.5 MB/s) - ‘bimac_protein.faa.gz’ saved [6741705/6741705]

--2026-06-10 18:13:16--  https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/001/194/135/GCF_001194135.2_ASM119413v2/GCF_001194135.2_ASM119413v2_genomic.gff.gz
Resolving ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)... 130.14.250.31, 130.14.250.7, 2607:f220:41e:250::12, ...
Connecting to ftp.ncbi.nlm.nih.gov (ftp.ncbi.nlm.nih.gov)|130.14.250.31|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13109005 (13M) [application/x-gzip]
Saving to: ‘bimac_genomic.gff.gz’

bimac_genomic.gff.g 100%[===================>]  12.50M  21.7MB/s    in 0.6s

2026-06-10 18:13:17 (21.7 MB/s) - ‘bimac_genomic.gff.gz’ saved [13109005/13109005]

/bin/bash: line 1: makeblastdb: command not found

In [46]:
!apt-get install ncbi-blast+ -y

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  ncbi-data
The following NEW packages will be installed:
  ncbi-blast+ ncbi-data
0 upgraded, 2 newly installed, 0 to remove and 53 not upgraded.
Need to get 15.8 MB of archives.
After this operation, 71.8 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 ncbi-data all 6.1.20170106+dfsg1-9 [3,519 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/universe amd64 ncbi-blast+ amd64 2.12.0+ds-3build1 [12.3 MB]
Fetched 15.8 MB in 0s (42.8 MB/s)
Selecting previously unselected package ncbi-data.
(Reading database ... 122403 files and directories currently installed.)
Preparing to unpack .../ncbi-data_6.1.20170106+dfsg1-9_all.deb ...
Unpacking ncbi-data (6.1.20170106+dfsg1-9) ...
Selecting previously unselected package ncbi-blast+.
Preparing to unpack .../ncbi-blast+_2.12.0+ds-3build1_amd64.deb ...
Unpacking ncbi-blast+ (2.12.0+ds-3build1) ...
Setting up ncbi-data (6.1.20170106+dfsg1-9) ...
Setting up ncbi-blast+ (2.12.0+ds-3build1) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...

In [47]:
# Создаём BLAST-базу
!makeblastdb -in bimac_protein.faa -dbtype prot -out bimac_db

Building a new DB, current time: 06/10/2026 18:14:16
New DB name:   /content/bimac_db
New DB title:  bimac_protein.faa
Sequence type: Protein
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 29037 sequences in 0.710032 seconds.

In [49]:
import pandas as pd

# Загружаем список генов
genes_df = pd.read_csv('genes_with_zdna_in_promoters_vulgaris.txt', sep='\t')
# genes_df должен содержать колонку 'gene_id'
print(genes_df.head())

                gene_id        gene_name
0  gene-OCTVUL_1B000032  OCTVUL_1B000032
1  gene-OCTVUL_1B000133  OCTVUL_1B000133
2  gene-OCTVUL_1B000146  OCTVUL_1B000146
3  gene-OCTVUL_1B000149  OCTVUL_1B000149
4  gene-OCTVUL_1B000167  OCTVUL_1B000167

In [61]:
from Bio import SeqIO

# Загружаем все белки O. vulgaris
vulgaris_proteins = {rec.id: rec for rec in SeqIO.parse("protein.faa", "fasta")}

# Проверим, что protein_id не пустые
genes_df = genes_df.dropna(subset=['protein_id'])

# Создаём FASTA-файл
with open("selected_genes_vulgaris.faa", "w") as out:
    for idx, row in genes_df.iterrows():
        prot_id = row['protein_id']
        if prot_id in vulgaris_proteins:
            SeqIO.write(vulgaris_proteins[prot_id], out, "fasta")
        else:
            print(f"Предупреждение: белок {prot_id} не найден в protein.faa")

# Проверяем
!grep -c ">" selected_genes_vulgaris.faa

1461

In [62]:
# BLAST
!blastp -query selected_genes_vulgaris.faa -db bimac_db -outfmt "6 qseqid sseqid evalue bitscore" -evalue 1e-5 -max_target_seqs 1 > blast_selected.txt

# Посмотрим результаты
!head -10 blast_selected.txt

Warning: [blastp] Examining 5 or more matches is recommended
CAI9727365.1	XP_052825850.1	0.0	3103
CAI9730386.1	XP_014784426.1	0.0	543
CAI9740886.1	XP_052832539.1	0.0	518
CAI9720533.1	XP_014782737.1	0.0	687
CAI9739051.1	XP_014770458.1	0.0	546
CAI9743609.1	XP_014782088.1	3.00e-86	248
CAI9727461.1	XP_052826647.1	0.0	612
CAI9731707.1	XP_014780681.1	4.28e-79	229
CAI9735086.1	XP_014785257.1	0.0	715
CAI9741546.1	XP_052832871.1	0.0	1399

In [63]:
import pandas as pd

blast_df = pd.read_csv('blast_selected.txt', sep='\t', names=['query_prot', 'hit_id_bimac', 'evalue', 'bitscore'])

# У нас есть словарь prot_id -> gene_id (из genes_df)
prot_to_gene = dict(zip(genes_df['protein_id'], genes_df['gene_id']))
blast_df['gene_id'] = blast_df['query_prot'].map(prot_to_gene)

print(blast_df[['gene_id', 'hit_id_bimac', 'evalue']].head())

                gene_id    hit_id_bimac  evalue
0  gene-OCTVUL_1B000032  XP_052825850.1     0.0
1  gene-OCTVUL_1B000133  XP_014784426.1     0.0
2  gene-OCTVUL_1B000146  XP_052832539.1     0.0
3  gene-OCTVUL_1B000149  XP_014782737.1     0.0
4  gene-OCTVUL_1B000167  XP_014770458.1     0.0

In [68]:
import re

prot_to_gene = {}
with open("bimac_genomic.gff", "r") as f:
    for line in f:
        if line.startswith("#"):
            continue
        parts = line.strip().split("\t")
        if len(parts) < 9 or parts[2] != "CDS":
            continue
        attrs = parts[8]
        # Ищем protein_id=XP_...
        p_match = re.search(r"protein_id=([^;]+)", attrs)
        if not p_match:
            continue
        prot_id = p_match.group(1)
        # Ищем gene=LOC... (или просто gene=...)
        g_match = re.search(r"gene=([^;]+)", attrs)
        if g_match:
            gene_id = g_match.group(1)   # например, LOC106877895
            prot_to_gene[prot_id] = gene_id

print(f"Найдено соответствий: {len(prot_to_gene)}")
# Применяем к вашему blast_df
blast_df['bimac_gene_id'] = blast_df['hit_id_bimac'].map(prot_to_gene)
print(blast_df[['gene_id', 'hit_id_bimac', 'bimac_gene_id']].head(10))

Найдено соответствий: 29037
                gene_id    hit_id_bimac bimac_gene_id
0  gene-OCTVUL_1B000032  XP_052825850.1  LOC106872539
1  gene-OCTVUL_1B000133  XP_014784426.1  LOC106879399
2  gene-OCTVUL_1B000146  XP_052832539.1  LOC106880683
3  gene-OCTVUL_1B000149  XP_014782737.1  LOC106878131
4  gene-OCTVUL_1B000167  XP_014770458.1  LOC106869296
5  gene-OCTVUL_1B000186  XP_014782088.1  LOC106877656
6  gene-OCTVUL_1B000199  XP_052826647.1  LOC106868077
7  gene-OCTVUL_1B000205  XP_014780681.1  LOC106876561
8  gene-OCTVUL_1B000222  XP_014785257.1  LOC106879992
9  gene-OCTVUL_1B000229  XP_052832871.1  LOC106883689

In [69]:
blast_df.to_csv('orthologs_bimac_with_genes.csv', index=False)

In [72]:
blast_df.head()

,query_prot,hit_id_bimac,evalue,bitscore,gene_id,bimac_gene_id
0,CAI9727365.1,XP_052825850.1,0.0,3103.0,gene-OCTVUL_1B000032,LOC106872539
1,CAI9730386.1,XP_014784426.1,0.0,543.0,gene-OCTVUL_1B000133,LOC106879399
2,CAI9740886.1,XP_052832539.1,0.0,518.0,gene-OCTVUL_1B000146,LOC106880683
3,CAI9720533.1,XP_014782737.1,0.0,687.0,gene-OCTVUL_1B000149,LOC106878131
4,CAI9739051.1,XP_014770458.1,0.0,546.0,gene-OCTVUL_1B000167,LOC106869296

In [70]:
# Отобрать только столбец bimac_gene_id
bimac_gene_ids = blast_df['bimac_gene_id']

# Посмотреть первые 10
print(bimac_gene_ids.head(10))

# Если нужен список уникальных значений (без повторов и NaN)
unique_ids = bimac_gene_ids.dropna().unique().tolist()
print(unique_ids)

# Сохранить в файл
bimac_gene_ids.to_csv('bimac_gene_ids.csv', index=False)

0    LOC106872539
1    LOC106879399
2    LOC106880683
3    LOC106878131
4    LOC106869296
5    LOC106877656
6    LOC106868077
7    LOC106876561
8    LOC106879992
9    LOC106883689
Name: bimac_gene_id, dtype: object
['LOC106872539', 'LOC106879399', 'LOC106880683', 'LOC106878131', 'LOC106869296', 'LOC106877656', 'LOC106868077', 'LOC106876561', 'LOC106879992', 'LOC106883689', 'LOC106877993', 'LOC106878664', 'LOC106881726', 'LOC106877159', 'LOC106874404', 'LOC106869381', 'LOC106872175', 'LOC106876926', 'LOC106873655', 'LOC106878652', 'LOC106873348', 'LOC106879048', 'LOC106883047', 'LOC106883356', 'LOC106870865', 'LOC106876012', 'LOC106882721', 'LOC106871773', 'LOC106882507', 'LOC106870659', 'LOC106876142', 'LOC106867951', 'LOC106870188', 'LOC106872141', 'LOC106874624', 'LOC128251004', 'LOC106874631', 'LOC106877879', 'LOC106867940', 'LOC106878163', 'LOC106880711', 'LOC106882876', 'LOC128249929', 'LOC106882869', 'LOC106872865', 'LOC106874875', 'LOC106875090', 'LOC106872771', 'LOC106869609', 'LOC106867467', 'LOC106868761', 'LOC106872645', 'LOC106882982', 'LOC106878161', 'LOC106867103', 'LOC106879459', 'LOC106868847', 'LOC128247069', 'LOC106883780', 'LOC106884083', 'LOC106882344', 'LOC106871668', 'LOC106875968', 'LOC106881860', 'LOC106869040', 'LOC106882896', 'LOC106877583', 'LOC106878883', 'LOC106877533', 'LOC106871661', 'LOC128251294', 'LOC106882314', 'LOC106876298', 'LOC106869058', 'LOC106870154', 'LOC106873977', 'LOC106880796', 'LOC106873996', 'LOC106879858', 'LOC106879726', 'LOC106879136', 'LOC106867192', 'LOC106874145', 'LOC106873798', 'LOC106884407', 'LOC106884262', 'LOC106867189', 'LOC106874194', 'LOC106880387', 'LOC106881733', 'LOC106868985', 'LOC106870582', 'LOC106869069', 'LOC106869879', 'LOC106879312', 'LOC106884008', 'LOC106867817', 'LOC106881224', 'LOC106879707', 'LOC106867662', 'LOC106878710', 'LOC106867546', 'LOC106880935', 'LOC106878278', 'LOC106882576', 'LOC106882968', 'LOC106873112', 'LOC106876546', 'LOC106868050', 'LOC106875884', 'LOC106877766', 'LOC128251527', 'LOC128251039', 'LOC106869506', 'LOC106878457', 'LOC106881314', 'LOC106871417', 'LOC106875849', 'LOC106869253', 'LOC106880078', 'LOC106884133', 'LOC106873831', 'LOC106879053', 'LOC106881643', 'LOC106877990', 'LOC106869229', 'LOC106871260', 'LOC106876014', 'LOC106882202', 'LOC106881472', 'LOC106872293', 'LOC106868703', 'LOC128250031', 'LOC106870470', 'LOC106882767', 'LOC106883887', 'LOC106868648', 'LOC106868208', 'LOC106873542', 'LOC106879976', 'LOC106873941', 'LOC106868928', 'LOC106873641', 'LOC106874533', 'LOC106877037', 'LOC106868081', 'LOC106883581', 'LOC106869320', 'LOC106884063', 'LOC128248504', 'LOC106868880', 'LOC106870446', 'LOC106868461', 'LOC106872270', 'LOC106875854', 'LOC106868862', 'LOC106883928', 'LOC106881085', 'LOC106879728', 'LOC106880590', 'LOC106879397', 'LOC106879572', 'LOC106872275', 'LOC106881952', 'LOC106879601', 'LOC106877080', 'LOC106877785', 'LOC106870605', 'LOC106883628', 'LOC106882174', 'LOC106867675', 'LOC106881483', 'LOC106882489', 'LOC106867428', 'LOC106868093', 'LOC106879788', 'LOC106875312', 'LOC106873617', 'LOC106877891', 'LOC106881039', 'LOC106879860', 'LOC106876017', 'LOC106873715', 'LOC106882761', 'LOC106871651', 'LOC106870575', 'LOC106879642', 'LOC106867861', 'LOC106873969', 'LOC106883595', 'LOC106881109', 'LOC106872420', 'LOC106879021', 'LOC106882799', 'LOC106874949', 'LOC106876724', 'LOC106872237', 'LOC106869854', 'LOC106882236', 'LOC128251150', 'LOC106879885', 'LOC106881786', 'LOC106869196', 'LOC106869194', 'LOC106879111', 'LOC106877158', 'LOC106877457', 'LOC106881230', 'LOC106878782', 'LOC106873492', 'LOC106881027', 'LOC106881135', 'LOC106879267', 'LOC106879182', 'LOC106877664', 'LOC106875564', 'LOC106871506', 'LOC128249674', 'LOC128250821', 'LOC106867276', 'LOC106869702', 'LOC106883803', 'LOC128246989', 'LOC106876496', 'LOC106875173', 'LOC106872709', 'LOC106875053', 'LOC106867391', 'LOC106883914', 'LOC106876990', 'LOC106874785', 'LOC106880928', 'LOC106876391', 'LOC106878138', 'LOC106877543', 'LOC106873845', 'LOC106872942', 'LOC106873884', 'LOC106869287', 'LOC106869624', 'LOC106878386', 'LOC106871536', 'LOC106876411', 'LOC128249616', 'LOC106880561', 'LOC106879805', 'LOC128250104', 'LOC106882622', 'LOC106880265', 'LOC106870416', 'LOC106879500', 'LOC106877363', 'LOC106876467', 'LOC106881982', 'LOC106867738', 'LOC106871364', 'LOC106869399', 'LOC106874907', 'LOC106867229', 'LOC106869476', 'LOC106882098', 'LOC106873062', 'LOC106881178', 'LOC106880025', 'LOC106873244', 'LOC106878475', 'LOC106882904', 'LOC106880175', 'LOC106874436', 'LOC106884279', 'LOC106882791', 'LOC106879393', 'LOC106875343', 'LOC106873760', 'LOC106868557', 'LOC106870889', 'LOC106874308', 'LOC106870617', 'LOC106883856', 'LOC106869820', 'LOC106883505', 'LOC106883972', 'LOC106875480', 'LOC106869730', 'LOC106872105', 'LOC106880798', 'LOC106875982', 'LOC106884177', 'LOC106869620', 'LOC106870815', 'LOC106881079', 'LOC106868425', 'LOC106880002', 'LOC106870314', 'LOC106877738', 'LOC106881480', 'LOC106871654', 'LOC106875972', 'LOC128248161', 'LOC106871265', 'LOC106869346', 'LOC106867255', 'LOC128251091', 'LOC106868652', 'LOC106869784', 'LOC106877582', 'LOC106874162', 'LOC106881681', 'LOC106868262', 'LOC106883345', 'LOC106869258', 'LOC106869074', 'LOC106871287', 'LOC106869455', 'LOC106868011', 'LOC106877170', 'LOC106873317', 'LOC106871278', 'LOC106868786', 'LOC106870708', 'LOC106871374', 'LOC106876350', 'LOC106876839', 'LOC106872046', 'LOC106883257', 'LOC106881841', 'LOC106875453', 'LOC106877925', 'LOC106869923', 'LOC106872515', 'LOC106873585', 'LOC106867483', 'LOC106875633', 'LOC106875059', 'LOC106870145', 'LOC106880030', 'LOC106870024', 'LOC106882491', 'LOC106876289', 'LOC128248913', 'LOC106879895', 'LOC106877131', 'LOC106878159', 'LOC106882336', 'LOC106882765', 'LOC106883095', 'LOC106880397', 'LOC106883351', 'LOC106875548', 'LOC106867556', 'LOC106879977', 'LOC106879874', 'LOC106880861', 'LOC106873875', 'LOC106877434', 'LOC106881774', 'LOC106877362', 'LOC106870257', 'LOC106874575', 'LOC106880594', 'LOC106869102', 'LOC106871573', 'LOC106868971', 'LOC106872147', 'LOC106878727', 'LOC106872296', 'LOC106867510', 'LOC106881296', 'LOC106884339', 'LOC106883006', 'LOC128251119', 'LOC106868777', 'LOC106878008', 'LOC106878005', 'LOC106883674', 'LOC106883309', 'LOC106870540', 'LOC106879368', 'LOC106867808', 'LOC106883032', 'LOC106871942', 'LOC106872072', 'LOC106878624', 'LOC106869537', 'LOC106870252', 'LOC106872170', 'LOC106884110', 'LOC106874692', 'LOC106876245', 'LOC106882638', 'LOC106876383', 'LOC106884187', 'LOC106878611', 'LOC106877914', 'LOC106881387', 'LOC106871398', 'LOC106877597', 'LOC106872700', 'LOC106867792', 'LOC106881001', 'LOC106871043', 'LOC106872994', 'LOC106880396', 'LOC106875618', 'LOC106875765', 'LOC106879014', 'LOC106880510', 'LOC106881743', 'LOC106868984', 'LOC128248671', 'LOC106881116', 'LOC106881590', 'LOC106870608', 'LOC106871120', 'LOC106876547', 'LOC106868940', 'LOC106882841', 'LOC106869169', 'LOC106867824', 'LOC106875497', 'LOC106875455', 'LOC128251177', 'LOC106878784', 'LOC106867091', 'LOC106877010', 'LOC106868244', 'LOC106874343', 'LOC106867066', 'LOC106876551', 'LOC106869415', 'LOC106871202', 'LOC106872689', 'LOC106869966', 'LOC106880962', 'LOC106882472', 'LOC106882059', 'LOC106869435', 'LOC106868222', 'LOC106873221', 'LOC106870169', 'LOC106879009', 'LOC106878393', 'LOC106876559', 'LOC106880221', 'LOC106870123', 'LOC128251169', 'LOC106877462', 'LOC106884266', 'LOC106882909', 'LOC106871415', 'LOC106882377', 'LOC106881289', 'LOC106874098', 'LOC106873855', 'LOC106882916', 'LOC106875646', 'LOC106880778', 'LOC106879743', 'LOC106870998', 'LOC106880453', 'LOC106881890', 'LOC106872498', 'LOC106880782', 'LOC128251480', 'LOC106870019', 'LOC106880139', 'LOC106868332', 'LOC106873006', 'LOC106881277', 'LOC106879469', 'LOC106867670', 'LOC106874360', 'LOC106874263', 'LOC106874908', 'LOC106880647', 'LOC106874185', 'LOC106872911', 'LOC106868082', 'LOC106877155', 'LOC106872402', 'LOC106879715', 'LOC106882031', 'LOC106879251', 'LOC106882725', 'LOC106872257', 'LOC106872091', 'LOC106874725', 'LOC106878135', 'LOC106879461', 'LOC106876681', 'LOC106872328', 'LOC106875349', 'LOC106872822', 'LOC106884475', 'LOC106873361', 'LOC106882018', 'LOC106874161', 'LOC106869158', 'LOC106867800', 'LOC106869250', 'LOC106868420', 'LOC106877920', 'LOC106882616', 'LOC106881589', 'LOC106867776', 'LOC106878702', 'LOC106870864', 'LOC106870949', 'LOC106873611', 'LOC106879952', 'LOC106870290', 'LOC106880595', 'LOC106881899', 'LOC106878311', 'LOC106875291', 'LOC106873627', 'LOC106883023', 'LOC106879710', 'LOC106870271', 'LOC106882999', 'LOC106869088', 'LOC106883256', 'LOC106879396', 'LOC106879631', 'LOC106872834', 'LOC106881659', 'LOC106878993', 'LOC106872414', 'LOC128249689', 'LOC106870181', 'LOC106876862', 'LOC106873774', 'LOC106874578', 'LOC106876943', 'LOC106880012', 'LOC106869911', 'LOC106875617', 'LOC106881197', 'LOC106874800', 'LOC106875206', 'LOC106872804', 'LOC106875500', 'LOC106876528', 'LOC106878280', 'LOC106876817', 'LOC106870839', 'LOC106875588', 'LOC106872599', 'LOC106872712', 'LOC106883161', 'LOC106884335', 'LOC106877085', 'LOC106877554', 'LOC106873291', 'LOC106868616', 'LOC106875601', 'LOC106877708', 'LOC106870507', 'LOC106875160', 'LOC106868753', 'LOC106877417', 'LOC106876588', 'LOC106867900', 'LOC106881531', 'LOC106881220', 'LOC106869382', 'LOC106873566', 'LOC106882289', 'LOC106868943', 'LOC106877138', 'LOC106884484', 'LOC106878916', 'LOC106872561', 'LOC106870081', 'LOC106874780', 'LOC106871867', 'LOC106875540', 'LOC106876454', 'LOC106879793', 'LOC106874447', 'LOC106876443', 'LOC106870967', 'LOC106876212', 'LOC106871505', 'LOC106877881', 'LOC106867621', 'LOC106884069', 'LOC106877967', 'LOC106867307', 'LOC106875403', 'LOC106878243', 'LOC106868281', 'LOC106871235', 'LOC106881479', 'LOC128250604', 'LOC106876417', 'LOC106875066', 'LOC106872786', 'LOC106880140', 'LOC106876626', 'LOC106868162', 'LOC106876047', 'LOC106873729', 'LOC106883571', 'LOC106869970', 'LOC106877880', 'LOC106877168', 'LOC106869709', 'LOC106878307', 'LOC106875264', 'LOC106879046', 'LOC106869013', 'LOC128248727', 'LOC106877222', 'LOC106878936', 'LOC106876915', 'LOC106882705', 'LOC106881805', 'LOC106874382', 'LOC106880702', 'LOC106880042', 'LOC106881424', 'LOC106878522', 'LOC106880774', 'LOC106874801', 'LOC106868586', 'LOC106873679', 'LOC106882977', 'LOC106878456', 'LOC106877556', 'LOC106873862', 'LOC106873293', 'LOC106869141', 'LOC106880625', 'LOC106871677', 'LOC106874479', 'LOC106875802', 'LOC106878297', 'LOC106869242', 'LOC106880011', 'LOC106868484', 'LOC106869061', 'LOC106884298', 'LOC106877327', 'LOC106872327', 'LOC106877557', 'LOC106875112', 'LOC106877445', 'LOC106880852', 'LOC106874616', 'LOC106873635', 'LOC106881686', 'LOC106870469', 'LOC106869737', 'LOC106877983', 'LOC106875097', 'LOC106871337', 'LOC106877380', 'LOC106880937', 'LOC106877088', 'LOC106873283', 'LOC106878899', 'LOC106880886', 'LOC106884053', 'LOC106876088', 'LOC106873050', 'LOC106871147', 'LOC106872608', 'LOC106880333', 'LOC106879751', 'LOC106868968', 'LOC106872191', 'LOC106877590', 'LOC106871930', 'LOC106869478', 'LOC106883137', 'LOC106884362', 'LOC106874200', 'LOC106882577', 'LOC106873083', 'LOC106880240', 'LOC106879237', 'LOC106872823', 'LOC106883201', 'LOC106881492', 'LOC106870134', 'LOC128247876', 'LOC106883424', 'LOC106869555', 'LOC106876076', 'LOC106869640', 'LOC106876066', 'LOC106875024', 'LOC106869868', 'LOC106875627', 'LOC106871007', 'LOC106867254', 'LOC128250770', 'LOC106875003', 'LOC106871546', 'LOC106883545', 'LOC106879116', 'LOC106870980', 'LOC106879478', 'LOC106879987', 'LOC106874196', 'LOC106883615', 'LOC106881069', 'LOC106869718', 'LOC106875011', 'LOC106881258', 'LOC106877655', 'LOC106869712', 'LOC106875673', 'LOC106880379', 'LOC106876414', 'LOC106868287', 'LOC106869769', 'LOC106868019', 'LOC106880031', 'LOC106884289', 'LOC106883781', 'LOC106870286', 'LOC106877824', 'LOC106874787', 'LOC106877562', 'LOC106874806', 'LOC106884271', 'LOC106869467', 'LOC106882232', 'LOC106876502', 'LOC128247289', 'LOC106882831', 'LOC106874402', 'LOC106875851', 'LOC106870569', 'LOC106868178', 'LOC106876495', 'LOC106875566', 'LOC106882146', 'LOC106869221', 'LOC106883668', 'LOC106879837', 'LOC106871502', 'LOC106877826', 'LOC106882122', 'LOC106882290', 'LOC106881607', 'LOC106878901', 'LOC106880015', 'LOC106868712', 'LOC106883957', 'LOC106876549', 'LOC106877125', 'LOC106877432', 'LOC106870351', 'LOC106869898', 'LOC106877419', 'LOC106871787', 'LOC106868937', 'LOC106878785', 'LOC106870143', 'LOC106867517', 'LOC106871490', 'LOC106878219', 'LOC106880763', 'LOC106880388', 'LOC106873025', 'LOC106873964', 'LOC106881814', 'LOC106871854', 'LOC106884481', 'LOC106868754', 'LOC106882020', 'LOC106875394', 'LOC106880803', 'LOC106872213', 'LOC106884467', 'LOC106880225', 'LOC106879828', 'LOC106869776', 'LOC106877021', 'LOC106867794', 'LOC106869716', 'LOC106877796', 'LOC106880341', 'LOC106869520', 'LOC106882071', 'LOC106884080', 'LOC106881034', 'LOC106869385', 'LOC106868555', 'LOC128249815', 'LOC106873933', 'LOC106874142', 'LOC106869746', 'LOC106872245', 'LOC106878959', 'LOC106875674', 'LOC106880724', 'LOC106870324', 'LOC106877357', 'LOC106875550', 'LOC106867429', 'LOC106873512', 'LOC106868022', 'LOC106875611', 'LOC106882317', 'LOC106877366', 'LOC106872277', 'LOC106876944', 'LOC106868389', 'LOC106868047', 'LOC106872625', 'LOC106879732', 'LOC106877541', 'LOC106868907', 'LOC106871118', 'LOC106870245', 'LOC106882154', 'LOC106868726', 'LOC106872249', 'LOC106876371', 'LOC106878778', 'LOC106877474', 'LOC106876898', 'LOC106877263', 'LOC106878925', 'LOC106869484', 'LOC106869903', 'LOC106870763', 'LOC106880954', 'LOC106876255', 'LOC106878581', 'LOC106878412', 'LOC106880875', 'LOC128249781', 'LOC106867195', 'LOC106873892', 'LOC106881280', 'LOC106870021', 'LOC106873020', 'LOC106867837', 'LOC106870007', 'LOC106871191', 'LOC128250153', 'LOC106871154', 'LOC106876426', 'LOC106867115', 'LOC106869394', 'LOC106879709', 'LOC106884131', 'LOC106867480', 'LOC106874030', 'LOC106875881', 'LOC106873206', 'LOC106874351', 'LOC106876548', 'LOC106876523', 'LOC106868910', 'LOC106881559', 'LOC106884054', 'LOC106877518', 'LOC106879405', 'LOC106880932', 'LOC106871896', 'LOC106874561', 'LOC106877334', 'LOC106882584', 'LOC128248884', 'LOC106878553', 'LOC106877756', 'LOC106867560', 'LOC106872331', 'LOC106870296', 'LOC106884019', 'LOC106877087', 'LOC106879552', 'LOC106884468', 'LOC106873342', 'LOC106868743', 'LOC128251050', 'LOC106878628', 'LOC106877033', 'LOC106879534', 'LOC106867768', 'LOC106868658', 'LOC106871628', 'LOC106872151', 'LOC106876093', 'LOC106874784', 'LOC106871425', 'LOC106875942', 'LOC106873152', 'LOC106880833', 'LOC106867412', 'LOC106868327', 'LOC106872963', 'LOC106870239', 'LOC106870514', 'LOC106873134', 'LOC106875625', 'LOC106870812', 'LOC106877011', 'LOC106878894', 'LOC106882104', 'LOC106870770', 'LOC106882052', 'LOC106873965', 'LOC106873703', 'LOC106869528', 'LOC106867761', 'LOC106873788', 'LOC106868175', 'LOC128250357', 'LOC106867811', 'LOC106870649', 'LOC128251228', 'LOC106867638', 'LOC106871046', 'LOC106872606', 'LOC106882542', 'LOC106880901', 'LOC106869078', 'LOC106874803', 'LOC106874693', 'LOC106869094', 'LOC106871408', 'LOC106875016', 'LOC106871334', 'LOC106874636', 'LOC106882943', 'LOC106868224', 'LOC106881247', 'LOC106882758', 'LOC106869076', 'LOC106874285', 'LOC106877244', 'LOC106872633', 'LOC106882641', 'LOC106882486', 'LOC128248346', 'LOC106877988', 'LOC106882575', 'LOC106870543', 'LOC106877177', 'LOC106873070', 'LOC106882692', 'LOC106877279', 'LOC106874310', 'LOC106870442', 'LOC106881682', 'LOC106877486', 'LOC106871868', 'LOC106876177', 'LOC106873440', 'LOC106882126', 'LOC106876863', 'LOC106879259', 'LOC106873149', 'LOC106876357', 'LOC106875122', 'LOC106879401', 'LOC106871579', 'LOC106877754', 'LOC106867210', 'LOC106875600', 'LOC106868329', 'LOC106868450', 'LOC106873852', 'LOC106882494', 'LOC106871366', 'LOC106880224', 'LOC106876989', 'LOC106875592', 'LOC106871672', 'LOC106883729', 'LOC106871049', 'LOC106875643', 'LOC106868772', 'LOC106867199', 'LOC106868398', 'LOC106872211', 'LOC106875697', 'LOC106884115', 'LOC106874233', 'LOC106875995', 'LOC106880842', 'LOC106872520', 'LOC106867197', 'LOC106871807', 'LOC106871338', 'LOC106876493', 'LOC106881813', 'LOC106870888', 'LOC106872982', 'LOC106881931', 'LOC106871880', 'LOC106881898', 'LOC106872610', 'LOC106878460', 'LOC128249552', 'LOC106882119', 'LOC106867574', 'LOC106876702', 'LOC106879839', 'LOC106882030', 'LOC106880401', 'LOC128250889', 'LOC106870453', 'LOC106869862', 'LOC106873744', 'LOC106876813', 'LOC106874373', 'LOC106882536', 'LOC106869942', 'LOC106869344', 'LOC106884092', 'LOC106873343', 'LOC106874890', 'LOC106869888', 'LOC128250366', 'LOC106884181', 'LOC106873074', 'LOC106879922', 'LOC106874977', 'LOC106873058', 'LOC106878801', 'LOC106884340', 'LOC106880986', 'LOC106876877', 'LOC106875733', 'LOC106878171', 'LOC106874650', 'LOC106876360', 'LOC106884272', 'LOC106871358', 'LOC106880952', 'LOC106872663', 'LOC106872510', 'LOC106877984', 'LOC106869198', 'LOC106876102', 'LOC106871586', 'LOC106869963', 'LOC106872006', 'LOC106874922', 'LOC106877090', 'LOC106867280', 'LOC106883662', 'LOC106873051', 'LOC106870557', 'LOC106874659', 'LOC106874213', 'LOC106868831', 'LOC106879734', 'LOC106873857', 'LOC106872358', 'LOC106876386', 'LOC106869012', 'LOC106880608', 'LOC106877734', 'LOC106867636', 'LOC106876292', 'LOC106878983', 'LOC106879158', 'LOC106877591', 'LOC106872106', 'LOC106882114', 'LOC106876351', 'LOC106879300', 'LOC106880290', 'LOC106868385', 'LOC106873685', 'LOC106867751', 'LOC106883189', 'LOC106870495', 'LOC106875656', 'LOC106880645', 'LOC106880787', 'LOC106871308', 'LOC106881713', 'LOC106867587', 'LOC106882955', 'LOC106882391', 'LOC106873773', 'LOC106881345', 'LOC106883400', 'LOC106868263', 'LOC106874353', 'LOC106883843', 'LOC106873013', 'LOC106867757', 'LOC106875511', 'LOC106872267', 'LOC128251403', 'LOC106879754', 'LOC106883872', 'LOC106876865', 'LOC128247268', 'LOC106868728', 'LOC106867422', 'LOC106878661', 'LOC106873733', 'LOC106868078', 'LOC106878848', 'LOC106869943', 'LOC106870546', 'LOC106868507', 'LOC106880077', 'LOC106876689', 'LOC106880813', 'LOC106880938', 'LOC106869197', 'LOC106875637', 'LOC106868827']

In [73]:
loc_list = [
    "LOC106877206",
    "LOC106876744",
    "LOC106880212",
    "LOC106877680",
    "LOC106883024",
    "LOC106869367"
]

In [75]:
print(blast_df['bimac_gene_id'].unique().tolist())

['LOC106872539', 'LOC106879399', 'LOC106880683', 'LOC106878131', 'LOC106869296', 'LOC106877656', 'LOC106868077', 'LOC106876561', 'LOC106879992', 'LOC106883689', 'LOC106877993', 'LOC106878664', 'LOC106881726', 'LOC106877159', 'LOC106874404', 'LOC106869381', 'LOC106872175', 'LOC106876926', 'LOC106873655', 'LOC106878652', 'LOC106873348', 'LOC106879048', 'LOC106883047', 'LOC106883356', 'LOC106870865', 'LOC106876012', 'LOC106882721', 'LOC106871773', 'LOC106882507', 'LOC106870659', 'LOC106876142', 'LOC106867951', 'LOC106870188', 'LOC106872141', 'LOC106874624', 'LOC128251004', 'LOC106874631', 'LOC106877879', 'LOC106867940', 'LOC106878163', 'LOC106880711', 'LOC106882876', 'LOC128249929', 'LOC106882869', 'LOC106872865', 'LOC106874875', 'LOC106875090', 'LOC106872771', 'LOC106869609', 'LOC106867467', 'LOC106868761', 'LOC106872645', 'LOC106882982', 'LOC106878161', 'LOC106867103', 'LOC106879459', 'LOC106868847', 'LOC128247069', 'LOC106883780', 'LOC106884083', 'LOC106882344', 'LOC106871668', 'LOC106875968', 'LOC106881860', 'LOC106869040', 'LOC106882896', 'LOC106877583', 'LOC106878883', 'LOC106877533', 'LOC106871661', 'LOC128251294', 'LOC106882314', 'LOC106876298', 'LOC106869058', 'LOC106870154', 'LOC106873977', 'LOC106880796', 'LOC106873996', 'LOC106879858', 'LOC106879726', 'LOC106879136', 'LOC106867192', 'LOC106874145', 'LOC106873798', 'LOC106884407', 'LOC106884262', 'LOC106867189', 'LOC106874194', 'LOC106880387', 'LOC106881733', 'LOC106868985', 'LOC106870582', 'LOC106869069', 'LOC106869879', 'LOC106879312', 'LOC106884008', 'LOC106867817', 'LOC106881224', 'LOC106879707', 'LOC106867662', 'LOC106878710', 'LOC106867546', 'LOC106880935', 'LOC106878278', 'LOC106882576', 'LOC106882968', 'LOC106873112', 'LOC106876546', 'LOC106868050', 'LOC106875884', 'LOC106877766', 'LOC128251527', 'LOC128251039', 'LOC106869506', 'LOC106878457', 'LOC106881314', 'LOC106871417', 'LOC106875849', 'LOC106869253', 'LOC106880078', 'LOC106884133', 'LOC106873831', 'LOC106879053', 'LOC106881643', 'LOC106877990', 'LOC106869229', 'LOC106871260', 'LOC106876014', 'LOC106882202', 'LOC106881472', 'LOC106872293', 'LOC106868703', 'LOC128250031', 'LOC106870470', 'LOC106882767', 'LOC106883887', 'LOC106868648', 'LOC106868208', 'LOC106873542', 'LOC106879976', 'LOC106873941', 'LOC106868928', 'LOC106873641', 'LOC106874533', 'LOC106877037', 'LOC106868081', 'LOC106883581', 'LOC106869320', 'LOC106884063', 'LOC128248504', 'LOC106868880', 'LOC106870446', 'LOC106868461', 'LOC106872270', 'LOC106875854', 'LOC106868862', 'LOC106883928', 'LOC106881085', 'LOC106879728', 'LOC106880590', 'LOC106879397', 'LOC106879572', 'LOC106872275', 'LOC106881952', 'LOC106879601', 'LOC106877080', 'LOC106877785', 'LOC106870605', 'LOC106883628', 'LOC106882174', 'LOC106867675', 'LOC106881483', 'LOC106882489', 'LOC106867428', 'LOC106868093', 'LOC106879788', 'LOC106875312', 'LOC106873617', 'LOC106877891', 'LOC106881039', 'LOC106879860', 'LOC106876017', 'LOC106873715', 'LOC106882761', 'LOC106871651', 'LOC106870575', 'LOC106879642', 'LOC106867861', 'LOC106873969', 'LOC106883595', 'LOC106881109', 'LOC106872420', 'LOC106879021', 'LOC106882799', 'LOC106874949', 'LOC106876724', 'LOC106872237', 'LOC106869854', 'LOC106882236', 'LOC128251150', 'LOC106879885', 'LOC106881786', 'LOC106869196', 'LOC106869194', 'LOC106879111', 'LOC106877158', 'LOC106877457', 'LOC106881230', 'LOC106878782', 'LOC106873492', 'LOC106881027', 'LOC106881135', 'LOC106879267', 'LOC106879182', 'LOC106877664', 'LOC106875564', 'LOC106871506', 'LOC128249674', 'LOC128250821', 'LOC106867276', 'LOC106869702', 'LOC106883803', 'LOC128246989', 'LOC106876496', 'LOC106875173', 'LOC106872709', 'LOC106875053', 'LOC106867391', 'LOC106883914', 'LOC106876990', 'LOC106874785', 'LOC106880928', 'LOC106876391', 'LOC106878138', 'LOC106877543', 'LOC106873845', 'LOC106872942', 'LOC106873884', 'LOC106869287', 'LOC106869624', 'LOC106878386', 'LOC106871536', 'LOC106876411', 'LOC128249616', 'LOC106880561', 'LOC106879805', 'LOC128250104', 'LOC106882622', 'LOC106880265', 'LOC106870416', 'LOC106879500', 'LOC106877363', 'LOC106876467', 'LOC106881982', 'LOC106867738', 'LOC106871364', 'LOC106869399', 'LOC106874907', 'LOC106867229', 'LOC106869476', 'LOC106882098', 'LOC106873062', 'LOC106881178', 'LOC106880025', 'LOC106873244', 'LOC106878475', 'LOC106882904', 'LOC106880175', 'LOC106874436', 'LOC106884279', 'LOC106882791', 'LOC106879393', 'LOC106875343', 'LOC106873760', 'LOC106868557', 'LOC106870889', 'LOC106874308', 'LOC106870617', 'LOC106883856', 'LOC106869820', 'LOC106883505', 'LOC106883972', 'LOC106875480', 'LOC106869730', 'LOC106872105', 'LOC106880798', 'LOC106875982', 'LOC106884177', 'LOC106869620', 'LOC106870815', 'LOC106881079', 'LOC106868425', 'LOC106880002', 'LOC106870314', 'LOC106877738', 'LOC106881480', 'LOC106871654', 'LOC106875972', 'LOC128248161', 'LOC106871265', 'LOC106869346', 'LOC106867255', 'LOC128251091', 'LOC106868652', 'LOC106869784', 'LOC106877582', 'LOC106874162', 'LOC106881681', 'LOC106868262', 'LOC106883345', 'LOC106869258', 'LOC106869074', 'LOC106871287', 'LOC106869455', 'LOC106868011', 'LOC106877170', 'LOC106873317', 'LOC106871278', 'LOC106868786', 'LOC106870708', 'LOC106871374', 'LOC106876350', 'LOC106876839', 'LOC106872046', 'LOC106883257', 'LOC106881841', 'LOC106875453', 'LOC106877925', 'LOC106869923', 'LOC106872515', 'LOC106873585', 'LOC106867483', 'LOC106875633', 'LOC106875059', 'LOC106870145', 'LOC106880030', 'LOC106870024', 'LOC106882491', 'LOC106876289', 'LOC128248913', 'LOC106879895', 'LOC106877131', 'LOC106878159', 'LOC106882336', 'LOC106882765', 'LOC106883095', 'LOC106880397', 'LOC106883351', 'LOC106875548', 'LOC106867556', 'LOC106879977', 'LOC106879874', 'LOC106880861', 'LOC106873875', 'LOC106877434', 'LOC106881774', 'LOC106877362', 'LOC106870257', 'LOC106874575', 'LOC106880594', 'LOC106869102', 'LOC106871573', 'LOC106868971', 'LOC106872147', 'LOC106878727', 'LOC106872296', 'LOC106867510', 'LOC106881296', 'LOC106884339', 'LOC106883006', 'LOC128251119', 'LOC106868777', 'LOC106878008', 'LOC106878005', 'LOC106883674', 'LOC106883309', 'LOC106870540', 'LOC106879368', 'LOC106867808', 'LOC106883032', 'LOC106871942', 'LOC106872072', 'LOC106878624', 'LOC106869537', 'LOC106870252', 'LOC106872170', 'LOC106884110', 'LOC106874692', 'LOC106876245', 'LOC106882638', 'LOC106876383', 'LOC106884187', 'LOC106878611', 'LOC106877914', 'LOC106881387', 'LOC106871398', 'LOC106877597', 'LOC106872700', 'LOC106867792', 'LOC106881001', 'LOC106871043', 'LOC106872994', 'LOC106880396', 'LOC106875618', 'LOC106875765', 'LOC106879014', 'LOC106880510', 'LOC106881743', 'LOC106868984', 'LOC128248671', 'LOC106881116', 'LOC106881590', 'LOC106870608', 'LOC106871120', 'LOC106876547', 'LOC106868940', 'LOC106882841', 'LOC106869169', 'LOC106867824', 'LOC106875497', 'LOC106875455', 'LOC128251177', 'LOC106878784', 'LOC106867091', 'LOC106877010', 'LOC106868244', 'LOC106874343', 'LOC106867066', 'LOC106876551', 'LOC106869415', 'LOC106871202', 'LOC106872689', 'LOC106869966', 'LOC106880962', 'LOC106882472', 'LOC106882059', 'LOC106869435', 'LOC106868222', 'LOC106873221', 'LOC106870169', 'LOC106879009', 'LOC106878393', 'LOC106876559', 'LOC106880221', 'LOC106870123', 'LOC128251169', 'LOC106877462', 'LOC106884266', 'LOC106882909', 'LOC106871415', 'LOC106882377', 'LOC106881289', 'LOC106874098', 'LOC106873855', 'LOC106882916', 'LOC106875646', 'LOC106880778', 'LOC106879743', 'LOC106870998', 'LOC106880453', 'LOC106881890', 'LOC106872498', 'LOC106880782', 'LOC128251480', 'LOC106870019', 'LOC106880139', 'LOC106868332', 'LOC106873006', 'LOC106881277', 'LOC106879469', 'LOC106867670', 'LOC106874360', 'LOC106874263', 'LOC106874908', 'LOC106880647', 'LOC106874185', 'LOC106872911', 'LOC106868082', 'LOC106877155', 'LOC106872402', 'LOC106879715', 'LOC106882031', 'LOC106879251', 'LOC106882725', 'LOC106872257', 'LOC106872091', 'LOC106874725', 'LOC106878135', 'LOC106879461', 'LOC106876681', 'LOC106872328', 'LOC106875349', 'LOC106872822', 'LOC106884475', 'LOC106873361', 'LOC106882018', 'LOC106874161', 'LOC106869158', 'LOC106867800', 'LOC106869250', 'LOC106868420', 'LOC106877920', 'LOC106882616', 'LOC106881589', 'LOC106867776', 'LOC106878702', 'LOC106870864', 'LOC106870949', 'LOC106873611', 'LOC106879952', 'LOC106870290', 'LOC106880595', 'LOC106881899', 'LOC106878311', 'LOC106875291', 'LOC106873627', 'LOC106883023', 'LOC106879710', 'LOC106870271', 'LOC106882999', 'LOC106869088', 'LOC106883256', 'LOC106879396', 'LOC106879631', 'LOC106872834', 'LOC106881659', 'LOC106878993', 'LOC106872414', 'LOC128249689', 'LOC106870181', 'LOC106876862', 'LOC106873774', 'LOC106874578', 'LOC106876943', 'LOC106880012', 'LOC106869911', 'LOC106875617', 'LOC106881197', 'LOC106874800', 'LOC106875206', 'LOC106872804', 'LOC106875500', 'LOC106876528', 'LOC106878280', 'LOC106876817', 'LOC106870839', 'LOC106875588', 'LOC106872599', 'LOC106872712', 'LOC106883161', 'LOC106884335', 'LOC106877085', 'LOC106877554', 'LOC106873291', 'LOC106868616', 'LOC106875601', 'LOC106877708', 'LOC106870507', 'LOC106875160', 'LOC106868753', 'LOC106877417', 'LOC106876588', 'LOC106867900', 'LOC106881531', 'LOC106881220', 'LOC106869382', 'LOC106873566', 'LOC106882289', 'LOC106868943', 'LOC106877138', 'LOC106884484', 'LOC106878916', 'LOC106872561', 'LOC106870081', 'LOC106874780', 'LOC106871867', 'LOC106875540', 'LOC106876454', 'LOC106879793', 'LOC106874447', 'LOC106876443', 'LOC106870967', 'LOC106876212', 'LOC106871505', 'LOC106877881', 'LOC106867621', 'LOC106884069', 'LOC106877967', 'LOC106867307', 'LOC106875403', 'LOC106878243', 'LOC106868281', 'LOC106871235', 'LOC106881479', 'LOC128250604', 'LOC106876417', 'LOC106875066', 'LOC106872786', 'LOC106880140', 'LOC106876626', 'LOC106868162', 'LOC106876047', 'LOC106873729', 'LOC106883571', 'LOC106869970', 'LOC106877880', 'LOC106877168', 'LOC106869709', 'LOC106878307', 'LOC106875264', 'LOC106879046', 'LOC106869013', 'LOC128248727', 'LOC106877222', 'LOC106878936', 'LOC106876915', 'LOC106882705', 'LOC106881805', 'LOC106874382', 'LOC106880702', 'LOC106880042', 'LOC106881424', 'LOC106878522', 'LOC106880774', 'LOC106874801', 'LOC106868586', 'LOC106873679', 'LOC106882977', 'LOC106878456', 'LOC106877556', 'LOC106873862', 'LOC106873293', 'LOC106869141', 'LOC106880625', 'LOC106871677', 'LOC106874479', 'LOC106875802', 'LOC106878297', 'LOC106869242', 'LOC106880011', 'LOC106868484', 'LOC106869061', 'LOC106884298', 'LOC106877327', 'LOC106872327', 'LOC106877557', 'LOC106875112', 'LOC106877445', 'LOC106880852', 'LOC106874616', 'LOC106873635', 'LOC106881686', 'LOC106870469', 'LOC106869737', 'LOC106877983', 'LOC106875097', 'LOC106871337', 'LOC106877380', 'LOC106880937', 'LOC106877088', 'LOC106873283', 'LOC106878899', 'LOC106880886', 'LOC106884053', 'LOC106876088', 'LOC106873050', 'LOC106871147', 'LOC106872608', 'LOC106880333', 'LOC106879751', 'LOC106868968', 'LOC106872191', 'LOC106877590', 'LOC106871930', 'LOC106869478', 'LOC106883137', 'LOC106884362', 'LOC106874200', 'LOC106882577', 'LOC106873083', 'LOC106880240', 'LOC106879237', 'LOC106872823', 'LOC106883201', 'LOC106881492', 'LOC106870134', 'LOC128247876', 'LOC106883424', 'LOC106869555', 'LOC106876076', 'LOC106869640', 'LOC106876066', 'LOC106875024', 'LOC106869868', 'LOC106875627', 'LOC106871007', 'LOC106867254', 'LOC128250770', 'LOC106875003', 'LOC106871546', 'LOC106883545', 'LOC106879116', 'LOC106870980', 'LOC106879478', 'LOC106879987', 'LOC106874196', 'LOC106883615', 'LOC106881069', 'LOC106869718', 'LOC106875011', 'LOC106881258', 'LOC106877655', 'LOC106869712', 'LOC106875673', 'LOC106880379', 'LOC106876414', 'LOC106868287', 'LOC106869769', 'LOC106868019', 'LOC106880031', 'LOC106884289', 'LOC106883781', 'LOC106870286', 'LOC106877824', 'LOC106874787', 'LOC106877562', 'LOC106874806', 'LOC106884271', 'LOC106869467', 'LOC106882232', 'LOC106876502', 'LOC128247289', 'LOC106882831', 'LOC106874402', 'LOC106875851', 'LOC106870569', 'LOC106868178', 'LOC106876495', 'LOC106875566', 'LOC106882146', 'LOC106869221', 'LOC106883668', 'LOC106879837', 'LOC106871502', 'LOC106877826', 'LOC106882122', 'LOC106882290', 'LOC106881607', 'LOC106878901', 'LOC106880015', 'LOC106868712', 'LOC106883957', 'LOC106876549', 'LOC106877125', 'LOC106877432', 'LOC106870351', 'LOC106869898', 'LOC106877419', 'LOC106871787', 'LOC106868937', 'LOC106878785', 'LOC106870143', 'LOC106867517', 'LOC106871490', 'LOC106878219', 'LOC106880763', 'LOC106880388', 'LOC106873025', 'LOC106873964', 'LOC106881814', 'LOC106871854', 'LOC106884481', 'LOC106868754', 'LOC106882020', 'LOC106875394', 'LOC106880803', 'LOC106872213', 'LOC106884467', 'LOC106880225', 'LOC106879828', 'LOC106869776', 'LOC106877021', 'LOC106867794', 'LOC106869716', 'LOC106877796', 'LOC106880341', 'LOC106869520', 'LOC106882071', 'LOC106884080', 'LOC106881034', 'LOC106869385', 'LOC106868555', 'LOC128249815', 'LOC106873933', 'LOC106874142', 'LOC106869746', 'LOC106872245', 'LOC106878959', 'LOC106875674', 'LOC106880724', 'LOC106870324', 'LOC106877357', 'LOC106875550', 'LOC106867429', 'LOC106873512', 'LOC106868022', 'LOC106875611', 'LOC106882317', 'LOC106877366', 'LOC106872277', 'LOC106876944', 'LOC106868389', 'LOC106868047', 'LOC106872625', 'LOC106879732', 'LOC106877541', 'LOC106868907', 'LOC106871118', 'LOC106870245', 'LOC106882154', 'LOC106868726', 'LOC106872249', 'LOC106876371', 'LOC106878778', 'LOC106877474', 'LOC106876898', 'LOC106877263', 'LOC106878925', 'LOC106869484', 'LOC106869903', 'LOC106870763', 'LOC106880954', 'LOC106876255', 'LOC106878581', 'LOC106878412', 'LOC106880875', 'LOC128249781', 'LOC106867195', 'LOC106873892', 'LOC106881280', 'LOC106870021', 'LOC106873020', 'LOC106867837', 'LOC106870007', 'LOC106871191', 'LOC128250153', 'LOC106871154', 'LOC106876426', 'LOC106867115', 'LOC106869394', 'LOC106879709', 'LOC106884131', 'LOC106867480', 'LOC106874030', 'LOC106875881', 'LOC106873206', 'LOC106874351', 'LOC106876548', 'LOC106876523', 'LOC106868910', 'LOC106881559', 'LOC106884054', 'LOC106877518', 'LOC106879405', 'LOC106880932', 'LOC106871896', 'LOC106874561', 'LOC106877334', 'LOC106882584', 'LOC128248884', 'LOC106878553', 'LOC106877756', 'LOC106867560', 'LOC106872331', 'LOC106870296', 'LOC106884019', 'LOC106877087', 'LOC106879552', 'LOC106884468', 'LOC106873342', 'LOC106868743', 'LOC128251050', 'LOC106878628', 'LOC106877033', 'LOC106879534', 'LOC106867768', 'LOC106868658', 'LOC106871628', 'LOC106872151', 'LOC106876093', 'LOC106874784', 'LOC106871425', 'LOC106875942', 'LOC106873152', 'LOC106880833', 'LOC106867412', 'LOC106868327', 'LOC106872963', 'LOC106870239', 'LOC106870514', 'LOC106873134', 'LOC106875625', 'LOC106870812', 'LOC106877011', 'LOC106878894', 'LOC106882104', 'LOC106870770', 'LOC106882052', 'LOC106873965', 'LOC106873703', 'LOC106869528', 'LOC106867761', 'LOC106873788', 'LOC106868175', 'LOC128250357', 'LOC106867811', 'LOC106870649', 'LOC128251228', 'LOC106867638', 'LOC106871046', 'LOC106872606', 'LOC106882542', 'LOC106880901', 'LOC106869078', 'LOC106874803', 'LOC106874693', 'LOC106869094', 'LOC106871408', 'LOC106875016', 'LOC106871334', 'LOC106874636', 'LOC106882943', 'LOC106868224', 'LOC106881247', 'LOC106882758', 'LOC106869076', 'LOC106874285', 'LOC106877244', 'LOC106872633', 'LOC106882641', 'LOC106882486', 'LOC128248346', 'LOC106877988', 'LOC106882575', 'LOC106870543', 'LOC106877177', 'LOC106873070', 'LOC106882692', 'LOC106877279', 'LOC106874310', 'LOC106870442', 'LOC106881682', 'LOC106877486', 'LOC106871868', 'LOC106876177', 'LOC106873440', 'LOC106882126', 'LOC106876863', 'LOC106879259', 'LOC106873149', 'LOC106876357', 'LOC106875122', 'LOC106879401', 'LOC106871579', 'LOC106877754', 'LOC106867210', 'LOC106875600', 'LOC106868329', 'LOC106868450', 'LOC106873852', 'LOC106882494', 'LOC106871366', 'LOC106880224', 'LOC106876989', 'LOC106875592', 'LOC106871672', 'LOC106883729', 'LOC106871049', 'LOC106875643', 'LOC106868772', 'LOC106867199', 'LOC106868398', 'LOC106872211', 'LOC106875697', 'LOC106884115', 'LOC106874233', 'LOC106875995', 'LOC106880842', 'LOC106872520', 'LOC106867197', 'LOC106871807', 'LOC106871338', 'LOC106876493', 'LOC106881813', 'LOC106870888', 'LOC106872982', 'LOC106881931', 'LOC106871880', 'LOC106881898', 'LOC106872610', 'LOC106878460', 'LOC128249552', 'LOC106882119', 'LOC106867574', 'LOC106876702', 'LOC106879839', 'LOC106882030', 'LOC106880401', 'LOC128250889', 'LOC106870453', 'LOC106869862', 'LOC106873744', 'LOC106876813', 'LOC106874373', 'LOC106882536', 'LOC106869942', 'LOC106869344', 'LOC106884092', 'LOC106873343', 'LOC106874890', 'LOC106869888', 'LOC128250366', 'LOC106884181', 'LOC106873074', 'LOC106879922', 'LOC106874977', 'LOC106873058', 'LOC106878801', 'LOC106884340', 'LOC106880986', 'LOC106876877', 'LOC106875733', 'LOC106878171', 'LOC106874650', 'LOC106876360', 'LOC106884272', 'LOC106871358', 'LOC106880952', 'LOC106872663', 'LOC106872510', 'LOC106877984', 'LOC106869198', 'LOC106876102', 'LOC106871586', 'LOC106869963', 'LOC106872006', 'LOC106874922', 'LOC106877090', 'LOC106867280', 'LOC106883662', 'LOC106873051', 'LOC106870557', 'LOC106874659', 'LOC106874213', 'LOC106868831', 'LOC106879734', 'LOC106873857', 'LOC106872358', 'LOC106876386', 'LOC106869012', 'LOC106880608', 'LOC106877734', 'LOC106867636', 'LOC106876292', 'LOC106878983', 'LOC106879158', 'LOC106877591', 'LOC106872106', 'LOC106882114', 'LOC106876351', 'LOC106879300', 'LOC106880290', 'LOC106868385', 'LOC106873685', 'LOC106867751', 'LOC106883189', 'LOC106870495', 'LOC106875656', 'LOC106880645', 'LOC106880787', 'LOC106871308', 'LOC106881713', 'LOC106867587', 'LOC106882955', 'LOC106882391', 'LOC106873773', 'LOC106881345', 'LOC106883400', 'LOC106868263', 'LOC106874353', 'LOC106883843', 'LOC106873013', 'LOC106867757', 'LOC106875511', 'LOC106872267', 'LOC128251403', 'LOC106879754', 'LOC106883872', 'LOC106876865', 'LOC128247268', 'LOC106868728', 'LOC106867422', 'LOC106878661', 'LOC106873733', 'LOC106868078', 'LOC106878848', 'LOC106869943', 'LOC106870546', 'LOC106868507', 'LOC106880077', 'LOC106876689', 'LOC106880813', 'LOC106880938', 'LOC106869197', 'LOC106875637', 'LOC106868827']

In [81]:
zdna2 = pd.read_csv("/content/ZDNA_promoters-2.csv", sep='\t')
zdna2.head()

,NC_068981.1,51107,51584,0.257615327835083,NC_068981.1.1,51107.1,53106,LOC106877895,0,+,T-box transcription factor TBX10
0,NC_068981.1,51696,51704,0.339798,NC_068981.1,51107,53106,LOC106877895,0,+,T-box transcription factor TBX10
1,NC_068981.1,52661,52673,0.409930,NC_068981.1,51107,53106,LOC106877895,0,+,T-box transcription factor TBX10
2,NC_068981.1,429582,431024,0.257615,NC_068981.1,429582,431581,LOC106881984,0,+,serine/threonine-protein kinase 36
3,NC_068981.1,802528,803256,0.257615,NC_068981.1,801257,803256,Trnap-ugg,0,-,transfer RNA proline (anticodon UGG)
4,NC_068981.1,805221,805248,0.521920,NC_068981.1,804799,806798,Trnap-ugg,0,-,transfer RNA proline (anticodon UGG)

In [85]:
# Посмотрим названия столбцов
print(zdna2.columns)
print(f"\nВсего столбцов: {len(zdna2.columns)}")

Index(['NC_068981.1', '51107', '51584', '0.257615327835083', 'NC_068981.1.1',
       '51107.1', '53106', 'LOC106877895', '0', '+',
       'T-box transcription factor TBX10'],
      dtype='object')

Всего столбцов: 11

In [86]:
# Получить все уникальные значения из столбца 'LOC106877895'
unique_genes = zdna2['LOC106877895'].unique()

# Создать DataFrame из уникальных значений
loc_list2 = pd.DataFrame(unique_genes, columns=['LOC106877895'])

print(loc_list2)

      LOC106877895
0     LOC106877895
1     LOC106881984
2        Trnap-ugg
3        Trnap-agg
4        Trnap-cgg
...            ...
9355  LOC106882621
9356  LOC106877600
9357  LOC106873928
9358  LOC106881959
9359  LOC106881958

[9360 rows x 1 columns]

In [89]:
# Преобразуем DataFrame в список уникальных значений
loc_list = zdna2['LOC106877895'].unique().tolist()  # или просто list(zdna2['LOC106877895'].unique())

# Теперь проверяем присутствие в blast_df
present = [x for x in loc_list if x in blast_df['bimac_gene_id'].values]
print("Присутствуют в blast_df:", present)
print(f"Количество присутствующих: {len(present)}")

missing = [x for x in loc_list if x not in blast_df['bimac_gene_id'].values]
print("Отсутствуют в blast_df:", missing)
print(f"Количество отсутствующих: {len(missing)}")

Присутствуют в blast_df: ['LOC106872663', 'LOC106875995', 'LOC106881135', 'LOC106874194', 'LOC106874907', 'LOC106876177', 'LOC106870021', 'LOC106875968', 'LOC106879987', 'LOC128249815', 'LOC106872633', 'LOC106878936', 'LOC106871880', 'LOC106877080', 'LOC106877088', 'LOC106881931', 'LOC106876017', 'LOC106874373', 'LOC106871358', 'LOC106882154', 'LOC106883615', 'LOC106876877', 'LOC106879743', 'LOC106868011', 'LOC106870290', 'LOC106871490', 'LOC106868726', 'LOC106869712', 'LOC106870507', 'LOC106871415', 'LOC106884407', 'LOC106869320', 'LOC106867662', 'LOC106867670', 'LOC106873025', 'LOC106872709', 'LOC106872712', 'LOC106870649', 'LOC106877664', 'LOC106869898', 'LOC106869903', 'LOC106874308', 'LOC106874310', 'LOC106880778', 'LOC106867900', 'LOC128247069', 'LOC106880453', 'LOC106867510', 'LOC106880954', 'LOC106877363', 'LOC106875982', 'LOC106884019', 'LOC106881039', 'LOC106875160', 'LOC128247268', 'LOC106867197', 'LOC106876626', 'LOC106876724', 'LOC106867280', 'LOC106881531', 'LOC106875592', 'LOC106868022', 'LOC106868450', 'LOC106875884', 'LOC106875881', 'LOC106869730', 'LOC106869888', 'LOC106868093', 'LOC106882289', 'LOC106878993', 'LOC106872091', 'LOC106868050', 'LOC106880962', 'LOC106880813', 'LOC106877518', 'LOC106882638', 'LOC106878243', 'LOC106868420', 'LOC106874285', 'LOC106882314', 'LOC106881713', 'LOC106880341', 'LOC106872358', 'LOC106884083', 'LOC106873206', 'LOC106883662', 'LOC106867199', 'LOC106867195', 'LOC106874631', 'LOC106869040', 'LOC106873996', 'LOC106877357', 'LOC106882344', 'LOC106873773', 'LOC106867824', 'LOC106868703', 'LOC106880397', 'LOC106884362', 'LOC106877222', 'LOC106879952', 'LOC106875497', 'LOC106880012', 'LOC106874098', 'LOC106876496', 'LOC106881289', 'LOC106878983', 'LOC106877419', 'LOC106883856', 'LOC106878883', 'LOC106872498', 'LOC106884092', 'LOC106883201', 'LOC106883400', 'LOC106876493', 'LOC106878581', 'LOC106882577', 'LOC106876142', 'LOC128247876', 'LOC106876417', 'LOC106881109', 'LOC106869776', 'LOC106869769', 'LOC106869784', 'LOC106883668', 'LOC106875601', 'LOC106883424', 'LOC106882999', 'LOC106873542', 'LOC106870442', 'LOC106875697', 'LOC106869484', 'LOC106869344', 'LOC106869346', 'LOC106876414', 'LOC106882236', 'LOC106874787', 'LOC106870865', 'LOC106882059', 'LOC106868712', 'LOC106868175', 'LOC106884335', 'LOC106881659', 'LOC106879552', 'LOC106878916', 'LOC106872072', 'LOC106881345', 'LOC106872249', 'LOC106872237', 'LOC106872245', 'LOC106871546', 'LOC106871586', 'LOC106871579', 'LOC106882472', 'LOC106878782', 'LOC106882391', 'LOC106869737', 'LOC106867391', 'LOC106872515', 'LOC106879534', 'LOC106872823', 'LOC106868937', 'LOC106868907', 'LOC106883351', 'LOC106875066', 'LOC106869506', 'LOC106879048', 'LOC106872911', 'LOC106874650', 'LOC106872834', 'LOC106883356', 'LOC106878138', 'LOC106878135', 'LOC106871930', 'LOC106884069', 'LOC106870569', 'LOC106870575', 'LOC106883309', 'LOC106868847', 'LOC106876076', 'LOC106872539', 'LOC106878894', 'LOC128248504', 'LOC106878280', 'LOC106875765', 'LOC106869242', 'LOC106878171', 'LOC106882799', 'LOC106869963', 'LOC106869221', 'LOC106868262', 'LOC106881890', 'LOC106867255', 'LOC106869709', 'LOC106881277', 'LOC106882486', 'LOC106877891', 'LOC106867808', 'LOC106884339', 'LOC106872645', 'LOC106869058', 'LOC106867428', 'LOC106878925', 'LOC106875343', 'LOC106870659', 'LOC106874578', 'LOC106868263', 'LOC106868178', 'LOC106871308', 'LOC106871334', 'LOC106872561', 'LOC128248671', 'LOC106875003', 'LOC106874616', 'LOC106872610', 'LOC106872608', 'LOC106870557', 'LOC106876839', 'LOC106882071', 'LOC106878848', 'LOC106869102', 'LOC106877990', 'LOC106868077', 'LOC106867276', 'LOC128248727', 'LOC106871043', 'LOC106872510', 'LOC106867621', 'LOC106883047', 'LOC106868047', 'LOC106869094', 'LOC106875453', 'LOC106871398', 'LOC106877708', 'LOC106879500', 'LOC106877655', 'LOC106877656', 'LOC106881387', 'LOC106869169', 'LOC106879895', 'LOC106877474', 'LOC106883914', 'LOC106873964', 'LOC106873965', 'LOC106871677', 'LOC106874196', 'LOC106868943', 'LOC106869061', 'LOC106880025', 'LOC106867517', 'LOC106871868', 'LOC106871867', 'LOC106869966', 'LOC106870181', 'LOC106869537', 'LOC106883345', 'LOC106871337', 'LOC106884266', 'LOC106869943', 'LOC106869394', 'LOC106874030', 'LOC106881197', 'LOC106882536', 'LOC106882542', 'LOC106876551', 'LOC106876548', 'LOC106876546', 'LOC106876549', 'LOC106884063', 'LOC106872106', 'LOC106877168', 'LOC106880886', 'LOC106881743', 'LOC106869716', 'LOC106875618', 'LOC106880928', 'LOC106867467', 'LOC106879401', 'LOC106879399', 'LOC106880015', 'LOC106873293', 'LOC106870608', 'LOC106881589', 'LOC106879837', 'LOC106879839', 'LOC106872771', 'LOC106870839', 'LOC106876990', 'LOC106879601', 'LOC106875733', 'LOC106883843', 'LOC106870967', 'LOC106870543', 'LOC106876702', 'LOC106871651', 'LOC106871654', 'LOC106875097', 'LOC106873685', 'LOC106874780', 'LOC106878522', 'LOC106880139', 'LOC106868244', 'LOC106880175', 'LOC106869911', 'LOC106877925', 'LOC106872689', 'LOC106868461', 'LOC106884481', 'LOC106884484', 'LOC106884467', 'LOC106875511', 'LOC106882968', 'LOC106872420', 'LOC106872414', 'LOC106879396', 'LOC106876289', 'LOC106876298', 'LOC106881230', 'LOC106878553', 'LOC106876561', 'LOC106875942', 'LOC106876255', 'LOC106879251', 'LOC106880645', 'LOC106880401', 'LOC106870007', 'LOC106883780', 'LOC106883781', 'LOC106870540', 'LOC106868425', 'LOC106872293', 'LOC106877993', 'LOC106869702', 'LOC106867556', 'LOC106867546', 'LOC106881559', 'LOC106876012', 'LOC106876689', 'LOC106874402', 'LOC106884298', 'LOC106867776', 'LOC106870470', 'LOC106870469', 'LOC106873244', 'LOC106868327', 'LOC106868928', 'LOC106880782', 'LOC106875588', 'LOC106879393', 'LOC106879397', 'LOC106884272', 'LOC106876383', 'LOC106876391', 'LOC106868557', 'LOC106868555', 'LOC106875540', 'LOC106875548', 'LOC106878005', 'LOC106882916', 'LOC106875059', 'LOC128249552', 'LOC106876865', 'LOC106878778', 'LOC106883872', 'LOC106869382', 'LOC106869381', 'LOC106873512', 'LOC106879014', 'LOC106874436', 'LOC106881841', 'LOC106870815', 'LOC106881479', 'LOC106873941', 'LOC106876559', 'LOC106871265', 'LOC106872331', 'LOC106880763', 'LOC106877090', 'LOC106867811', 'LOC106883595', 'LOC106870605', 'LOC106874561', 'LOC106872170', 'LOC128249689', 'LOC106877366', 'LOC106876817', 'LOC106878475', 'LOC106869868', 'LOC106879300', 'LOC106880608', 'LOC106878393', 'LOC106878386', 'LOC106871120', 'LOC128249674', 'LOC106867422', 'LOC106881492', 'LOC106884262', 'LOC106881590', 'LOC106874800', 'LOC106874803', 'LOC106877279', 'LOC106871672', 'LOC106880594', 'LOC106874479', 'LOC106880798', 'LOC106868658', 'LOC106868648', 'LOC106868652', 'LOC106871191', 'LOC106869609', 'LOC106882202', 'LOC106875600', 'LOC106869923', 'LOC106872046', 'LOC106882174', 'LOC106877380', 'LOC128249781', 'LOC106877914', 'LOC128249929', 'LOC106879469', 'LOC106882119', 'LOC106880379', 'LOC106880388', 'LOC106880387', 'LOC106882692', 'LOC106880265', 'LOC106884053', 'LOC106884054', 'LOC106872700', 'LOC106869435', 'LOC128250153', 'LOC128250104', 'LOC106879478', 'LOC106871787', 'LOC106872942', 'LOC106867429', 'LOC106883189', 'LOC106873566', 'LOC106873348', 'LOC106877734', 'LOC106877826', 'LOC106877033', 'LOC106877011', 'LOC106877010', 'LOC106874693', 'LOC106875394', 'LOC106875403', 'LOC128250031', 'LOC106878801', 'LOC106878460', 'LOC106877556', 'LOC106877554', 'LOC128250357', 'LOC106877543', 'LOC106878297', 'LOC106869197', 'LOC106869854', 'LOC106877582', 'LOC106882982', 'LOC106881607', 'LOC106880711', 'LOC106871896', 'LOC106876502', 'LOC106869970', 'LOC128250366', 'LOC106879734', 'LOC106875455', 'LOC106876588', 'LOC106877462', 'LOC106873492', 'LOC106881681', 'LOC106877457', 'LOC106870314', 'LOC106870446', 'LOC106870239', 'LOC106870257', 'LOC106870169', 'LOC106881224', 'LOC106874351', 'LOC106871287', 'LOC106882896', 'LOC106871278', 'LOC106877796', 'LOC106877785', 'LOC106873852', 'LOC106875264', 'LOC106872141', 'LOC106871942', 'LOC106877881', 'LOC106877880', 'LOC106875611', 'LOC106875617', 'LOC106873798', 'LOC106880290', 'LOC106883957', 'LOC106880842', 'LOC106870296', 'LOC106873617', 'LOC106880938', 'LOC106882018', 'LOC106880510', 'LOC106875053', 'LOC106884115', 'LOC106884110', 'LOC106879732', 'LOC106878710', 'LOC106879021', 'LOC106879976', 'LOC106867675', 'LOC106872599', 'LOC106869942', 'LOC106874142', 'LOC106867412', 'LOC106869296', 'LOC106872175', 'LOC106872625', 'LOC106872211', 'LOC106873134', 'LOC106872982', 'LOC106874447', 'LOC106879461', 'LOC106884008', 'LOC106879642', 'LOC106868743', 'LOC106873857', 'LOC106873855', 'LOC106879158', 'LOC106881280', 'LOC106874725', 'LOC106875849', 'LOC128250604', 'LOC106873788', 'LOC106882909', 'LOC106874624', 'LOC106874784', 'LOC106868162', 'LOC106873729', 'LOC106873733', 'LOC106871202', 'LOC106882622', 'LOC106878311', 'LOC106876088', 'LOC106876093', 'LOC106881472', 'LOC106870888', 'LOC106878702', 'LOC106870763', 'LOC106877541', 'LOC106868772', 'LOC106868754', 'LOC106883161', 'LOC106873361', 'LOC106875564', 'LOC106879977', 'LOC106871668', 'LOC106882869', 'LOC106883729', 'LOC106873112', 'LOC106876360', 'LOC106880225', 'LOC106871505', 'LOC106871502', 'LOC106871506', 'LOC106876411', 'LOC106881982', 'LOC106880833', 'LOC106873831', 'LOC106873760', 'LOC106871374', 'LOC106879885', 'LOC106880030', 'LOC106879259', 'LOC106877138', 'LOC106868777', 'LOC106873013', 'LOC106881786', 'LOC106881860', 'LOC106873149', 'LOC106882576', 'LOC106882575', 'LOC106874343', 'LOC106884340', 'LOC106878412', 'LOC106882377', 'LOC106880787', 'LOC106880683', 'LOC106879267', 'LOC106869076', 'LOC106869069', 'LOC106867940', 'LOC106868831', 'LOC106880590', 'LOC106879707', 'LOC106879710', 'LOC106878628', 'LOC106871364', 'LOC106871628', 'LOC106883689', 'LOC106868385', 'LOC106868940', 'LOC106868968', 'LOC106880702', 'LOC106871854', 'LOC106882122', 'LOC106881296', 'LOC106876813', 'LOC106882761', 'LOC106882758', 'LOC106882767', 'LOC106868880', 'LOC106881898', 'LOC106875206', 'LOC106883887', 'LOC106867480', 'LOC106867574', 'LOC106881774', 'LOC106877417', 'LOC106874922', 'LOC106868389', 'LOC106876898', 'LOC106870998', 'LOC128251004', 'LOC106867792', 'LOC106870514', 'LOC106875646', 'LOC106873342', 'LOC106873343', 'LOC128251119', 'LOC106878457', 'LOC128251150', 'LOC106882489', 'LOC128251177', 'LOC106873884', 'LOC128251039', 'LOC128246989', 'LOC106874908', 'LOC128251050', 'LOC128251091', 'LOC106876014', 'LOC106882098', 'LOC106873062', 'LOC106877591', 'LOC106877590', 'LOC106881814', 'LOC106875312', 'LOC106872277', 'LOC106872267', 'LOC106872275', 'LOC106882146', 'LOC106877983', 'LOC106883581', 'LOC106884133', 'LOC106884131', 'LOC106871536', 'LOC106883571', 'LOC106882336', 'LOC106878784', 'LOC106873635', 'LOC106884181', 'LOC106884177', 'LOC106878785', 'LOC106874213', 'LOC128251294', 'LOC106880724', 'LOC106878159', 'LOC106878163', 'LOC106873050', 'LOC106873051', 'LOC106876523', 'LOC106882584', 'LOC106879788', 'LOC106867091', 'LOC106882114', 'LOC106877597', 'LOC106880077', 'LOC106877562', 'LOC106878664', 'LOC106877967', 'LOC128251527']
Количество присутствующих: 678

In [90]:
selected_rows = blast_df[blast_df['bimac_gene_id'].isin(present)]
protein_ids = selected_rows['query_prot'].unique().tolist()

In [91]:
print(protein_ids)

['CAI9727365.1', 'CAI9730386.1', 'CAI9740886.1', 'CAI9739051.1', 'CAI9743609.1', 'CAI9727461.1', 'CAI9731707.1', 'CAI9741546.1', 'CAI9729526.1', 'CAI9743405.1', 'CAI9734175.1', 'CAI9738772.1', 'CAI9737061.1', 'CAI9726406.1', 'CAI9728393.1', 'CAI9725593.1', 'CAI9724950.1', 'CAI9732073.1', 'CAI9726567.1', 'CAI9723436.1', 'CAI9738537.1', 'CAI9739673.1', 'CAI9741983.1', 'CAI9718901.1', 'CAI9740464.1', 'CAI9727062.1', 'CAI9737729.1', 'CAI9735831.1', 'CAI9740043.1', 'CAI9730088.1', 'CAI9736210.1', 'CAI9730452.1', 'CAI9727382.1', 'CAI9737843.1', 'CAI9725699.1', 'CAI9737122.1', 'CAI9731625.1', 'CAI9719529.1', 'CAI9724016.1', 'CAI9740705.1', 'CAI9744335.1', 'CAI9740984.1', 'CAI9739617.1', 'CAI9737278.1', 'CAI9723042.1', 'CAI9723413.1', 'CAI9720399.1', 'CAI9731742.1', 'CAI9727214.1', 'CAI9726143.1', 'CAI9738631.1', 'CAI9716324.1', 'CAI9734866.1', 'CAI9715678.1', 'CAI9736749.1', 'CAI9740486.1', 'CAI9739241.1', 'CAI9737223.1', 'CAI9741449.1', 'CAI9716472.1', 'CAI9739158.1', 'CAI9732179.1', 'CAI9740680.1', 'CAI9731661.1', 'CAI9732562.1', 'CAI9743269.1', 'CAI9730753.1', 'CAI9719756.1', 'CAI9720365.1', 'CAI9734400.1', 'CAI9743141.1', 'CAI9726388.1', 'CAI9715743.1', 'CAI9739389.1', 'CAI9744008.1', 'CAI9740282.1', 'CAI9727433.1', 'CAI9724964.1', 'CAI9742309.1', 'CAI9736212.1', 'CAI9740019.1', 'CAI9731894.1', 'CAI9723376.1', 'CAI9736839.1', 'CAI9737511.1', 'CAI9742258.1', 'CAI9741841.1', 'CAI9736085.1', 'CAI9725003.1', 'CAI9739138.1', 'CAI9734331.1', 'CAI9733172.1', 'CAI9743634.1', 'CAI9716380.1', 'CAI9730657.1', 'CAI9727306.1', 'CAI9742239.1', 'CAI9737197.1', 'CAI9731314.1', 'CAI9732691.1', 'CAI9741126.1', 'CAI9732494.1', 'CAI9742929.1', 'CAI9729869.1', 'CAI9716792.1', 'CAI9738481.1', 'CAI9734770.1', 'CAI9735896.1', 'CAI9738948.1', 'CAI9743230.1', 'CAI9726789.1', 'CAI9719070.1', 'CAI9743473.1', 'CAI9742960.1', 'CAI9738164.1', 'CAI9726815.1', 'CAI9719366.1', 'CAI9715501.1', 'CAI9742265.1', 'CAI9729794.1', 'CAI9726308.1', 'CAI9739244.1', 'CAI9734441.1', 'CAI9723217.1', 'CAI9731802.1', 'CAI9739153.1', 'CAI9727397.1', 'CAI9739192.1', 'CAI9725195.1', 'CAI9737914.1', 'CAI9724484.1', 'CAI9743244.1', 'CAI9740555.1', 'CAI9740963.1', 'CAI9734935.1', 'CAI9737140.1', 'CAI9731734.1', 'CAI9725284.1', 'CAI9737312.1', 'CAI9715694.1', 'CAI9740922.1', 'CAI9716703.1', 'CAI9740178.1', 'CAI9740380.1', 'CAI9728827.1', 'CAI9728485.1', 'CAI9740180.1', 'CAI9732005.1', 'CAI9743126.1', 'CAI9723563.1', 'CAI9716558.1', 'CAI9738271.1', 'CAI9725350.1', 'CAI9729365.1', 'CAI9729895.1', 'CAI9730466.1', 'CAI9732887.1', 'CAI9725744.1', 'CAI9738002.1', 'CAI9736561.1', 'CAI9743009.1', 'CAI9735461.1', 'CAI9743355.1', 'CAI9740335.1', 'CAI9736609.1', 'CAI9739447.1', 'CAI9736702.1', 'CAI9727698.1', 'CAI9719349.1', 'CAI9740328.1', 'CAI9741471.1', 'CAI9715918.1', 'CAI9742364.1', 'CAI9742874.1', 'CAI9729068.1', 'CAI9733557.1', 'CAI9735437.1', 'CAI9731038.1', 'CAI9733932.1', 'CAI9732489.1', 'CAI9726767.1', 'CAI9740275.1', 'CAI9732967.1', 'CAI9714719.1', 'CAI9723079.1', 'CAI9720375.1', 'CAI9736070.1', 'CAI9719465.1', 'CAI9744268.1', 'CAI9733852.1', 'CAI9731927.1', 'CAI9737163.1', 'CAI9729798.1', 'CAI9734694.1', 'CAI9724161.1', 'CAI9727109.1', 'CAI9743874.1', 'CAI9736086.1', 'CAI9723150.1', 'CAI9737948.1', 'CAI9737133.1', 'CAI9727166.1', 'CAI9728546.1', 'CAI9737262.1', 'CAI9715157.1', 'CAI9737277.1', 'CAI9729962.1', 'CAI9727859.1', 'CAI9736263.1', 'CAI9733909.1', 'CAI9727571.1', 'CAI9731446.1', 'CAI9736239.1', 'CAI9725437.1', 'CAI9733770.1', 'CAI9740529.1', 'CAI9731744.1', 'CAI9728607.1', 'CAI9744534.1', 'CAI9731117.1', 'CAI9723408.1', 'CAI9726220.1', 'CAI9732606.1', 'CAI9732200.1', 'CAI9740160.1', 'CAI9741814.1', 'CAI9737204.1', 'CAI9736374.1', 'CAI9727519.1', 'CAI9725578.1', 'CAI9737500.1', 'CAI9744081.1', 'CAI9727386.1', 'CAI9742902.1', 'CAI9740511.1', 'CAI9732574.1', 'CAI9726365.1', 'CAI9731844.1', 'CAI9726825.1', 'CAI9738564.1', 'CAI9723882.1', 'CAI9728542.1', 'CAI9735313.1', 'CAI9726022.1', 'CAI9720016.1', 'CAI9732552.1', 'CAI9735736.1', 'CAI9729207.1', 'CAI9727617.1', 'CAI9744201.1', 'CAI9734713.1', 'CAI9736675.1', 'CAI9741871.1', 'CAI9739311.1', 'CAI9728448.1', 'CAI9730473.1', 'CAI9727331.1', 'CAI9744479.1', 'CAI9738248.1', 'CAI9730583.1', 'CAI9728097.1', 'CAI9735543.1', 'CAI9730175.1', 'CAI9735501.1', 'CAI9741162.1', 'CAI9729233.1', 'CAI9723355.1', 'CAI9722817.1', 'CAI9737392.1', 'CAI9743229.1', 'CAI9737494.1', 'CAI9732697.1', 'CAI9736979.1', 'CAI9730855.1', 'CAI9744290.1', 'CAI9740673.1', 'CAI9730762.1', 'CAI9735242.1', 'CAI9727323.1', 'CAI9739479.1', 'CAI9731211.1', 'CAI9729125.1', 'CAI9720436.1', 'CAI9725209.1', 'CAI9724943.1', 'CAI9736666.1', 'CAI9737215.1', 'CAI9735466.1', 'CAI9734344.1', 'CAI9737341.1', 'CAI9728755.1', 'CAI9739653.1', 'CAI9716297.1', 'CAI9740795.1', 'CAI9723577.1', 'CAI9722664.1', 'CAI9739269.1', 'CAI9732570.1', 'CAI9741922.1', 'CAI9714782.1', 'CAI9715253.1', 'CAI9742036.1', 'CAI9724534.1', 'CAI9727116.1', 'CAI9723014.1', 'CAI9733148.1', 'CAI9730884.1', 'CAI9726460.1', 'CAI9735760.1', 'CAI9716473.1', 'CAI9729324.1', 'CAI9726129.1', 'CAI9731580.1', 'CAI9719733.1', 'CAI9739359.1', 'CAI9725727.1', 'CAI9739203.1', 'CAI9740202.1', 'CAI9738246.1', 'CAI9720500.1', 'CAI9730150.1', 'CAI9732331.1', 'CAI9739998.1', 'CAI9722911.1', 'CAI9716056.1', 'CAI9739450.1', 'CAI9741451.1', 'CAI9723963.1', 'CAI9731763.1', 'CAI9725561.1', 'CAI9724634.1', 'CAI9738429.1', 'CAI9731784.1', 'CAI9722388.1', 'CAI9729100.1', 'CAI9726580.1', 'CAI9722656.1', 'CAI9731055.1', 'CAI9738646.1', 'CAI9723671.1', 'CAI9735539.1', 'CAI9742236.1', 'CAI9727319.1', 'CAI9735630.1', 'CAI9730069.1', 'CAI9733134.1', 'CAI9739004.1', 'CAI9716559.1', 'CAI9740230.1', 'CAI9724599.1', 'CAI9738009.1', 'CAI9723500.1', 'CAI9727723.1', 'CAI9716237.1', 'CAI9719183.1', 'CAI9741609.1', 'CAI9737334.1', 'CAI9714756.1', 'CAI9719358.1', 'CAI9734176.1', 'CAI9737094.1', 'CAI9719678.1', 'CAI9729425.1', 'CAI9740513.1', 'CAI9731491.1', 'CAI9724883.1', 'CAI9728133.1', 'CAI9732937.1', 'CAI9729134.1', 'CAI9732614.1', 'CAI9738735.1', 'CAI9729707.1', 'CAI9740386.1', 'CAI9738571.1', 'CAI9728406.1', 'CAI9725862.1', 'CAI9744433.1', 'CAI9736865.1', 'CAI9719961.1', 'CAI9733794.1', 'CAI9739401.1', 'CAI9744360.1', 'CAI9726260.1', 'CAI9719259.1', 'CAI9739525.1', 'CAI9739520.1', 'CAI9743293.1', 'CAI9737678.1', 'CAI9738573.1', 'CAI9730722.1', 'CAI9727100.1', 'CAI9738517.1', 'CAI9743732.1', 'CAI9723424.1', 'CAI9714837.1', 'CAI9741387.1', 'CAI9729633.1', 'CAI9716692.1', 'CAI9738017.1', 'CAI9730332.1', 'CAI9729523.1', 'CAI9736015.1', 'CAI9737335.1', 'CAI9737256.1', 'CAI9726517.1', 'CAI9729079.1', 'CAI9732279.1', 'CAI9727975.1', 'CAI9715665.1', 'CAI9733588.1', 'CAI9725310.1', 'CAI9743431.1', 'CAI9729802.1', 'CAI9728728.1', 'CAI9735898.1', 'CAI9716782.1', 'CAI9730586.1', 'CAI9736687.1', 'CAI9739770.1', 'CAI9744141.1', 'CAI9727908.1', 'CAI9741309.1', 'CAI9742741.1', 'CAI9725830.1', 'CAI9723412.1', 'CAI9722917.1', 'CAI9725996.1', 'CAI9722607.1', 'CAI9735562.1', 'CAI9723459.1', 'CAI9724087.1', 'CAI9744505.1', 'CAI9725640.1', 'CAI9726414.1', 'CAI9743281.1', 'CAI9735422.1', 'CAI9728069.1', 'CAI9725737.1', 'CAI9725168.1', 'CAI9736576.1', 'CAI9714904.1', 'CAI9729491.1', 'CAI9715346.1', 'CAI9727778.1', 'CAI9729096.1', 'CAI9736775.1', 'CAI9723674.1', 'CAI9723153.1', 'CAI9731628.1', 'CAI9724662.1', 'CAI9740451.1', 'CAI9737686.1', 'CAI9732128.1', 'CAI9725882.1', 'CAI9726981.1', 'CAI9743621.1', 'CAI9726653.1', 'CAI9723647.1', 'CAI9731793.1', 'CAI9730120.1', 'CAI9740382.1', 'CAI9727616.1', 'CAI9737307.1', 'CAI9737039.1', 'CAI9741324.1', 'CAI9737794.1', 'CAI9730358.1', 'CAI9724930.1', 'CAI9738681.1', 'CAI9730749.1', 'CAI9714695.1', 'CAI9723092.1', 'CAI9736570.1', 'CAI9725930.1', 'CAI9744257.1', 'CAI9728994.1', 'CAI9716074.1', 'CAI9734683.1', 'CAI9736748.1', 'CAI9716527.1', 'CAI9743902.1', 'CAI9742975.1', 'CAI9741351.1', 'CAI9731404.1', 'CAI9739894.1', 'CAI9736885.1', 'CAI9731494.1', 'CAI9740415.1', 'CAI9723155.1', 'CAI9730485.1', 'CAI9738478.1', 'CAI9719114.1', 'CAI9727826.1', 'CAI9732682.1', 'CAI9734958.1', 'CAI9739023.1', 'CAI9725193.1', 'CAI9744476.1', 'CAI9743065.1', 'CAI9736806.1', 'CAI9734016.1', 'CAI9720347.1', 'CAI9738653.1', 'CAI9735582.1', 'CAI9742932.1', 'CAI9736391.1', 'CAI9741715.1', 'CAI9728365.1', 'CAI9738769.1', 'CAI9738095.1', 'CAI9739933.1', 'CAI9726217.1', 'CAI9715364.1', 'CAI9716159.1', 'CAI9725204.1', 'CAI9733627.1', 'CAI9728576.1', 'CAI9742165.1', 'CAI9724437.1', 'CAI9724249.1', 'CAI9714702.1', 'CAI9739994.1', 'CAI9719319.1', 'CAI9731697.1', 'CAI9722944.1', 'CAI9740702.1', 'CAI9735915.1', 'CAI9718961.1', 'CAI9739335.1', 'CAI9714933.1', 'CAI9731603.1', 'CAI9736142.1', 'CAI9743597.1', 'CAI9736650.1', 'CAI9728830.1', 'CAI9744019.1', 'CAI9741836.1', 'CAI9729462.1', 'CAI9724707.1', 'CAI9719614.1', 'CAI9737240.1', 'CAI9730757.1', 'CAI9744143.1', 'CAI9732137.1', 'CAI9736682.1', 'CAI9733790.1', 'CAI9737719.1', 'CAI9734773.1', 'CAI9744262.1', 'CAI9731733.1', 'CAI9740919.1', 'CAI9734327.1', 'CAI9738376.1', 'CAI9719455.1', 'CAI9724631.1', 'CAI9743032.1', 'CAI9739260.1', 'CAI9742835.1', 'CAI9741459.1', 'CAI9736996.1', 'CAI9725452.1', 'CAI9736078.1', 'CAI9741498.1', 'CAI9739769.1', 'CAI9739614.1', 'CAI9731708.1', 'CAI9740325.1', 'CAI9739040.1', 'CAI9733333.1', 'CAI9737199.1', 'CAI9741891.1', 'CAI9738835.1', 'CAI9736981.1', 'CAI9726672.1', 'CAI9714921.1', 'CAI9728646.1', 'CAI9743092.1', 'CAI9739414.1', 'CAI9723731.1', 'CAI9738004.1', 'CAI9734487.1', 'CAI9716582.1', 'CAI9732544.1', 'CAI9735530.1', 'CAI9736906.1', 'CAI9731134.1', 'CAI9727538.1', 'CAI9724379.1', 'CAI9728144.1', 'CAI9742259.1', 'CAI9740493.1', 'CAI9720544.1', 'CAI9738407.1', 'CAI9726417.1', 'CAI9740679.1', 'CAI9719171.1', 'CAI9734636.1', 'CAI9736726.1', 'CAI9734922.1', 'CAI9735368.1', 'CAI9714723.1', 'CAI9724400.1', 'CAI9729138.1', 'CAI9733928.1', 'CAI9740517.1', 'CAI9740651.1', 'CAI9730388.1', 'CAI9725134.1', 'CAI9736226.1', 'CAI9726824.1', 'CAI9720364.1', 'CAI9738495.1', 'CAI9720328.1', 'CAI9736432.1', 'CAI9727290.1', 'CAI9740070.1', 'CAI9739904.1', 'CAI9718968.1', 'CAI9738690.1', 'CAI9724328.1', 'CAI9738286.1', 'CAI9715723.1', 'CAI9738384.1', 'CAI9719246.1', 'CAI9722437.1', 'CAI9740009.1', 'CAI9731370.1', 'CAI9715570.1', 'CAI9716752.1', 'CAI9738078.1', 'CAI9727917.1', 'CAI9738045.1', 'CAI9733765.1', 'CAI9736788.1', 'CAI9741786.1', 'CAI9724145.1', 'CAI9729763.1', 'CAI9730119.1', 'CAI9731588.1', 'CAI9725379.1', 'CAI9731058.1', 'CAI9715436.1', 'CAI9730778.1', 'CAI9739013.1', 'CAI9724164.1', 'CAI9722313.1', 'CAI9743030.1', 'CAI9719071.1', 'CAI9737613.1', 'CAI9744330.1', 'CAI9738060.1', 'CAI9740670.1', 'CAI9715261.1', 'CAI9729817.1', 'CAI9726501.1', 'CAI9726100.1', 'CAI9740423.1', 'CAI9732530.1', 'CAI9716818.1', 'CAI9715787.1', 'CAI9728414.1', 'CAI9725140.1', 'CAI9726631.1', 'CAI9741744.1', 'CAI9734493.1', 'CAI9719480.1', 'CAI9719660.1', 'CAI9744138.1', 'CAI9727889.1', 'CAI9744239.1', 'CAI9741136.1', 'CAI9737469.1', 'CAI9716759.1', 'CAI9739267.1', 'CAI9720196.1', 'CAI9735484.1', 'CAI9737066.1', 'CAI9723624.1', 'CAI9739316.1', 'CAI9742739.1', 'CAI9730675.1', 'CAI9739326.1', 'CAI9735418.1', 'CAI9738677.1', 'CAI9741257.1', 'CAI9729666.1', 'CAI9736817.1', 'CAI9731583.1', 'CAI9740858.1', 'CAI9728149.1', 'CAI9719105.1', 'CAI9725291.1', 'CAI9744119.1', 'CAI9723876.1', 'CAI9722414.1', 'CAI9739932.1', 'CAI9741735.1', 'CAI9727000.1', 'CAI9729746.1', 'CAI9740506.1', 'CAI9731688.1', 'CAI9742931.1', 'CAI9733614.1', 'CAI9733678.1', 'CAI9719217.1', 'CAI9734984.1', 'CAI9739515.1', 'CAI9728192.1', 'CAI9728779.1', 'CAI9735559.1', 'CAI9744349.1', 'CAI9732112.1', 'CAI9720470.1', 'CAI9738206.1', 'CAI9737933.1']

In [92]:
from Bio import SeqIO

# Загружаем белки Octopus vulgaris
vulgaris_prots = {rec.id: rec for rec in SeqIO.parse("protein.faa", "fasta")}

# Записываем в FASTA
with open("selected_vulgaris_proteins.fasta", "w") as out:
    for pid in protein_ids:
        if pid in vulgaris_prots:
            SeqIO.write(vulgaris_prots[pid], out, "fasta")
        else:
            print(f"Не найден: {pid}")

print(f"Извлечено {len(protein_ids)} последовательностей")

Извлечено 715 последовательностей

# Фон

In [93]:
# Группируем по region_type и суммируем длины
region_lengths = regions_df.groupby('region_type').apply(
    lambda x: (x['end_half'] - x['start_half']).sum()
).to_dict()

print("Длины регионов (bp):")
for region, length in region_lengths.items():
    print(f"  {region}: {length:,}")

# Общая длина всех регионов (они не перекрываются, поэтому сумма = длина генома, покрытая этими категориями)
total_annotated_length = sum(region_lengths.values())
print(f"\nОбщая аннотированная длина: {total_annotated_length:,} bp")

Длины регионов (bp):
  Downstream: 5,025,482
  Exons: 1,462,556,279
  Intergenic: 1,723,494,774
  Introns: 1,011,276,011
  Promoters: 25,126,656

Общая аннотированная длина: 4,227,479,202 bp

/tmp/ipykernel_3034/3017193055.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  region_lengths = regions_df.groupby('region_type').apply(

In [94]:
total_g4 = len(g4)
total_zhun = len(zhunt)
total_zdnabert = len(zdnabert)

print(f"Всего G4: {total_g4}")
print(f"Всего Zhun: {total_zhun}")
print(f"Всего ZDNABERT: {total_zdnabert}")

Всего G4: 83930
Всего Zhun: 810
Всего ZDNABERT: 212403

In [95]:
from collections import defaultdict

def count_structures_in_region_trees(region_trees, struct_trees):
    """
    region_trees: dict {region_type: {seqid: IntervalTree}}
    struct_trees: dict {seqid: IntervalTree}
    Возвращает dict {region_type: количество структур}
    """
    counts = defaultdict(int)
    for region_type, r_trees in region_trees.items():
        for seqid, rtree in r_trees.items():
            if seqid not in struct_trees:
                continue
            stree = struct_trees[seqid]
            # Для каждого интервала региона ищем пересечения со структурами
            for r_interval in rtree:
                overlaps = stree.overlap(r_interval.begin, r_interval.end)
                counts[region_type] += len(overlaps)
    return counts

real_g4 = count_structures_in_region_trees(region_trees, g4_trees)
real_zhun = count_structures_in_region_trees(region_trees, zhun_trees)
real_zdnabert = count_structures_in_region_trees(region_trees, zdnabert_trees)

In [96]:
region_lengths = regions_df.groupby('region_type').apply(
    lambda x: (x['end_half'] - x['start_half']).sum()
).to_dict()
total_length = sum(region_lengths.values())

/tmp/ipykernel_3034/3613791045.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  region_lengths = regions_df.groupby('region_type').apply(

In [97]:
total_g4 = len(g4)
total_zhun = len(zhunt)
total_zdnabert = len(zdnabert)

expected_g4 = {r: (l / total_length) * total_g4 for r, l in region_lengths.items()}
expected_zhun = {r: (l / total_length) * total_zhun for r, l in region_lengths.items()}
expected_zdnabert = {r: (l / total_length) * total_zdnabert for r, l in region_lengths.items()}

In [98]:
enrich_g4 = {r: real_g4.get(r, 0) / expected_g4[r] for r in region_lengths}
enrich_zhun = {r: real_zhun.get(r, 0) / expected_zhun[r] for r in region_lengths}
enrich_zdnabert = {r: real_zdnabert.get(r, 0) / expected_zdnabert[r] for r in region_lengths}

In [99]:
import pandas as pd

rows = []
for region in region_lengths:
    rows.append({
        'Region': region,
        'Length (bp)': region_lengths[region],
        'G4 real': real_g4.get(region, 0),
        'G4 expected': round(expected_g4[region], 1),
        'G4 enrichment': round(enrich_g4[region], 2),
        'Zhun real': real_zhun.get(region, 0),
        'Zhun expected': round(expected_zhun[region], 1),
        'Zhun enrichment': round(enrich_zhun[region], 2),
        'ZDNABERT real': real_zdnabert.get(region, 0),
        'ZDNABERT expected': round(expected_zdnabert[region], 1),
        'ZDNABERT enrichment': round(enrich_zdnabert[region], 2),
    })

df_compare = pd.DataFrame(rows)
print(df_compare.to_string(index=False))

    Region  Length (bp)  G4 real  G4 expected  G4 enrichment  Zhun real  Zhun expected  Zhun enrichment  ZDNABERT real  ZDNABERT expected  ZDNABERT enrichment
Downstream      5025482      148         99.8           1.48          1            1.0             1.04            189              252.5                 0.75
     Exons   1462556279    43539      29036.8           1.50        288          280.2             1.03          74769            73483.8                 1.02
Intergenic   1723494774    51165      34217.3           1.50        578          330.2             1.75         152989            86594.3                 1.77
   Introns   1011276011    31202      20077.3           1.55        225          193.8             1.16          56031            50810.0                 1.10
 Promoters     25126656     1376        498.9           2.76          6            4.8             1.25           2656             1262.4                 2.10

In [100]:
df_compare

,Region,Length (bp),G4 real,G4 expected,G4 enrichment,Zhun real,Zhun expected,Zhun enrichment,ZDNABERT real,ZDNABERT expected,ZDNABERT enrichment
0,Downstream,5025482,148,99.8,1.48,1,1.0,1.04,189,252.5,0.75
1,Exons,1462556279,43539,29036.8,1.50,288,280.2,1.03,74769,73483.8,1.02
2,Intergenic,1723494774,51165,34217.3,1.50,578,330.2,1.75,152989,86594.3,1.77
3,Introns,1011276011,31202,20077.3,1.55,225,193.8,1.16,56031,50810.0,1.10
4,Promoters,25126656,1376,498.9,2.76,6,4.8,1.25,2656,1262.4,2.10